REGIONS = {u'ad': u'Andora',
 u'ae': u'U.A.E.',
 u'af': u'Afganistan',
 u'ag': u'Antigua ne Baabuda',
 u'ai': u'Anguila',
 u'al': u'Albenia',
 u'am': u'Aam\u025bnia',
 u'an': u'N\u025bd\u025bland Antelez',
 u'ao': u'Angola',
 u'aq': u'Antaktika',
 u'ar': u'Agy\u025bntina',
 u'as': u'Am\u025brika Samoa',
 u'at': u'\u0186stria',
 u'au': u'\u0186strelia',
 u'aw': u'Aruba',
 u'ax': u'\xc5land Islands',
 u'az': u'Azebaegyan',
 u'ba': u'Bosnia ne H\u025bzegovina',
 u'bb': u'Baabados',
 u'bd': u'Banglad\u025bhye',
 u'be': u'B\u025blgyium',
 u'bf': u'B\u0254kina Faso',
 u'bg': u'B\u0254lgeria',
 u'bh': u'Baren',
 u'bi': u'Burundi',
 u'bj': u'B\u025bnin',
 u'bl': u'Saint Barthelemy',
 u'bm': u'B\u025bmuda',
 u'bn': u'Brunae Darusalam',
 u'bo': u'Bolivia',
 u'br': u'Brazil',
 u'bs': u'Bahama',
 u'bt': u'Butan',
 u'bv': u'Buv\u025bt Island',
 u'bw': u'B\u0254tswana',
 u'by': u'B\u025blarus',
 u'bz': u'Beliz',
 u'ca': u'Kanada',
 u'cc': u'Kokos (Keeling) Islands',
 u'cd': u'Kongo-Kinhyasa',
 u'cf': u'Afrika Finimfin Man',
 u'cg': u'Kongo-Brazavil',
 u'ch': u'Swetzaland',
 u'ci': u"La C\xf4te d'Ivoire",
 u'ck': u'Kook Nsup\u0254w',
 u'cl': u'Kyili',
 u'cm': u'Kam\u025brun',
 u'cn': u'Kyaena',
 u'co': u'Kolombia',
 u'cr': u'K\u0254sta Rika',
 u'cu': u'Kuba',
 u'cv': u'Kepv\u025bdfo Islands',
 u'cx': u'Kristmas Island',
 u'cy': u'Saepr\u0254s',
 u'cz': u'Ky\u025bk Kurok\u025bse',
 u'de': u'Gyaaman',
 u'dj': u'Gyibuti',
 u'dk': u'D\u025bnmak',
 u'dm': u'D\u0254meneka',
 u'do': u'D\u0254meneka Kurok\u025bse',
 u'dz': u'\u0186lgyeria',
 u'ec': u'Ikuwad\u0254',
 u'ee': u'\u0190stonia',
 u'eg': u'Nisrim',
 u'eh': u'Westen Sahara',
 u'er': u'\u0190ritrea',
 u'es': u'Spain',
 u'et': u'Ithiopia',
 u'fi': u'Finland',
 u'fj': u'Figyi',
 u'fk': u'F\u0254lkman Aeland (Malvinafo)',
 u'fm': u'Maekronehyia',
 u'fo': u'Farofo Aeland',
 u'fr': u'Fr\u025bnkyeman',
 u'ga': u'Gab\u0254n',
 u'gb': u'Ahendiman Nkabom',
 u'gd': u'Grenada',
 u'ge': u'Gy\u0254gyea',
 u'gf': u'Fr\u025bnkye Gayana',
 u'gg': u'Gw\u025bnsey',
 u'gh': u'Gaana',
 u'gi': u'Gyebralta',
 u'gl': u'Greenman',
 u'gm': u'Gambia',
 u'gn': u'Gini',
 u'gp': u'Guwadelup',
 u'gq': u'Gini Ikuweta',
 u'gr': u'Greekman',
 u'gs': u'Gy\u0254gyia Anaafo \u025bne Sandwich Aeland Anaafo',
 u'gt': u'Guwatemala',
 u'gu': u'Guam',
 u'gw': u'Gini-Bisaw',
 u'gy': u'Gayana',
 u'hk': u'Hong Kong',
 u'hm': u'Heard Aeland \u025bne McDonald Aeland',
 u'hn': u'H\u0254nduras',
 u'hr': u'Krowehyia',
 u'ht': u'Heiti',
 u'hu': u'Hangari',
 u'id': u'Ind\u0254nehyia',
 u'ie': u'Aereland',
 u'il': u'Israel',
 u'im': u'Isle of Man',
 u'in': u'India',
 u'io': u'Britainfo H\u0254n Man W\u0254 India Po No Mu',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'Aesland',
 u'it': u'Itali',
 u'je': u'Gy\u025b\u025bsey',
 u'jm': u'Gyameka',
 u'jo': u'Gy\u0254dan',
 u'jp': u'Gyapan',
 u'ke': u'K\u025bnya',
 u'kg': u'K\u025b\u025bgestan',
 u'kh': u'Kambodia',
 u'ki': u'Kiribati',
 u'km': u'K\u0254m\u0254r\u0254s',
 u'kn': u'Saint Kitts and N\u025bves',
 u'kp': u'Etifi Koria',
 u'kr': u'Anaafo Koria',
 u'kw': u'Kuwete',
 u'ky': u'Kemanfo Islands',
 u'kz': u'Kazakstan',
 u'la': u'Laos',
 u'lb': u'L\u025bban\u0254n',
 u'lc': u'Saint Lucia',
 u'li': u'Lektenstaen',
 u'lk': u'Sri Lanka',
 u'lr': u'Laeberia',
 u'ls': u'L\u025bsutu',
 u'lt': u'Lituwenia',
 u'lu': u'Laksemb\u025bg',
 u'lv': u'Latvia',
 u'ly': u'Libya',
 u'ma': u'Moroko',
 u'mc': u'M\u0254nako',
 u'md': u'M\u0254ldova',
 u'me': u'M\u0254nten\u025bgro',
 u'mf': u'Saint Maten',
 u'mg': u'Madagaska',
 u'mh': u'Marshall Islands',
 u'mk': u'Masedonia, F.Y.R. fo',
 u'ml': u'Mali',
 u'mm': u'Miyanma',
 u'mn': u'M\u0254ngolia',
 u'mo': u'Makao',
 u'mp': u'Northern Mariana Islands',
 u'mq': u'Matinik',
 u'mr': u'M\u0254retenia',
 u'ms': u'Mantserat',
 u'mt': u'M\u0254lta',
 u'mu': u'M\u0254rehye\u0254s',
 u'mv': u'Maldives',
 u'mw': u'Malawi',
 u'mx': u'M\u025bksiko',
 u'my': u'Malehyia',
 u'mz': u'Mozambik',
 u'na': u'Namibia',
 u'nc': u'Kaledonia Foforo',
 u'ne': u'Nigy\u025b',
 u'nf': u'N\u0254folk Aeland',
 u'ng': u'Naegyeria',
 u'ni': u'Nekaraguwa',
 u'nl': u'N\u025bd\u025bland',
 u'no': u'N\u0254\u0254we',
 u'np': u'N\u025bp\u0254l',
 u'nr': u'Naworu',
 u'nu': u'Niyu',
 u'nz': u'Ziland Foforo',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Fr\u025bnkye Polynehyia',
 u'pg': u'Papua Guinea Foforo',
 u'ph': u'Philippines',
 u'pk': u'Pakistan',
 u'pl': u'Poland',
 u'pm': u'Saint Pierre ne Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Pu\u025bto Riko',
 u'ps': u'Palestaenfo Asaase a W\u0254agye \u025bte so',
 u'pt': u'P\u0254tugal',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Kata',
 u're': u'Reyuni\u0254n',
 u'ro': u'Romenia',
 u'rs': u'S\u025b\u025bbia',
 u'ru': u'R\u0254hyea Amankabom',
 u'rw': u'Rwanda',
 u'sa': u'Saudi Arabia',
 u'sb': u'Solomon Islands',
 u'sc': u'Seyhy\u025bl',
 u'sd': u'Sudan',
 u'se': u'Sweden',
 u'sg': u'Singap\u0254',
 u'sh': u'Saint Helena',
 u'si': u'Slovinia',
 u'sj': u'Svalbard ne Jan Mayen',
 u'sk': u'Slovakia',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalia',
 u'sr': u'Suriname',
 u'st': u'S\xe3o Tom\xe9 ne Pr\xedncipe',
 u'sv': u'\u0190l Salvad\u0254',
 u'sy': u'Siria',
 u'sz': u'Swaziland',
 u'tc': u'Turks ne Caicos Islands',
 u'td': u'Kyad',
 u'tf': u'Fr\u025bnkye Anaafo Mp\u0254tam',
 u'tg': u'Togo',
 u'th': u'Taeland',
 u'tj': u'Tajikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor-Leste',
 u'tm': u'T\u025bkm\u025bnistan',
 u'tn': u'Tunihyia',
 u'to': u'Tonga',
 u'tr': u'T\u025b\u025bki',
 u'tt': u'Trinidad ne Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanzania',
 u'ua': u'Ukren',
 u'ug': u'Uganda',
 u'um': u'Am\u025brika Aeland nketewaa a w\u0254da nky\u025bnky\u025bn',
 u'us': u'Am\u025brika',
 u'uy': u'Yurugwae',
 u'uz': u'Uzb\u025bkistan',
 u'va': u'Vatikan Man',
 u'vc': u'Saint Vincent ne Grenadines',
 u've': u'Venezuela',
 u'vg': u'Britainfo Virgin Islands',
 u'vi': u'Am\u025brika Virgin Islands',
 u'vn': u'Vi\u025btnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis ne Futuna',
 u'ws': u'Samoa',
 u'ye': u'Y\u025bm\u025bn',
 u'yt': u'May\u0254te',
 u'za': u'Afrika Anaafo',
 u'zm': u'Zambia',
 u'zw': u'Zembabwe'}