REGIONS = {u'ad': u'Andorra',
 u'ae': u'U.A.E.',
 u'af': u'Afghanistan',
 u'ag': u'Antigua ha Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albania',
 u'am': u'Armenia',
 u'an': u'Antilhez an Nederland',
 u'ao': u'Angola',
 u'aq': u'Adarzhrod',
 u'ar': u"Arc'hantina",
 u'as': u'Samoa Americat',
 u'at': u'Aostria',
 u'au': u'Aostralia',
 u'aw': u'Aruba',
 u'ax': u'Inizi \xc5land',
 u'az': u'Azerbaijan',
 u'ba': u'Bosnia ha Herzegovina',
 u'bb': u'Barbadoz',
 u'bd': u'Bangladesh',
 u'be': u'Belgia',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgaria',
 u'bh': u'Bahrein',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Sant Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei Darussalam',
 u'bo': u'Bolivia',
 u'br': u'Brazil',
 u'bs': u'Bahamaz',
 u'bt': u'Bhutan',
 u'bv': u'Enez Bouvet',
 u'bw': u'Botswana',
 u'by': u'Belarus',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Inizi Kokoz (Keeling)',
 u'cd': u'Kongo-Kinshasa',
 u'cf': u'Republik Africat Kreiz',
 u'cg': u'Kongo-Brazzaville',
 u'ch': u'Suis',
 u'ci': u'Aodo\xf9 an Dent Olifant',
 u'ck': u'Inizi Cook',
 u'cl': u'Chili',
 u'cm': u'Kameroun',
 u'cn': u'Sina',
 u'co': u'Kolombia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Cape Verde',
 u'cx': u'Inizi Nedeleg',
 u'cy': u'Kiprenez',
 u'cz': u'Republik Tcheg',
 u'de': u'Alamagn',
 u'dj': u'Djibouti',
 u'dk': u'Denmark',
 u'dm': u'Dominika',
 u'do': u'Republik Dominikan',
 u'dz': u'Aljeria',
 u'ec': u'Keheder',
 u'ee': u'Estonia',
 u'eg': u'Egipt',
 u'eh': u"Sahara ar C'horn\xf4g",
 u'er': u'Eritrea',
 u'es': u'Bro-Spagn',
 u'et': u'Ethiopia',
 u'fi': u'Finland',
 u'fj': u'Fiji',
 u'fk': u'Inizi Falkland (Malvinas)',
 u'fm': u'Mikronezia',
 u'fo': u'Inizi Faroe',
 u'fr': u"Bro-C'hall",
 u'ga': u'Gabon',
 u'gb': u'Rouantelezh-Unanet',
 u'gd': u'Grenada',
 u'ge': u'Georgia',
 u'gf': u"Gwiana C'hall",
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Groenland',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'Guinea ar Cheheder',
 u'gr': u'Gres',
 u'gs': u'Inizi Georgia ar Su hah Inizi Sandwich ar Su',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Enez Heard hag Inizi McDonald',
 u'hn': u'Honduraz',
 u'hr': u'Kroatia',
 u'ht': u'Haiti',
 u'hu': u'Hungaria',
 u'id': u'Indonezia',
 u'ie': u'Iwerzhon',
 u'il': u'Israel',
 u'im': u'Enez Manav',
 u'in': u'India',
 u'io': u'Douaro\xf9 Saoz Meurvor India',
 u'iq': u'Iraq',
 u'ir': u'Iran',
 u'is': u'Island',
 u'it': u'Italia',
 u'je': u'Jersey',
 u'jm': u'Jamaika',
 u'jo': u'Jordania',
 u'jp': u'Japon',
 u'ke': u'Kenya',
 u'kg': u'Kyrgyzstan',
 u'kh': u'Kambodia',
 u'ki': u'Kiribati',
 u'km': u'Komoros',
 u'kn': u'Sant Kitts ha Nevis',
 u'kp': u'Korea Hanternoz',
 u'kr': u'Korea Su',
 u'kw': u'Koweit',
 u'ky': u'Inizi Kayman',
 u'kz': u'Kazakhstan',
 u'la': u'Laos',
 u'lb': u'Liban',
 u'lc': u'Sant Lusia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Lithuania',
 u'lu': u'Luksembourg',
 u'lv': u'Latvia',
 u'ly': u'Libia',
 u'ma': u'Maroko',
 u'mc': u'Monako',
 u'md': u'Moldova, Republik',
 u'me': u'Montenegro',
 u'mf': u'Sant Martin',
 u'mg': u'Madagascar',
 u'mh': u'Inizi Marshall',
 u'mk': u'Makedonia, F.Y.R. eus',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongolia',
 u'mo': u'Makao',
 u'mp': u'Inizi Mariana an Norzh',
 u'mq': u'Martinique',
 u'mr': u'Mauritania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Maldives',
 u'mw': u'Malawi',
 u'mx': u"Mec'hiko",
 u'my': u'Malayzia',
 u'mz': u'Mozambik',
 u'na': u'Namibia',
 u'nc': u'Kaledonia Nevez',
 u'ne': u'Niger',
 u'nf': u'Enez Norfolk',
 u'ng': u'Nigeria',
 u'ni': u'Nikaragua',
 u'nl': u'Nederland',
 u'no': u'Norvegia',
 u'np': u'Nepal',
 u'nr': u'Naurueg',
 u'nu': u'Niue',
 u'nz': u'Zeland Nevez',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Perou',
 u'pf': u"Polynezia C'hall",
 u'pg': u'Papua Guinea Nevez',
 u'ph': u'Filipinez',
 u'pk': u'Pakistan',
 u'pl': u'Polonia',
 u'pm': u'Sant Per ha Mikelon',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Rico',
 u'ps': u"Douar Palestiniat ac'hubet",
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Qatar',
 u're': u'Reunion',
 u'ro': u'Romania',
 u'rs': u'Serbia',
 u'ru': u'Rusia',
 u'rw': u'Rwanda',
 u'sa': u'Arabia Saoudat',
 u'sb': u'Inizi Solomon',
 u'sc': u'Seychelles',
 u'sd': u'Sudan',
 u'se': u'Sveden',
 u'sg': u'Singapour',
 u'sh': u'Santez Helena',
 u'si': u'Slovenia',
 u'sj': u'Svalbard ha Jan Mayen',
 u'sk': u'Slovakia',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalia',
 u'sr': u'Suriname',
 u'st': u'Sao Tome ha Principe',
 u'sv': u'El Salvador',
 u'sy': u'Siria',
 u'sz': u'Swaziland',
 u'tc': u'Inizi Turks ha Caicos',
 u'td': u'Chad',
 u'tf': u'Douaro\xf9 Gall ar Su',
 u'tg': u'Togo',
 u'th': u'Thailand',
 u'tj': u'Tajikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor-Leste',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunizia',
 u'to': u'Tongeg',
 u'tr': u'Turkia',
 u'tt': u'Trinidad ha Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanzania',
 u'ua': u'Ukraine',
 u'ug': u'Uganda',
 u'um': u'Inizi digenvez Stao\xf9-Unanet',
 u'us': u'Stado\xf9 Unanet',
 u'uy': u'Uruguay',
 u'uz': u'Uzbekistan',
 u'va': u'K\xear Vatican',
 u'vc': u'Sant Visent hag Grenadin',
 u've': u'Venezuela',
 u'vg': u"Inizi Gwerc'h Saoz",
 u'vi': u"Inizi Gwerc'h Stado\xf9 Unanet",
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis ha Futuna',
 u'ws': u'Samoa',
 u'ye': u'Yemen',
 u'yt': u'Mayotte',
 u'za': u'Afrika Su',
 u'zm': u'Zambia',
 u'zw': u'Zimbabwe'}