REGIONS = {u'ad': u'Andorra',
 u'ae': u'Emirats \xc0rabs Units',
 u'af': u'Afganistan',
 u'ag': u'Antigua i Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Alb\xe0nia',
 u'am': u'Arm\xe8nia',
 u'an': u'Antilles Neerlandeses',
 u'ao': u'Angola',
 u'aq': u'Ant\xe0rtida',
 u'ar': u'Argentina',
 u'as': u'Samoa Nord-americana',
 u'at': u'\xc0ustria',
 u'au': u'Austr\xe0lia',
 u'aw': u'Aruba',
 u'ax': u'Illes \xc5land',
 u'az': u'Azerbaidjan',
 u'ba': u'B\xf2snia i Hercegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangla Desh',
 u'be': u'B\xe8lgica',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulg\xe0ria',
 u'bh': u'Bahrain',
 u'bi': u'Burundi',
 u'bj': u'Ben\xedn',
 u'bl': u'Saint-Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei',
 u'bo': u'Bol\xedvia',
 u'br': u'Brasil',
 u'bs': u'Bahames',
 u'bt': u'Bhutan',
 u'bv': u'Bouvet',
 u'bw': u'Botswana',
 u'by': u'Bielor\xfassia',
 u'bz': u'Belize',
 u'ca': u'Canad\xe0',
 u'cc': u'Illes Cocos (Keeling)',
 u'cd': u'Congo Kinshasa',
 u'cf': u'Rep\xfablica Centreafricana',
 u'cg': u'Congo Brazzaville',
 u'ch': u'Su\xefssa',
 u'ci': u"Costa d'Ivori",
 u'ck': u'Illes Cook',
 u'cl': u'Xile',
 u'cm': u'Camerun',
 u'cn': u'Xina',
 u'co': u'Col\xf2mbia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Cap Verd',
 u'cx': u'Illa Christmas',
 u'cy': u'Xipre',
 u'cz': u'Rep\xfablica Txeca',
 u'de': u'Alemanya',
 u'dj': u'Djibouti',
 u'dk': u'Dinamarca',
 u'dm': u'Dominica',
 u'do': u'Rep\xfablica Dominicana',
 u'dz': u'Alg\xe8ria',
 u'ec': u'Equador',
 u'ee': u'Est\xf2nia',
 u'eg': u'Egipte',
 u'eh': u'S\xe0hara Occidental',
 u'er': u'Eritrea',
 u'es': u'Espanya',
 u'et': u'Eti\xf2pia',
 u'fi': u'Finl\xe0ndia',
 u'fj': u'Fiji',
 u'fk': u'Illes Malvines',
 u'fm': u'Micron\xe8sia',
 u'fo': u'Illes F\xe8roe',
 u'fr': u'Fran\xe7a',
 u'ga': u'Gabon',
 u'gb': u'Regne Unit',
 u'gd': u'Grenada',
 u'ge': u'Ge\xf2rgia',
 u'gf': u'Guaiana francesa',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Grenl\xe0ndia',
 u'gm': u'G\xe0mbia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'Guinea Equatorial',
 u'gr': u'Gr\xe8cia',
 u'gs': u'Illes Ge\xf2rgia del Sud i Sandwich del Sud',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Illa de Heard i illes McDonald',
 u'hn': u'Hondures',
 u'hr': u'Cro\xe0cia',
 u'ht': u'Hait\xed',
 u'hu': u'Hongria',
 u'id': u'Indon\xe8sia',
 u'ie': u'Irlanda',
 u'il': u'Israel',
 u'im': u'Illa de Man',
 u'in': u'\xcdndia',
 u'io': u"Territori Brit\xe0nic de l'Oce\xe0 \xcdndic",
 u'iq': u'Iraq',
 u'ir': u'Iran',
 u'is': u'Isl\xe0ndia',
 u'it': u'It\xe0lia',
 u'je': u'Jersey',
 u'jm': u'Jamaica',
 u'jo': u'Jord\xe0nia',
 u'jp': u'Jap\xf3',
 u'ke': u'Kenya',
 u'kg': u'Kirguizistan',
 u'kh': u'Cambodja',
 u'ki': u'Kiribati',
 u'km': u'Comores',
 u'kn': u'Saint Kitts i Nevis',
 u'kp': u'Corea del Nord',
 u'kr': u'Corea del Sud',
 u'kw': u'Kuwait',
 u'ky': u'Illes Caiman',
 u'kz': u'Kazakhstan',
 u'la': u'Laos',
 u'lb': u'L\xedban',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Lib\xe8ria',
 u'ls': u'Lesotho',
 u'lt': u'Litu\xe0nia',
 u'lu': u'Luxemburg',
 u'lv': u'Let\xf2nia',
 u'ly': u'L\xedbia',
 u'ma': u'Marroc',
 u'mc': u'M\xf2naco',
 u'md': u'Rep\xfablica de Mold\xe0via',
 u'me': u'Montenegro',
 u'mf': u'Saint-Martin',
 u'mg': u'Madagascar',
 u'mh': u'Illes Marshall',
 u'mk': u'Maced\xf2nia',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mong\xf2lia',
 u'mo': u'Macau',
 u'mp': u'Illes Mariannes Septentrionals',
 u'mq': u'Martinica',
 u'mr': u'Maurit\xe0nia',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Maurici',
 u'mv': u'Maldives',
 u'mw': u'Malawi',
 u'mx': u'M\xe8xic',
 u'my': u'Mal\xe0isia',
 u'mz': u'Mo\xe7ambic',
 u'na': u'Nam\xedbia',
 u'nc': u'Nova Caled\xf2nia',
 u'ne': u'N\xedger',
 u'nf': u'Illa de Norfolk',
 u'ng': u'Nig\xe8ria',
 u'ni': u'Nicaragua',
 u'nl': u'Pa\xefsos Baixos',
 u'no': u'Noruega',
 u'np': u'Nepal',
 u'nr': u'Na\xfcru',
 u'nu': u'Niue',
 u'nz': u'Nova Zelanda',
 u'om': u'Oman',
 u'pa': u'Panam\xe0',
 u'pe': u'Per\xfa',
 u'pf': u'Polin\xe8sia Francesa',
 u'pg': u'Papua Nova Guinea',
 u'ph': u'Filipines',
 u'pk': u'Pakistan',
 u'pl': u'Pol\xf2nia',
 u'pm': u'Saint-Pierre i Miquelon',
 u'pn': u'Illes Pitcairn',
 u'pr': u'Puerto Rico',
 u'ps': u'Territori Ocupat de Palestina',
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguai',
 u'qa': u'Qatar',
 u're': u'Illa de la Reuni\xf3',
 u'ro': u'Romania',
 u'rs': u'S\xe8rbia',
 u'ru': u'R\xfassia',
 u'rw': u'Rwanda',
 u'sa': u'Ar\xe0bia Saudita',
 u'sb': u'Illes Salom\xf3',
 u'sc': u'Seychelles',
 u'sd': u'Sudan',
 u'se': u'Su\xe8cia',
 u'sg': u'Singapur',
 u'sh': u'Santa Helena',
 u'si': u'Eslov\xe8nia',
 u'sj': u'Svalbard i Jan Mayen',
 u'sk': u'Eslov\xe0quia',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Som\xe0lia',
 u'sr': u'Surinam',
 u'st': u'S\xe3o Tom\xe9 i Pr\xedncipe',
 u'sv': u'El Salvador',
 u'sy': u'S\xedria',
 u'sz': u'Swazil\xe0ndia',
 u'tc': u'Illes Turks i Caicos',
 u'td': u'Txad',
 u'tf': u'Terres Australs i Ant\xe0rtiques Franceses',
 u'tg': u'Togo',
 u'th': u'Tail\xe0ndia',
 u'tj': u'Tadjikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor Oriental',
 u'tm': u'Turcmenistan',
 u'tn': u'Tun\xedsia',
 u'to': u'Tonga',
 u'tr': u'Turquia',
 u'tt': u'Trinitat',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanz\xe0nia',
 u'ua': u'Ucra\xefna',
 u'ug': u'Uganda',
 u'um': u'Illes Perif\xe8riques Menors dels EUA',
 u'us': u'Estats Units',
 u'uy': u'Uruguai',
 u'uz': u'Uzbekistan',
 u'va': u'Ciutat del Vatic\xe0',
 u'vc': u'Saint Vincent i les Grenadines',
 u've': u'Vene\xe7uela',
 u'vg': u'Illes Verges Brit\xe0niques',
 u'vi': u'Illes Verges Nord-americanes',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis i Futuna',
 u'ws': u'Samoa',
 u'ye': u'Iemen',
 u'yt': u'Mayotte',
 u'za': u'Sud-\xe0frica',
 u'zm': u'Z\xe0mbia',
 u'zw': u'Zimbabwe'}