REGIONS = {u'ad': u'Andorra',
 u'ae': u'Vereinigte Arabische Emirate',
 u'af': u'Afghanistan',
 u'ag': u'Antigua und Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albanien',
 u'am': u'Armenien',
 u'an': u'Niederl\xe4ndische Antillen',
 u'ao': u'Angola',
 u'aq': u'Antarktis',
 u'ar': u'Argentinien',
 u'as': u'Samoa',
 u'at': u'\xd6sterreich',
 u'au': u'Australien',
 u'aw': u'Aruba',
 u'ax': u'\xc5land',
 u'az': u'Aserbaidschan',
 u'ba': u'Bosnien und Herzegowina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesch',
 u'be': u'Belgien',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgarien',
 u'bh': u'Bahrain',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Sankt Bartholom\xe4us',
 u'bm': u'Bermuda',
 u'bn': u'Brunei',
 u'bo': u'Bolivien',
 u'br': u'Brasilien',
 u'bs': u'Bahamas',
 u'bt': u'Bhutan',
 u'bv': u'Bouvetinsel',
 u'bw': u'Botsuana',
 u'by': u'Wei\xdfrussland',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Kokosinseln (Keelinginseln)',
 u'cd': u'Demokratische Republik Kongo',
 u'cf': u'Zentralafrikanische Republik',
 u'cg': u'Republik Kongo',
 u'ch': u'Schweiz',
 u'ci': u'Elfenbeink\xfcste',
 u'ck': u'Cookinseln',
 u'cl': u'Chile',
 u'cm': u'Kamerun',
 u'cn': u'China',
 u'co': u'Kolumbien',
 u'cr': u'Costa Rica',
 u'cu': u'Kuba',
 u'cv': u'Kap Verde',
 u'cx': u'Weihnachtsinsel',
 u'cy': u'Zypern',
 u'cz': u'Tschechische Republik',
 u'de': u'Deutschland',
 u'dj': u'Dschibuti',
 u'dk': u'D\xe4nemark',
 u'dm': u'Dominica',
 u'do': u'Dominikanische Republik',
 u'dz': u'Algerien',
 u'ec': u'Ecuador',
 u'ee': u'Estland',
 u'eg': u'\xc4gypten',
 u'eh': u'Westsahara',
 u'er': u'Eritrea',
 u'es': u'Spanien',
 u'et': u'\xc4thiopien',
 u'fi': u'Finnland',
 u'fj': u'Fidschi',
 u'fk': u'Falklandinseln (Malwinen)',
 u'fm': u'Mikronesien',
 u'fo': u'F\xe4r\xf6er',
 u'fr': u'Frankreich',
 u'ga': u'Gabun',
 u'gb': u'Gro\xdfbritannien',
 u'gd': u'Grenada',
 u'ge': u'Georgien',
 u'gf': u'Franz\xf6sisch-Guayana',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Gr\xf6nland',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'\xc4quatorialguinea',
 u'gr': u'Griechenland',
 u'gs': u'S\xfcdgeorgien und die S\xfcdlichen Sandwichinseln',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hongkong',
 u'hm': u'Heard und McDonaldinseln',
 u'hn': u'Honduras',
 u'hr': u'Kroatien',
 u'ht': u'Haiti',
 u'hu': u'Ungarn',
 u'id': u'Indonesien',
 u'ie': u'Irland',
 u'il': u'Israel',
 u'im': u'Isle of Man',
 u'in': u'Indien',
 u'io': u'Britisches Territorium im Indischen Ozean',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'Island',
 u'it': u'Italien',
 u'je': u'Jersey',
 u'jm': u'Jamaika',
 u'jo': u'Jordanien',
 u'jp': u'Japan',
 u'ke': u'Kenia',
 u'kg': u'Kirgisistan',
 u'kh': u'Kambodscha',
 u'ki': u'Kiribati',
 u'km': u'Komoren',
 u'kn': u'St. Kitts und Nevis',
 u'kp': u'Nordkorea',
 u'kr': u'S\xfcdkorea',
 u'kw': u'Kuwait',
 u'ky': u'Kaimaninseln',
 u'kz': u'Kasachstan',
 u'la': u'Laos',
 u'lb': u'Libanon',
 u'lc': u'St. Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Litauen',
 u'lu': u'Luxemburg',
 u'lv': u'Lettland',
 u'ly': u'Libyen',
 u'ma': u'Marokko',
 u'mc': u'Monaco',
 u'md': u'Moldawien',
 u'me': u'Montenegro',
 u'mf': u'Saint-Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Marshallinseln',
 u'mk': u'Mazedonien',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongolei',
 u'mo': u'Macao',
 u'mp': u'N\xf6rdliche Marianen',
 u'mq': u'Martinique',
 u'mr': u'Mauretanien',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Malediven',
 u'mw': u'Malawi',
 u'mx': u'Mexiko',
 u'my': u'Malaysia',
 u'mz': u'Mosambik',
 u'na': u'Namibia',
 u'nc': u'Neukaledonien',
 u'ne': u'Niger',
 u'nf': u'Norfolkinsel',
 u'ng': u'Nigeria',
 u'ni': u'Nicaragua',
 u'nl': u'Niederlande',
 u'no': u'Norwegen',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Neuseeland',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Franz\xf6sisch-Polynesien',
 u'pg': u'Papua-Neuguinea',
 u'ph': u'Philippinen',
 u'pk': u'Pakistan',
 u'pl': u'Polen',
 u'pm': u'Saint-Pierre und Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Rico',
 u'ps': u'Pal\xe4stinensische Autonomiegebiete',
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Katar',
 u're': u'R\xe9union',
 u'ro': u'Rum\xe4nien',
 u'rs': u'Serbien',
 u'ru': u'Russland',
 u'rw': u'Ruanda',
 u'sa': u'Saudi-Arabien',
 u'sb': u'Salomonen',
 u'sc': u'Seychellen',
 u'sd': u'Sudan',
 u'se': u'Schweden',
 u'sg': u'Singapur',
 u'sh': u'St. Helena',
 u'si': u'Slowenien',
 u'sj': u'Svalbard und Jan Mayen',
 u'sk': u'Slowakei',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalia',
 u'sr': u'Suriname',
 u'st': u'S\xe3o Tom\xe9 und Pr\xedncipe',
 u'sv': u'El Salvador',
 u'sy': u'Syrien',
 u'sz': u'Swasiland',
 u'tc': u'Turks- und Caicosinseln',
 u'td': u'Tschad',
 u'tf': u'Franz\xf6sische S\xfcdpolarterritorien',
 u'tg': u'Togo',
 u'th': u'Thailand',
 u'tj': u'Tadschikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor-Leste',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunesien',
 u'to': u'Tonga',
 u'tr': u'T\xfcrkei',
 u'tt': u'Trinidad und Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tansania',
 u'ua': u'Ukraine',
 u'ug': u'Uganda',
 u'um': u'Au\xdfengebiete der Vereinigten Staaten',
 u'us': u'Vereinigte Staaten von Amerika',
 u'uy': u'Uruguay',
 u'uz': u'Usbekistan',
 u'va': u'Vatikanstadt',
 u'vc': u'St. Vincent und die Grenadinen',
 u've': u'Venezuela',
 u'vg': u'Britische Jungferninseln',
 u'vi': u'Amerikanische Jungferninseln',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis und Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jemen',
 u'yt': u'Mayotte',
 u'za': u'S\xfcdafrika',
 u'zm': u'Sambia',
 u'zw': u'Simbabwe'}