REGIONS = {u'ad': u'Andorra',
 u'ae': u'Z.A.E.',
 u'af': u'Afganistan',
 u'ag': u'Antigua a Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Alba\u0144ska',
 u'am': u'Arme\u0144ska',
 u'an': u'Ni\u017eozemske Antile',
 u'ao': u'Angola',
 u'aq': u'Antarktika',
 u'ar': u'Argentinska',
 u'as': u'Amerika\u0144ska Samoa',
 u'at': u'Awstriska',
 u'au': u'Awstralska',
 u'aw': u'Aruba',
 u'ax': u'\xc5landske kupy',
 u'az': u'Azerbajd\u017ean',
 u'ba': u'Bosniska a Hercegowina',
 u'bb': u'Barbados',
 u'bd': u'Banglade\u0161',
 u'be': u'Belgiska',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgarska',
 u'bh': u'Bahrain',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermudy',
 u'bn': u'Brunei Darussalam',
 u'bo': u'Boliwiska',
 u'br': u'Brazilska',
 u'bs': u'Bahamy',
 u'bt': u'Bhutan',
 u'bv': u'Bouvetska kupa',
 u'bw': u'Botswana',
 u'by': u'B\u011b\u0142oruska',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Kokoske (Keeling) kupy',
 u'cd': u'Kongo-Kinshasa',
 u'cf': u'Centralnoafrika\u0144ska republika',
 u'cg': u'Kongo-Brazzaville',
 u'ch': u'\u0160wicarska, \u0160wicojska',
 u'ci': u'S\u0142onok\xf3s\u0107owy p\xf3brjog',
 u'ck': u'Cookowe kupy',
 u'cl': u'Chilska',
 u'cm': u'Kamerun',
 u'cn': u'Chinska',
 u'co': u'Kolumbiska',
 u'cr': u'Kostarika',
 u'cu': u'Kuba',
 u'cv': u'Kap Verde',
 u'cx': u'G\xf3downa kupa',
 u'cy': u'Cypern',
 u'cz': u'\u010ceska republika',
 u'de': u'Nimska',
 u'dj': u'D\u017eibuti',
 u'dk': u'Da\u0144ska',
 u'dm': u'Dominika',
 u'do': u'Dominika\u0144ska republika',
 u'dz': u'Algeriska',
 u'ec': u'Ekuador',
 u'ee': u'Estniska',
 u'eg': u'Egyptojska',
 u'eh': u'P\xf3dwjacorna Sahara',
 u'er': u'Eritreja',
 u'es': u'\u0160pa\u0144ska',
 u'et': u'Etiopiska',
 u'fi': u'Finska',
 u'fj': u'Fid\u017ai',
 u'fk': u'Falklandske kupy (Malwiny)',
 u'fm': u'Mikroneziska, Mikronezija',
 u'fo': u'Ferejske kupy',
 u'fr': u'Francojska',
 u'ga': u'Gabun',
 u'gb': u'Zjadno\u015bone kralojstwo',
 u'gd': u'Grenada',
 u'ge': u'Georgiska',
 u'gf': u'Francojska Guyana',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Gr\xf6nlandska',
 u'gm': u'Gambija',
 u'gn': u'Guineja',
 u'gp': u'Guadeloupe',
 u'gq': u'Ekwatorialna Guineja',
 u'gr': u'Grichiska',
 u'gs': u'P\xf3dpo\u0142dnjowa Georgiska a kupy South Sandwich',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guineja-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Kupa Heard a kupy McDonald',
 u'hn': u'Honduras',
 u'hr': u'Chorwatska',
 u'ht': u'Haiti',
 u'hu': u'Hungorska',
 u'id': u'Indoneziska',
 u'ie': u'Irska',
 u'il': u'Israel',
 u'im': u'Isle of Man, kupa Man',
 u'in': u'Indiska',
 u'io': u'Britiski indiskooceaniski teritorium',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'Islandska',
 u'it': u'Italska',
 u'je': u'Jersey',
 u'jm': u'Jamaika',
 u'jo': u'Jorda\u0144ska, Jordaniska',
 u'jp': u'Japa\u0144ska',
 u'ke': u'Kenija',
 u'kg': u'Kirgiziska',
 u'kh': u'Kambod\u017ea',
 u'ki': u'Kiribati',
 u'km': u'Komory',
 u'kn': u'Saint Kitts a Nevis',
 u'kp': u'P\xf3dpo\u0142nocna Koreja',
 u'kr': u'P\xf3dpo\u0142dnjowa Koreja\xa0',
 u'kw': u'Kuwait',
 u'ky': u'Kajmanske kupy',
 u'kz': u'Kazachska',
 u'la': u'Laos',
 u'lb': u'Libanon',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Litawska',
 u'lu': u'Luxemburgska',
 u'lv': u'Letiska',
 u'ly': u'Libyska',
 u'ma': u'Marokko',
 u'mc': u'Monaco',
 u'md': u'Moldawska',
 u'me': u'Carnog\xf3rska, Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Mar\u0161alske kupy',
 u'mk': u'N.J.R. Makedo\u0144ska',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongolska',
 u'mo': u'Makao\xa0',
 u'mp': u'P\xf3dpo\u0142nocne Maria\u0144ske kupy',
 u'mq': u'Martinique',
 u'mr': u'Maureta\u0144ska',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Malediwy',
 u'mw': u'Malawi',
 u'mx': u'Mexiko',
 u'my': u'Malayzija',
 u'mz': u'Mosambik',
 u'na': u'Namibija',
 u'nc': u'Nowa Kaledonija',
 u'ne': u'Niger',
 u'nf': u'Kupa Norfolk',
 u'ng': u'Nigerija',
 u'ni': u'Nikaragua',
 u'nl': u'Ni\u017eozemska',
 u'no': u'Norwegska',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nowoseelandska',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Francojska Polyneziska',
 u'pg': u'Papua-Neuguinea',
 u'ph': u'Filipiny',
 u'pk': u'Pakistan',
 u'pl': u'P\xf3lska',
 u'pm': u'Saint Pierre a Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Riko',
 u'ps': u'Wobsaj\u017aony palestinski teritorium',
 u'pt': u'Portugalska',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Katar',
 u're': u'R\xe9union',
 u'ro': u'Rumu\u0144ska',
 u'rs': u'Serbiska',
 u'ru': u'Ruska federacija',
 u'rw': u'Ruanda',
 u'sa': u'Saudi-Arabska',
 u'sb': u'Solomonske kupy',
 u'sc': u'Seychelle',
 u'sd': u'Sudan',
 u'se': u'\u0160wedska',
 u'sg': u'Singapur',
 u'sh': u'Saint Helena',
 u'si': u'S\u0142owje\u0144ska',
 u'sj': u'Svalbard a Jan Mayen',
 u'sk': u'S\u0142owakska',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalija',
 u'sr': u'Surinam',
 u'st': u'Sao Tome a Principe',
 u'sv': u'El Salvador',
 u'sy': u'Syriska',
 u'sz': u'Swasilandska',
 u'tc': u'Kupy Turks a Caicos',
 u'td': u'\u010cad',
 u'tf': u'Francojske p\xf3dpo\u0142dnjowe teritoriumy',
 u'tg': u'Togo',
 u'th': u'Thailandska',
 u'tj': u'Tad\u017aikistan',
 u'tk': u'Tokelau',
 u'tl': u'P\xf3dzajt\u0161ny Timor',
 u'tm': u'Turkme\u0144ska',
 u'tn': u'Tuneziska',
 u'to': u'Tonga',
 u'tr': u'Turkojska',
 u'tt': u'Trinidad a Tobago',
 u'tv': u'Tuwalu',
 u'tw': u'Taiwan',
 u'tz': u'Tansanija',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'Ma\u0142e wenkowne kupy Zjadno\u015bonych statow',
 u'us': u'Zjadno\u015bone staty',
 u'uy': u'Uruguay',
 u'uz': u'Uzbekistan',
 u'va': u'Vatika\u0144ske m\u011bsto',
 u'vc': u'Saint Vincent a Grenadiny',
 u've': u'Venezuela',
 u'vg': u'Britiske knje\u017eniske kupy',
 u'vi': u'Amerika\u0144ske kn\u011b\u017eniske kupy',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis a Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jemen',
 u'yt': u'Mayotte',
 u'za': u'P\xf3dpo\u0142dnjowa Afrika',
 u'zm': u'Sambija',
 u'zw': u'Simbabwe'}