REGIONS = {u'ad': u'Andorra',
 u'ae': u'Araabia \xdchendemiraadid',
 u'af': u'Afganistan',
 u'ag': u'Antigua ja Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albaania',
 u'am': u'Armeenia',
 u'an': u'Hollandi Antillid',
 u'ao': u'Angola',
 u'aq': u'Antarktika',
 u'ar': u'Argentina',
 u'as': u'Ameerika Samoa',
 u'at': u'Austria',
 u'au': u'Austraalia',
 u'aw': u'Aruba',
 u'ax': u'Ahvenamaa',
 u'az': u'Aserbaid\u017eaan',
 u'ba': u'Bosnia ja Hertsegoviina',
 u'bb': u'Barbados',
 u'bd': u'Bangladeshi Rahvavabariik',
 u'be': u'Belgia',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgaaria',
 u'bh': u'Bahrein',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei Darussalami Riik',
 u'bo': u'Boliivia',
 u'br': u'Brasiilia',
 u'bs': u'Bahama',
 u'bt': u'Bhutani Kuningriik',
 u'bv': u"Bouvet' saar",
 u'bw': u'Botswana',
 u'by': u'Valgevene',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Kookossaared',
 u'cd': u'Kongo Demokraatlik Vabariik',
 u'cf': u'Kesk-Aafrika Vabariik',
 u'cg': u'Kongo Vabariik',
 u'ch': u'\u0160veits',
 u'ci': u'Elevandiluurannik',
 u'ck': u'Cooki saared',
 u'cl': u'T\u0161iili',
 u'cm': u'Kamerun',
 u'cn': u'Hiina',
 u'co': u'Kolumbia',
 u'cr': u'Costa Rica',
 u'cu': u'Kuuba',
 u'cv': u'Roheneemesaared',
 u'cx': u'J\xf5ulusaar',
 u'cy': u'K\xfcpros',
 u'cz': u'T\u0161ehhi',
 u'de': u'Saksamaa',
 u'dj': u'Djibouti',
 u'dk': u'Taani',
 u'dm': u'Dominica',
 u'do': u'Dominikaani Vabariik',
 u'dz': u'Al\u017eeeria',
 u'ec': u'Ecuador',
 u'ee': u'Eesti',
 u'eg': u'Egiptus',
 u'eh': u'Sahara Araabia Demokraatlik Vabariik',
 u'er': u'Eritrea',
 u'es': u'Hispaania',
 u'et': u'Etioopia',
 u'fi': u'Soome',
 u'fj': u'Fid\u017ei',
 u'fk': u'Falklandi saared',
 u'fm': u'Mikroneesia Liiduriigid',
 u'fo': u'F\xe4\xe4ri saared',
 u'fr': u'Prantsusmaa',
 u'ga': u'Gabon',
 u'gb': u'Suurbritannia',
 u'gd': u'Grenada',
 u'ge': u'Gruusia',
 u'gf': u'Prantsuse Guajaana',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Gr\xf6\xf6nimaa',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'Ekvatoriaal-Guinea',
 u'gr': u'Kreeka',
 u'gs': u'L\xf5una-Georgia',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hongkong',
 u'hm': u"Heard'i ja McDonald'i saared",
 u'hn': u'Honduras',
 u'hr': u'Horvaatia',
 u'ht': u'Haiti',
 u'hu': u'Ungari',
 u'id': u'Indoneesia',
 u'ie': u'Iirimaa',
 u'il': u'Iisrael',
 u'im': u'Man',
 u'in': u'India',
 u'io': u'Briti India ookeani ala',
 u'iq': u'Iraak',
 u'ir': u'Iraan',
 u'is': u'Island',
 u'it': u'Itaalia',
 u'je': u'Jersey',
 u'jm': u'Jamaica',
 u'jo': u'Jordaania',
 u'jp': u'Jaapan',
 u'ke': u'Keenia',
 u'kg': u'K\xf5rg\xf5zstan',
 u'kh': u'Kambod\u017ea',
 u'ki': u'Kiribati',
 u'km': u'Komoorid',
 u'kn': u'Saint Kitts and Nevis',
 u'kp': u'P\xf5hja-Korea',
 u'kr': u'L\xf5una-Korea',
 u'kw': u'Kuveit',
 u'ky': u'Kaimanisaared',
 u'kz': u'Kasahstan',
 u'la': u'Laos',
 u'lb': u'Liibanon',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Libeeria',
 u'ls': u'Lesotho',
 u'lt': u'Leedu',
 u'lu': u'Luksemburg',
 u'lv': u'L\xe4ti',
 u'ly': u'Liib\xfca',
 u'ma': u'Maroko',
 u'mc': u'Monaco',
 u'md': u'Moldova Vabariik',
 u'me': u'Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Marshalli Saared',
 u'mk': u'Makedoonia',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongoolia',
 u'mo': u'Macau',
 u'mp': u'Northern Mariana Islands',
 u'mq': u'Martinique',
 u'mr': u'Mauritaania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Maldiivid',
 u'mw': u'Malawi',
 u'mx': u'Mehhiko',
 u'my': u'Malaisia',
 u'mz': u'Mosambiik',
 u'na': u'Namiibia',
 u'nc': u'Uus-Kaledoonia',
 u'ne': u'Nigeri',
 u'nf': u'Norfolki saare ala',
 u'ng': u'Nigeeria',
 u'ni': u'Nicaragua',
 u'nl': u'Holland',
 u'no': u'Norra',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Uus-Meremaa',
 u'om': u'Omaan',
 u'pa': u'Panama',
 u'pe': u'Peruu',
 u'pf': u'Prantsuse Pol\xfcneesia',
 u'pg': u'Paapua Uus-Guinea',
 u'ph': u'Filipiinid',
 u'pk': u'Pakistan',
 u'pl': u'Poola',
 u'pm': u'Saint Pierre ja Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Rico',
 u'ps': u'Okupeeritud Palestiina ala',
 u'pt': u'Portugal',
 u'pw': u'Belau Vabariik',
 u'py': u'Paraguai',
 u'qa': u'Katar',
 u're': u'R\xe9union',
 u'ro': u'Rumeenia',
 u'rs': u'Serbia',
 u'ru': u'Venemaa',
 u'rw': u'Rwanda',
 u'sa': u'Saudi Araabia',
 u'sb': u'Saalomoni Saared',
 u'sc': u'Sei\u0161ellid',
 u'sd': u'Sudaan',
 u'se': u'Rootsi',
 u'sg': u'Singapur',
 u'sh': u'Saint Helena',
 u'si': u'Sloveenia',
 u'sj': u'Svalbard ja Jan Mayen',
 u'sk': u'Slovakkia',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somaalia',
 u'sr': u'Suriname',
 u'st': u'S\xe3o Tom\xe9 ja Pr\xedncipe',
 u'sv': u'El Salvador',
 u'sy': u'S\xfc\xfcria',
 u'sz': u'Svaasimaa',
 u'tc': u"Turksi ja Caicos' saared",
 u'td': u'T\u0161aad',
 u'tf': u'Prantsuse L\xf5unaalad',
 u'tg': u'Togo',
 u'th': u'Tai',
 u'tj': u'Tad\u017eikistan',
 u'tk': u'Tokelau',
 u'tl': u'Ida-Timor',
 u'tm': u'T\xfcrkmenistan',
 u'tn': u'Tuneesia',
 u'to': u'Tonga',
 u'tr': u'T\xfcrgi',
 u'tt': u'Trinidad ja Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tansaania',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'\xdchendriikide hajasaared',
 u'us': u'Ameerika \xdchendriigid',
 u'uy': u'Uruguay',
 u'uz': u'Usbekistan',
 u'va': u'Vatican',
 u'vc': u'Saint Vincent ja Grenadines',
 u've': u'Venezuela',
 u'vg': u'Briti Neitsisaared',
 u'vi': u'USA Neitsisaared',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis ja Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jeemen',
 u'yt': u'Mayotte',
 u'za': u'L\xf5una-Aafrika Vabariik',
 u'zm': u'Sambia',
 u'zw': u'Zimbabwe'}