REGIONS = {u'ad': u'Andorra',
 u'ae': u'U.A.E.',
 u'af': u'Afganistan',
 u'ag': u'Antigua eta Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albania',
 u'am': u'Armenia',
 u'an': u'Holandarren Antillak',
 u'ao': u'Angola',
 u'aq': u'Antartika',
 u'ar': u'Argentina',
 u'as': u'Amerikar Samoa',
 u'at': u'Austria',
 u'au': u'Australia',
 u'aw': u'Aruba',
 u'ax': u'\xc5land Uharteak',
 u'az': u'Azerbaijan',
 u'ba': u'Bosnia eta Herzegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesh',
 u'be': u'Belgika',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgaria',
 u'bh': u'Bahrain',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei Darussalam',
 u'bo': u'Bolivia',
 u'br': u'Brasil',
 u'bs': u'Bahamas',
 u'bt': u'Bhutan',
 u'bv': u'Bouvet uhartea',
 u'bw': u'Botswana',
 u'by': u'Belarus',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Cocos (Keeling) Uharteak',
 u'cd': u'Congo-Kinshasa',
 u'cf': u'Afrika Erdiko Errepublika',
 u'cg': u'Kongo-Brazzaville',
 u'ch': u'Suitza',
 u'ci': u'Boli Kosta',
 u'ck': u'Cook Uharteak',
 u'cl': u'Txile',
 u'cm': u'Kamerun',
 u'cn': u'Txina',
 u'co': u'Kolonbia',
 u'cr': u'Costa Rica',
 u'cu': u'Kuba',
 u'cv': u'Cabo Verde',
 u'cx': u'Christmas Uhartea',
 u'cy': u'Txipre',
 u'cz': u'Txekiar errepublika',
 u'de': u'Alemania',
 u'dj': u'Djibouti',
 u'dk': u'Dinamarka',
 u'dm': u'Dominika',
 u'do': u'Dominikar errepublika',
 u'dz': u'Aljeria',
 u'ec': u'Ekuador',
 u'ee': u'Estonia',
 u'eg': u'Egipto',
 u'eh': u'Mendebaldeko Sahara',
 u'er': u'Eritrea',
 u'es': u'Espainia',
 u'et': u'Etiopia',
 u'fi': u'Finlandia',
 u'fj': u'Fidji',
 u'fk': u'Falkland uharteak (Malvinak)',
 u'fm': u'Mikronesia',
 u'fo': u'Faroe uharteak',
 u'fr': u'Frantzia',
 u'ga': u'Gabon',
 u'gb': u'Erresuma Batua',
 u'gd': u'Granada',
 u'ge': u'Georgia',
 u'gf': u'Guyana Frantsesa',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Groenlandia',
 u'gm': u'Ganbia',
 u'gn': u'Ginea',
 u'gp': u'Guadalupe',
 u'gq': u'Ekuatore Ginea',
 u'gr': u'Grezia',
 u'gs': u'Hego Georgia eta Hego Sandwich Uharteak',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Heard eta McDonald Uharteak',
 u'hn': u'Honduras',
 u'hr': u'Kroazia',
 u'ht': u'Haiti',
 u'hu': u'Hungaria',
 u'id': u'Indonesia',
 u'ie': u'Irlanda',
 u'il': u'Israel',
 u'im': u'Man uhartea',
 u'in': u'India',
 u'io': u'Ozeano Indikoko Lurralde Britaniarra',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'Islandia',
 u'it': u'Italia',
 u'je': u'Jersey',
 u'jm': u'Jamaika',
 u'jo': u'Jordania',
 u'jp': u'Japonia',
 u'ke': u'Kenya',
 u'kg': u'Kirgizistan',
 u'kh': u'Kanbodia',
 u'ki': u'Kiribati',
 u'km': u'Comoros',
 u'kn': u'Saint Kitts eta Nevis',
 u'kp': u'Ipar Korea',
 u'kr': u'Hego Korea',
 u'kw': u'Kuwait',
 u'ky': u'Kaiman Uharteak',
 u'kz': u'Kazakhstan',
 u'la': u'Laos',
 u'lb': u'Libano',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Lithuania',
 u'lu': u'Luxenburgo',
 u'lv': u'Latvia',
 u'ly': u'Libia',
 u'ma': u'Maroko',
 u'mc': u'Monako',
 u'md': u'Moldabiako errepublika',
 u'me': u'Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagascar',
 u'mh': u'Marshall Uharteak',
 u'mk': u'Macedoniako errepublia yugoslabiar federala',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongolia',
 u'mo': u'Makao',
 u'mp': u'Ipar Mariana Uharteak',
 u'mq': u'Martinika',
 u'mr': u'Mauritania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Maurizio',
 u'mv': u'Maldivak',
 u'mw': u'Malawi',
 u'mx': u'Mexiko',
 u'my': u'Malasia',
 u'mz': u'Mozambique',
 u'na': u'Namibia',
 u'nc': u'Kaledonia Berria',
 u'ne': u'Niger',
 u'nf': u'Norfolk Uharteak',
 u'ng': u'Nigeria',
 u'ni': u'Nikaragua',
 u'nl': u'Herbehereak',
 u'no': u'Norvegia',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Zelanda Berria',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Polinesia Frantziarra',
 u'pg': u'Papua Ginea Berria',
 u'ph': u'Filipinak',
 u'pk': u'Pakistan',
 u'pl': u'Polonia',
 u'pm': u'Saint-Pierre eta Mikelune',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Rico',
 u'ps': u'Palestina',
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguai',
 u'qa': u'Katar',
 u're': u'Reunion',
 u'ro': u'Errumania',
 u'rs': u'Serbia',
 u'ru': u'Russia',
 u'rw': u'Rwanda',
 u'sa': u'Saudi Arabia',
 u'sb': u'Salomon Uharteak',
 u'sc': u'Seychelles',
 u'sd': u'Sudan',
 u'se': u'Suedia',
 u'sg': u'Singapur',
 u'sh': u'Saint Helena',
 u'si': u'Eslovenia',
 u'sj': u'Svalbard eta Jan Mayen Uharteak',
 u'sk': u'Eslovakia',
 u'sl': u'Sierra Leona',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalia',
 u'sr': u'Surinam',
 u'st': u'Sao Tome eta Principe uharteak',
 u'sv': u'El Salvador',
 u'sy': u'Siria',
 u'sz': u'Swazilandia',
 u'tc': u'Turkiar eta Caicos Uharteak',
 u'td': u'Txad',
 u'tf': u'Hegoaldeko Frantziar Lurraldeak',
 u'tg': u'Togo',
 u'th': u'Thailandia',
 u'tj': u'Tajikistan',
 u'tk': u'Tokelau',
 u'tl': u'Ekialdeko Timor',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunez',
 u'to': u'Tonga',
 u'tr': u'Turkia',
 u'tt': u'Trinidad eta Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanzania',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'Estatu Batuetako Itsasoz Haraindiko Uharteak',
 u'us': u'Estatu Batuak',
 u'uy': u'Uruguai',
 u'uz': u'Uzbekistan',
 u'va': u'Vatikano Hiriko Estatua',
 u'vc': u'Saint Vincent eta Grenadinak',
 u've': u'Venezuela',
 u'vg': u'Erresuma Batuko Birjina Uharteak',
 u'vi': u'Estatu batuetako birjina uharteak',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis eta Futuna',
 u'ws': u'Samoa',
 u'ye': u'Yemen',
 u'yt': u'Mayotte',
 u'za': u'Hegoafrika',
 u'zm': u'Zambia',
 u'zw': u'Zimbawe'}