REGIONS = {u'ad': u'Andorre',
 u'ae': u'\xc9mirats arabes unis',
 u'af': u'Afghanistan',
 u'ag': u'Antigua-et-Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albanie',
 u'am': u'Arm\xe9nie',
 u'an': u'Antilles n\xe9erlandaises',
 u'ao': u'Angola',
 u'aq': u'Antarctique',
 u'ar': u'Argentine',
 u'as': u'Samoa am\xe9ricaines',
 u'at': u'Autriche',
 u'au': u'Australie',
 u'aw': u'Aruba',
 u'ax': u"\xc5land, \xeeles d'",
 u'az': u'Azerba\xefdjan',
 u'ba': u'Bosnie-Herz\xe9govine',
 u'bb': u'Barbade',
 u'bd': u'Bangladesh',
 u'be': u'Belgique',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgarie',
 u'bh': u'Bahre\xefn',
 u'bi': u'Burundi',
 u'bj': u'B\xe9nin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermudes',
 u'bn': u'Brun\xe9i Darussalam',
 u'bo': u'Bolivie',
 u'br': u'Br\xe9sil',
 u'bs': u'Bahamas',
 u'bt': u'Bhoutan',
 u'bv': u'Bouvet, \xeele',
 u'bw': u'Botswana',
 u'by': u'B\xe9larus',
 u'bz': u'Belize',
 u'ca': u'Canada',
 u'cc': u'Cocos (Keeling), \xeeles',
 u'cd': u'Congo-Kinshasa',
 u'cf': u'Centrafricaine, R\xe9publique',
 u'cg': u'Congo-Brazzaville',
 u'ch': u'Suisse',
 u'ci': u"C\xf4te d'Ivoire",
 u'ck': u'Cook, \xeeles',
 u'cl': u'Chili',
 u'cm': u'Cameroun',
 u'cn': u'Chine',
 u'co': u'Colombie',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Cap-Vert',
 u'cx': u'Christmas, \xeele',
 u'cy': u'Chypre',
 u'cz': u'Tch\xe8que, R\xe9publique',
 u'de': u'Allemagne',
 u'dj': u'Djibouti',
 u'dk': u'Danemark',
 u'dm': u'Dominique',
 u'do': u'Dominicaine, R\xe9publique',
 u'dz': u'Alg\xe9rie',
 u'ec': u'\xc9quateur',
 u'ee': u'Estonie',
 u'eg': u'\xc9gypte',
 u'eh': u'Sahara Occidental',
 u'er': u'\xc9rythr\xe9e',
 u'es': u'Espagne',
 u'et': u'\xc9thiopie',
 u'fi': u'Finlande',
 u'fj': u'Fidji',
 u'fk': u'Malouines, \xeeles',
 u'fm': u'Micron\xe9sie',
 u'fo': u'F\xe9ro\xe9, \xeeles',
 u'fr': u'France',
 u'ga': u'Gabon',
 u'gb': u'Royaume-Uni',
 u'gd': u'Grenade',
 u'ge': u'G\xe9orgie',
 u'gf': u'Guyane Fran\xe7aise',
 u'gg': u'Guernesey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Groenland',
 u'gm': u'Gambie',
 u'gn': u'Guin\xe9e',
 u'gp': u'Guadeloupe',
 u'gq': u'Guin\xe9e \xc9quatoriale',
 u'gr': u'Gr\xe8ce',
 u'gs': u'G\xe9orgie du Sud et les \xeeles Sandwich du Sud',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guin\xe9e-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong-Kong',
 u'hm': u'Heard, \xeeles et McDonald, \xeeles',
 u'hn': u'Honduras',
 u'hr': u'Croatie',
 u'ht': u'Ha\xefti',
 u'hu': u'Hongrie',
 u'id': u'Indon\xe9sie',
 u'ie': u'Irlande',
 u'il': u'Isra\xebl',
 u'im': u'Man, \xeele de',
 u'in': u'Inde',
 u'io': u"Oc\xe9an Indien, territoire britannique de l'\xeele de l'",
 u'iq': u'Iraq',
 u'ir': u'Iran',
 u'is': u'Islande',
 u'it': u'Italie',
 u'je': u'Jersey',
 u'jm': u'Jama\xefque',
 u'jo': u'Jordanie',
 u'jp': u'Japon',
 u'ke': u'Kenya',
 u'kg': u'Kirghizistan',
 u'kh': u'Cambodge',
 u'ki': u'Kiribati',
 u'km': u'Comores',
 u'kn': u'Saint-Kitts-et-Nevis',
 u'kp': u'Cor\xe9e du Nord',
 u'kr': u'Cor\xe9e du Sud',
 u'kw': u'Kowe\xeft',
 u'ky': u'Ca\xefmans, \xeeles',
 u'kz': u'Kazakhstan',
 u'la': u'Laos',
 u'lb': u'Liban',
 u'lc': u'Sainte-Lucie',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Lib\xe9ria',
 u'ls': u'Lesotho',
 u'lt': u'Lituanie',
 u'lu': u'Luxembourg',
 u'lv': u'Lettonie',
 u'ly': u'Libye',
 u'ma': u'Maroc',
 u'mc': u'Monaco',
 u'md': u'Moldavie',
 u'me': u'Mont\xe9n\xe9gro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagascar',
 u'mh': u'Marshall, \xeeles',
 u'mk': u'Mac\xe9doine',
 u'ml': u'Mali',
 u'mm': u'Birmanie',
 u'mn': u'Mongolie',
 u'mo': u'Macao',
 u'mp': u'Mariannes du Nord, \xeeles',
 u'mq': u'Martinique',
 u'mr': u'Mauritanie',
 u'ms': u'Montserrat',
 u'mt': u'Malte',
 u'mu': u'Maurice',
 u'mv': u'Maldives',
 u'mw': u'Malawi',
 u'mx': u'Mexique',
 u'my': u'Malaisie',
 u'mz': u'Mozambique',
 u'na': u'Namibie',
 u'nc': u'Nouvelle-Cal\xe9donie',
 u'ne': u'Niger',
 u'nf': u'Norfolk, \xeele',
 u'ng': u'Nig\xe9ria',
 u'ni': u'Nicaragua',
 u'nl': u'Pays-Bas',
 u'no': u'Norv\xe8ge',
 u'np': u'N\xe9pal',
 u'nr': u'Nauru',
 u'nu': u'Niu\xe9',
 u'nz': u'Nouvelle-Z\xe9lande',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'P\xe9rou',
 u'pf': u'Polyn\xe9sie fran\xe7aise',
 u'pg': u'Papouasie-Nouvelle-Guin\xe9e',
 u'ph': u'Philippines',
 u'pk': u'Pakistan',
 u'pl': u'Pologne',
 u'pm': u'Saint-Pierre-et-Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Porto Rico',
 u'ps': u'Palestinien Occup\xe9, territoire',
 u'pt': u'Portugal',
 u'pw': u'Palaos',
 u'py': u'Paraguay',
 u'qa': u'Qatar',
 u're': u'R\xe9union',
 u'ro': u'Roumanie',
 u'rs': u'Serbie',
 u'ru': u'Russie',
 u'rw': u'Rwanda',
 u'sa': u'Arabie Saoudite',
 u'sb': u'Salomon, \xeeles',
 u'sc': u'Seychelles',
 u'sd': u'Soudan',
 u'se': u'Su\xe8de',
 u'sg': u'Singapour',
 u'sh': u'Sainte-H\xe9l\xe8ne',
 u'si': u'Slov\xe9nie',
 u'sj': u'Svalbard et \xeele Jan Mayen',
 u'sk': u'Slovaquie',
 u'sl': u'Sierra Leone',
 u'sm': u'Saint-Marin',
 u'sn': u'S\xe9n\xe9gal',
 u'so': u'Somalie',
 u'sr': u'Suriname',
 u'st': u'Sao Tom\xe9-et-Principe',
 u'sv': u'El Salvador',
 u'sy': u'Syrie',
 u'sz': u'Swaziland',
 u'tc': u'Turques et Ca\xefques, \xeeles',
 u'td': u'Tchad',
 u'tf': u'Terres Australes Fran\xe7aises',
 u'tg': u'Togo',
 u'th': u'Tha\xeflande',
 u'tj': u'Tadjikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor-Leste',
 u'tm': u'Turkm\xe9nistan',
 u'tn': u'Tunisie',
 u'to': u'Tonga',
 u'tr': u'Turquie',
 u'tt': u'Trinit\xe9-et-Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Ta\xefwan',
 u'tz': u'Tanzanie',
 u'ua': u'Ukraine',
 u'ug': u'Ouganda',
 u'um': u'\xceles Mineures \xc9loign\xe9es des \xc9tats-Unis',
 u'us': u'\xc9tats-Unis',
 u'uy': u'Uruguay',
 u'uz': u'Ouzb\xe9kistan',
 u'va': u'Vatican',
 u'vc': u'Saint-Vincent-et-les-Grenadines',
 u've': u'Venezuela',
 u'vg': u'\xceles Vierges Britanniques',
 u'vi': u'\xceles Vierges Am\xe9ricaines',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis-et-Futuna',
 u'ws': u'Samoa',
 u'ye': u'Y\xe9men',
 u'yt': u'Mayotte',
 u'za': u'Afrique du Sud',
 u'zm': u'Zambie',
 u'zw': u'Zimbabwe'}