REGIONS = {u'ad': u'Andorra',
 u'ae': u'Na h-Iomaratan Arabach Aonaichte',
 u'af': u'Afghanast\xe0n',
 u'ag': u'Aint\xecoga is Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Alb\xe0inia',
 u'am': u'Airmeinia',
 u'an': u'Eileanan Aintilia nan T\xecrean \xccsle',
 u'ao': u'Ang\xf2la',
 u'aq': u'An Antartaig',
 u'ar': u'An Argantain',
 u'as': u'Samotha na h-Airmeireaga',
 u'at': u'An Ostair',
 u'au': u'Astr\xe0ilia',
 u'aw': u'Ar\xf9ba',
 u'ax': u'Na h-Eileanan \xc5land',
 u'az': u'Asarbaide\xe0n',
 u'ba': u'Bosna is Hearsagobhana',
 u'bb': u'Barbados',
 u'bd': u'Bangladais',
 u'be': u"A' Bheilg",
 u'bf': u'Buirciona Faso',
 u'bg': u"A' Bhulgair",
 u'bh': u'Bachrain',
 u'bi': u'Burundaidh',
 u'bj': u'Beinin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bearm\xf9da',
 u'bn': u'Br\xf9naigh D\xe0r as-Sal\xe0m',
 u'bo': u'Boilibhia',
 u'br': u'Braisil',
 u'bs': u'Na h-Eileanan Bathama',
 u'bt': u'But\xe0n',
 u'bv': u'Eilean Bouvet',
 u'bw': u'Botsuana',
 u'by': u"A' Bhealaruis",
 u'bz': u'Beil\xecs',
 u'ca': u'Canada',
 u'cc': u'Na h-Eileanan Cocos (Keeling)',
 u'cd': u'Congo-Kinshasa',
 u'cf': u'Poblachd Meadhan Afraga',
 u'cg': u'Congo-Brazzaville',
 u'ch': u'An Eilbheis',
 u'ci': u'An Costa \xccbhri',
 u'ck': u'Eileanan Cook',
 u'cl': u'An t-Sile',
 u'cm': u'Camarun',
 u'cn': u'An t-S\xecn',
 u'co': u'Coloimbia',
 u'cr': u'Costa R\xeccea',
 u'cu': u'C\xf9ba',
 u'cv': u'An Ceap Uaine',
 u'cx': u'Eilean na Nollaig',
 u'cy': u'C\xecopras',
 u'cz': u'Poblachd na Seice',
 u'de': u"A' Ghearmailt",
 u'dj': u'Diob\xf9taidh',
 u'dk': u'An Danmhairg',
 u'dm': u'Doiminicea',
 u'do': u"A' Phoblachd Dhoiminiceach",
 u'dz': u'Aildiria',
 u'ec': u'Eacuador',
 u'ee': u'An Eastoin',
 u'eg': u'An \xc8iphit',
 u'eh': u'Sathara an Iar',
 u'er': u'Sathara an Iar',
 u'es': u'An Sp\xe0inn',
 u'et': u'An Itiop',
 u'fi': u'An Fhionnlann',
 u'fj': u'F\xecdi',
 u'fk': u'Na h-Eileanan F\xe0clannach (Malvinas)',
 u'fm': u'Na Meanbh Eileanan',
 u'fo': u'Na h-Eileanan F\xe0ro',
 u'fr': u'Na h-Eileanan F\xe0ro',
 u'ga': u'Gabon',
 u'gb': u'An R\xecoghachd Aonaichte',
 u'gd': u'Grean\xe0da',
 u'ge': u"A' Chairtbheil",
 u'gf': u'Guidhe\xe0na na Frainge',
 u'gg': u'Ge\xe0rnsaidh',
 u'gh': u'G\xe0na',
 u'gi': u'Diobraltar',
 u'gl': u"A' Ghraonlann",
 u'gm': u"A' Ghaimbia",
 u'gn': u'Gini',
 u'gp': u'Guadalup',
 u'gq': u'Gini Mheadhan-chriosach',
 u'gr': u"A' Ghreug",
 u'gs': u'Se\xf2rsia a Deas is na h-Eileanan Sandwich a Deas',
 u'gt': u'Guatamala',
 u'gu': u'Guam',
 u'gw': u'Gini Bioso',
 u'gy': u'Guidhe\xe0na',
 u'hk': u'Hong Kong',
 u'hm': u'Eilean Heard is MhicDh\xf2mhnaill',
 u'hn': u'Hond\xf9ras',
 u'hr': u"A' Chr\xf2thais",
 u'ht': u'Haidhti',
 u'hu': u'An Ungair',
 u'id': u'Na h-Innd Innse',
 u'ie': u'\xc8irinn',
 u'il': u'Iosrael',
 u'im': u'Eilean Manainn',
 u'in': u'Na h-Innseachan',
 u'io': u'Raon Breatannach Cuan nan Innseachan',
 u'iq': u'Ior\xe0c',
 u'ir': u'Ior\xe0n',
 u'is': u'Innis T\xecle',
 u'it': u'An Eadailt',
 u'je': u'De\xe0rsaidh',
 u'jm': u'Diameuga',
 u'jo': u'I\xf2rdan',
 u'jp': u'An t-Seapan',
 u'ke': u'Ceinia',
 u'kg': u'C\xecorgastan',
 u'kh': u'Cambuidea',
 u'ki': u'Ciribeas',
 u'km': u'Comoros',
 u'kn': u'Naomh Cr\xecstean is Nibheis',
 u'kp': u'Coir\xe8a a Tuath',
 u'kr': u'Coir\xe8a a Deas',
 u'kw': u'Cuibh\xe8it',
 u'ky': u'Na h-Eileanan Caimean',
 u'kz': u'Casachst\xe0n',
 u'la': u'L\xe0thos',
 u'lb': u'Leabanon',
 u'lc': u'Naomh L\xf9isia',
 u'li': u'Lichtenstein',
 u'lk': u'Sri Lanca',
 u'lr': u'Lib\xe8ir',
 u'ls': u'Leasoto',
 u'lt': u'An Liotuain',
 u'lu': u'Lugsamburg',
 u'lv': u'An Laitbhe',
 u'ly': u'Libia',
 u'ma': u'Maroco',
 u'mc': u'Monaco',
 u'md': u"A' Mholdobha",
 u'me': u'Am Monadh Neagrach',
 u'mf': u'Naomh M\xe0rtainn',
 u'mg': u'Madagasgar',
 u'mh': u'Eileanan Mharshall',
 u'mk': u"A' Mhasadon",
 u'ml': u'M\xe0ili',
 u'mm': u'Mi\xe0nmar',
 u'mn': u'D\xf9thaich nam Mongol',
 u'mo': u'Mac\xe0thu',
 u'mp': u'Na h-Eileanan Mairianach a Tuath',
 u'mq': u'Mairtinic',
 u'mr': u'Moratain',
 u'ms': u'Montsarat',
 u'mt': u'Malta',
 u'mu': u'Na h-Eileanan Mhoiriseas',
 u'mv': u'Na h-Eileanan Maladaibh',
 u'mw': u'Malabhaidh',
 u'mx': u'Meagsago',
 u'my': u'Malaidhsia',
 u'mz': u'M\xf2saimbig',
 u'na': u'An Namaib',
 u'nc': u'Cailleann Nuadh',
 u'ne': u'N\xecgeir',
 u'nf': u'Eilean Norfolk',
 u'ng': u'Nig\xe8iria',
 u'ni': u'Niocaragua',
 u'nl': u'Na T\xecrean \xccsle',
 u'no': u'Na T\xecrean \xccsle',
 u'np': u'Neapal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Sealainn Nuadh',
 u'om': u'Om\xe0n',
 u'pa': u'Panama',
 u'pe': u'Pear\xf9',
 u'pf': u'Poilin\xe8is na Frainge',
 u'pg': u'Gini Nuadh Phaputhach',
 u'ph': u'Na h-Eileanan Filipineach',
 u'pk': u'Pagast\xe0n',
 u'pl': u"A' Ph\xf2lainn",
 u'pm': u'Saint Pierre is Miquelon',
 u'pn': u"Peit a' Ch\xe0irn",
 u'pr': u'Puerto Rico',
 u'ps': u'Ranntair Palastaineach fo fhoirghlacadh',
 u'pt': u"A' Phortagail",
 u'pw': u'Palau',
 u'py': u'Paraguaidh',
 u'qa': u'Catar',
 u're': u'R\xe9union',
 u'ro': u'Rom\xe0inia',
 u'rs': u'An t-S\xe8irb',
 u'ru': u'An Co-nasgadh Ruiseach',
 u'rw': u'Rubhanda',
 u'sa': u'Ar\xe0ibia nan Sabhd',
 u'sb': u'Eileanan Sholaimh',
 u'sc': u'Na h-Eileanan Sheiseall',
 u'sd': u'Sud\xe0n',
 u'se': u'An t-Suain',
 u'sg': u'Singeap\xf2r',
 u'sh': u'Eilean Naomh Eilidh',
 u'si': u'An t-Sl\xf2bhain',
 u'sj': u'Svalbard is Jan Mayen',
 u'sk': u'An t-Sl\xf2bhac',
 u'sl': u'Siarra Le\xf2mhann',
 u'sm': u'San Marino',
 u'sn': u'Seanagal',
 u'so': u'Som\xe0ilia',
 u'sr': u'Suranam',
 u'st': u'S\xe3o Tom\xe9 is Pr\xedncipe',
 u'sv': u'An Salbhador',
 u'sy': u'Siridhea',
 u'sz': u'D\xf9thaich nan Suasaidh',
 u'tc': u'Na h-Eileanan Turcach is Caiceo',
 u'td': u'An t-Se\xe0d',
 u'tf': u'Ranntairean a Deas na Frainge',
 u'tg': u'Togo',
 u'th': u'D\xf9thaiche nan T\xe0idh',
 u'tj': u'Taidigeast\xe0n',
 u'tk': u'Tokelau',
 u'tl': u'Timor an Ear',
 u'tm': u'Turcmanast\xe0n',
 u'tn': u'Tuinisea',
 u'to': u'Tonga',
 u'tr': u'An Tuirc',
 u'tt': u'Trianaid is Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taidh-Bh\xe0n',
 u'tz': u'An Tansan',
 u'ua': u'An Ucr\xe0in',
 u'ug': u'Uganda',
 u'um': u'Meanbh Eileanan Iomallach nan St\xe0itean Aonaichte',
 u'us': u'Na St\xe0itean Aonaichte',
 u'uy': u'Uruguaidh',
 u'uz': u'Usbagastan',
 u'va': u'Cathair na Bhatacain',
 u'vc': u'Naomh Bhionsant agus Eileanan Greanadach',
 u've': u"A' Bheiniseala",
 u'vg': u'Eileanan Breatannach na Maighdinn',
 u'vi': u'Eileanan Aimeireagach na Maighdinn',
 u'vn': u'Bhiet-Nam',
 u'vu': u'Vanuatu',
 u'wf': u'Uallas agus Futuna',
 u'ws': u'Samotha',
 u'ye': u'An Eaman',
 u'yt': u'Mayotte',
 u'za': u'Afraga a Deas',
 u'zm': u'S\xe0imbia',
 u'zw': u'An t-S\xecombab'}