REGIONS = {u'ad': u'Andorra',
 u'ae': u'Z.A.E.',
 u'af': u'Afganistan',
 u'ag': u'Antigua a Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albanska',
 u'am': u'Armenska',
 u'an': u'Ni\u017eozemske Antile',
 u'ao': u'Angola',
 u'aq': u'Antarktika',
 u'ar': u'Argentinska',
 u'as': u'Ameriska Samoa',
 u'at': u'Awstriska',
 u'au': u'Awstralska',
 u'aw': u'Aruba',
 u'ax': u'\xc5landske kupy',
 u'az': u'Azerbajd\u017aan',
 u'ba': u'Bosniska a Hercegowina',
 u'bb': u'Barbados',
 u'bd': u'Banglade\u0161',
 u'be': u'Belgiska',
 u'bf': u'Burkina Faso',
 u'bg': u'Bo\u0142harska',
 u'bh': u'Bahrajn',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermudy',
 u'bn': u'Brunei Darussalam',
 u'bo': u'Boliwiska',
 u'br': u'Brazilska',
 u'bs': u'Bahamy',
 u'bt': u'Bhutan',
 u'bv': u'Bouvetska kupa',
 u'bw': u'Botswana',
 u'by': u'B\u011b\u0142oruska',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Kokoske (Keeling) kupy',
 u'cd': u'Kongo-Kinshasa',
 u'cf': u'Centralnoafriska republika',
 u'cg': u'Kongo-Brazzaville',
 u'ch': u'\u0160wicarska',
 u'ci': u'S\u0142onowinowy pobrj\xf3h',
 u'ck': u'Cookowe kupy',
 u'cl': u'Chile',
 u'cm': u'Kamerun',
 u'cn': u'Chinska',
 u'co': u'Kolumbiska',
 u'cr': u'Kostarika',
 u'cu': u'Kuba',
 u'cv': u'Kapwerdiske kupy',
 u'cx': u'Hodowna kupa',
 u'cy': u'Cypern',
 u'cz': u'\u010c\u011bska republika',
 u'de': u'N\u011bmska',
 u'dj': u'D\u017aibuti',
 u'dk': u'Danska',
 u'dm': u'Dominika',
 u'do': u'Dominikanska Republika',
 u'dz': u'Algeriska',
 u'ec': u'Ekuador',
 u'ee': u'Estiska',
 u'eg': u'Egyptowska',
 u'eh': u'Zapadna Sahara',
 u'er': u'Eritreja',
 u'es': u'\u0160paniska',
 u'et': u'Etiopiska',
 u'fi': u'Finska',
 u'fj': u'Fid\u017ai',
 u'fk': u'Falklandske kupy (Malwiny)',
 u'fm': u'Mikroneziska',
 u'fo': u'Ferejske kupy',
 u'fr': u'Francoska',
 u'ga': u'Gabun',
 u'gb': u'Wulka Britaniska',
 u'gd': u'Grenada',
 u'ge': u'Georgiska',
 u'gf': u'Francoska Guyana',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Gr\xf6nlandska',
 u'gm': u'Gambija',
 u'gn': u'Gineja',
 u'gp': u'Guadeloupe',
 u'gq': u'Ekwatorialna Gineja',
 u'gr': u'Grjekska',
 u'gs': u'Ju\u017ena Georgiska a kupy South Sandwich',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Gineja-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Kupa Heard a kupy McDonald',
 u'hn': u'Honduras',
 u'hr': u'Chorwatska',
 u'ht': u'Haiti',
 u'hu': u'Mad\u017aarska',
 u'id': u'Indoneska',
 u'ie': u'Irska',
 u'il': u'Israel',
 u'im': u'Isle of Man',
 u'in': u'Indiska',
 u'io': u'Britiski indisko-oceanski teritorij',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'Islandska',
 u'it': u'Italska',
 u'je': u'Jersey',
 u'jm': u'Jamaika',
 u'jo': u'Jordanska',
 u'jp': u'Japanska',
 u'ke': u'Kenija',
 u'kg': u'Kirgiska',
 u'kh': u'Kambod\u017aa',
 u'ki': u'Kiribati',
 u'km': u'Komory',
 u'kn': u'Saint Kitts a Nevis',
 u'kp': u'Sewjerna Koreja',
 u'kr': u'Ju\u017ena Koreja',
 u'kw': u'Kuwait',
 u'ky': u'Kajmanske kupy',
 u'kz': u'Kazachska',
 u'la': u'Laos',
 u'lb': u'Libanon',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberija',
 u'ls': u'Lesotho',
 u'lt': u'Litawska',
 u'lu': u'Luksemburgska',
 u'lv': u'Letiska',
 u'ly': u'Libyska',
 u'ma': u'Marokko',
 u'mc': u'Monako',
 u'md': u'Moldawska',
 u'me': u'\u010corna Hora',
 u'mf': u'Saint Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Mar\u0161alske kupy',
 u'mk': u'N.J.R. Makedonska',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongolska',
 u'mo': u'Makao',
 u'mp': u'Sewjerne Marianske kupy',
 u'mq': u'Martinique',
 u'mr': u'Mawretanska',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Malediwy',
 u'mw': u'Malawi',
 u'mx': u'Meksiko',
 u'my': u'Malajzija',
 u'mz': u'Mosambik',
 u'na': u'Namibija',
 u'nc': u'Nowa Kaledonija',
 u'ne': u'Niger',
 u'nf': u'Kupa Norfolk',
 u'ng': u'Nigerija',
 u'ni': u'Nikaragua',
 u'nl': u'Ni\u017eozemska',
 u'no': u'Norwegska',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nowoseelandska',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Francoska Polyneziska',
 u'pg': u'Papua-Nowa Gineja',
 u'ph': u'Filipiny',
 u'pk': u'Pakistan',
 u'pl': u'P\xf3lska',
 u'pm': u'Saint Pierre a Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Riko',
 u'ps': u'Wobsad\u017aeny palestinski teritorij',
 u'pt': u'Portugalska',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Katar',
 u're': u'Reunion',
 u'ro': u'Rumunska',
 u'rs': u'Serbiska',
 u'ru': u'Ruska federacija',
 u'rw': u'Ruanda',
 u'sa': u'Saudi-Arabska',
 u'sb': u'Solomonske kupy',
 u'sc': u'Seychelle',
 u'sd': u'Sudan',
 u'se': u'\u0160wedska',
 u'sg': u'Singapur',
 u'sh': u'Saint Helena',
 u'si': u'S\u0142owjenska',
 u'sj': u'Svalbard a Jan Mayen',
 u'sk': u'S\u0142owakska',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalija',
 u'sr': u'Surinam',
 u'st': u'Sao Tome a Principe',
 u'sv': u'El Salvador',
 u'sy': u'Syriska',
 u'sz': u'Swaziska',
 u'tc': u'Kupy Turks a Caicos',
 u'td': u'\u010cad',
 u'tf': u'Francoske ju\u017ene teritorije',
 u'tg': u'Togo',
 u'th': u'Thailandska',
 u'tj': u'Tad\u017aikistan',
 u'tk': u'Tokelau',
 u'tl': u'Wuchodny Timor',
 u'tm': u'Turkmeniska',
 u'tn': u'Tuneziska',
 u'to': u'Tonga',
 u'tr': u'Turkowska',
 u'tt': u'Trinidad a Tobago',
 u'tv': u'Tuwalu',
 u'tw': u'Taiwan',
 u'tz': u'Tansanija',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'Zwonkowne kupy Zjedno\u0107enych statow',
 u'us': u'Zjedno\u0107ene staty',
 u'uy': u'Uruguay',
 u'uz': u'Uzbekistan',
 u'va': u'Vatikanske m\u011bsto',
 u'vc': u'Saint Vincent a Grenadiny',
 u've': u'Venezuela',
 u'vg': u'Britiske knje\u017eniske kupy',
 u'vi': u'Ameriske knje\u017eniske kupy',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis a Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jemen',
 u'yt': u'Mayotte',
 u'za': u'Ju\u017ena Afrika',
 u'zm': u'Sambija',
 u'zw': u'Simbabwe'}