REGIONS = {u'ad': u'Andorra',
 u'ae': u'Emirati Arabi Uniti',
 u'af': u'Afghanistan',
 u'ag': u'Antigua e Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albania',
 u'am': u'Armenia',
 u'an': u'Antille Olandesi',
 u'ao': u'Angola',
 u'aq': u'Antartide',
 u'ar': u'Argentina',
 u'as': u'Samoa Americana',
 u'at': u'Austria',
 u'au': u'Australia',
 u'aw': u'Aruba',
 u'ax': u'Isole \xc5land',
 u'az': u'Azerbaijan',
 u'ba': u'Bosnia Herzegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesh',
 u'be': u'Belgio',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgaria',
 u'bh': u'Bahrein',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei Darussalam',
 u'bo': u'Bolivia',
 u'br': u'Brasile',
 u'bs': u'Bahamas',
 u'bt': u'Bhutan',
 u'bv': u'Isola Bouvet',
 u'bw': u'Botswana',
 u'by': u'Bielorussia',
 u'bz': u'Belize',
 u'ca': u'Canada',
 u'cc': u'Isole Cocos (Keeling)',
 u'cd': u'Congo-Kinshasa',
 u'cf': u"Repubblica dell'Africa Centrale",
 u'cg': u'Congo-Brazzaville',
 u'ch': u'Svizzera',
 u'ci': u"Costa d'Avorio",
 u'ck': u'Isole Cook',
 u'cl': u'Cile',
 u'cm': u'Camerun',
 u'cn': u'Cina',
 u'co': u'Colombia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Capo Verde',
 u'cx': u'Isola di Natale',
 u'cy': u'Cipro',
 u'cz': u'Repubblica Ceca',
 u'de': u'Germania',
 u'dj': u'Gibuti',
 u'dk': u'Danimarca',
 u'dm': u'Dominica',
 u'do': u'Repubblica Dominicana',
 u'dz': u'Algeria',
 u'ec': u'Ecuador',
 u'ee': u'Estonia',
 u'eg': u'Egitto',
 u'eh': u'Sahara Occidentale',
 u'er': u'Eritrea',
 u'es': u'Spagna',
 u'et': u'Etiopia',
 u'fi': u'Finlandia',
 u'fj': u'Fiji',
 u'fk': u'Isole Falkland (Malvinas)',
 u'fm': u'Micronesia',
 u'fo': u'Isole Faroe',
 u'fr': u'Francia',
 u'ga': u'Gabon',
 u'gb': u'Regno Unito',
 u'gd': u'Grenada',
 u'ge': u'Georgia',
 u'gf': u'Guiana Francese',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibilterra',
 u'gl': u'Groenlandia',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadalupe',
 u'gq': u'Guinea Equatoriale',
 u'gr': u'Grecia',
 u'gs': u'Georgia del Sud e isole Sandwich meridionali',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Isola Heard e isole McDonald',
 u'hn': u'Honduras',
 u'hr': u'Croazia',
 u'ht': u'Haiti',
 u'hu': u'Ungheria',
 u'id': u'Indonesia',
 u'ie': u'Irlanda',
 u'il': u'Israele',
 u'im': u'Isola di Man',
 u'in': u'India',
 u'io': u"Territorio Britannico dell'Oceano Indiano",
 u'iq': u'Iraq',
 u'ir': u'Iran',
 u'is': u'Islanda',
 u'it': u'Italia',
 u'je': u'Jersey',
 u'jm': u'Giamaica',
 u'jo': u'Giordania',
 u'jp': u'Giappone',
 u'ke': u'Kenya',
 u'kg': u'Kyrgyzstan',
 u'kh': u'Cambogia',
 u'ki': u'Kiribati',
 u'km': u'Comore',
 u'kn': u'Saint Kitts and Nevis',
 u'kp': u'Nord Corea',
 u'kr': u'Sud Corea',
 u'kw': u'Kuwait',
 u'ky': u'Isole Cayman',
 u'kz': u'Kazakistan',
 u'la': u'Laos',
 u'lb': u'Libano',
 u'lc': u'Santa Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Lituania',
 u'lu': u'Lussemburgo',
 u'lv': u'Lettonia',
 u'ly': u'Libia',
 u'ma': u'Marocco',
 u'mc': u'Monaco',
 u'md': u'Moldavia',
 u'me': u'Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagascar',
 u'mh': u'Isole Marshall',
 u'mk': u'Macedonia, prec. R.Y. di',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongolia',
 u'mo': u'Macao',
 u'mp': u'Isole Marianne Settentrionali',
 u'mq': u'Martinica',
 u'mr': u'Mauritania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Maldive',
 u'mw': u'Malawi',
 u'mx': u'Messico',
 u'my': u'Malesia',
 u'mz': u'Mozambique',
 u'na': u'Namibia',
 u'nc': u'Nuova Caledonia',
 u'ne': u'Niger',
 u'nf': u'Isola Norfolk',
 u'ng': u'Nigeria',
 u'ni': u'Nicaragua',
 u'nl': u'Olanda',
 u'no': u'Norvegia',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nuova Zelanda',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Per\xf9',
 u'pf': u'Polinesia Francese',
 u'pg': u'Papua Nuova Guinea',
 u'ph': u'Filippine',
 u'pk': u'Pakistan',
 u'pl': u'Polonia',
 u'pm': u'Saint Pierre e Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Porto Rico',
 u'ps': u'Territori Palestinesi Occupati',
 u'pt': u'Portogallo',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Qatar',
 u're': u'Reunion',
 u'ro': u'Romania',
 u'rs': u'Serbia',
 u'ru': u'Federazione Russa',
 u'rw': u'Ruanda',
 u'sa': u'Arabia Saudita',
 u'sb': u'Isole Salomone',
 u'sc': u'Seychelles',
 u'sd': u'Sudan',
 u'se': u'Svezia',
 u'sg': u'Singapore',
 u'sh': u"Sant'Elena",
 u'si': u'Slovenia',
 u'sj': u'Svalbard e Jan Mayen',
 u'sk': u'Slovacchia',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalia',
 u'sr': u'Suriname',
 u'st': u'Sao Tome e Principe',
 u'sv': u'El Salvador',
 u'sy': u'Siria',
 u'sz': u'Swaziland',
 u'tc': u'Isole Turks e Caicos',
 u'td': u'Ciad',
 u'tf': u'Territori Francesi Meridionali',
 u'tg': u'Togo',
 u'th': u'Tailandia',
 u'tj': u'Tagikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor Est',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunisia',
 u'to': u'Tonga',
 u'tr': u'Turchia',
 u'tt': u'Trinidad e Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanzania',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'Isole minori esterne degli Stati Uniti',
 u'us': u'Stati Uniti',
 u'uy': u'Uruguay',
 u'uz': u'Uzbekistan',
 u'va': u'Citt\xe0 del Vaticano',
 u'vc': u'San Vincenzo e Grenadine',
 u've': u'Venezuela',
 u'vg': u'Isole Vergini Britanniche',
 u'vi': u'Isole Vergini Statunitensi',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis e Futuna',
 u'ws': u'Samoa',
 u'ye': u'Yemen',
 u'yt': u'Mayotte',
 u'za': u'Sud Africa',
 u'zm': u'Zambia',
 u'zw': u'Zimbabwe'}