REGIONS = {u'ad': u'Andora',
 u'ae': u'Apvienotie Ar\u0101bu Emir\u0101ti',
 u'af': u'Afganist\u0101na',
 u'ag': u'Antigva un Barbuda',
 u'ai': u'Angi\u013ca',
 u'al': u'Alb\u0101nija',
 u'am': u'Arm\u0113nija',
 u'an': u'N\u012bderlandes Anti\u013cas',
 u'ao': u'Angola',
 u'aq': u'Antarktika',
 u'ar': u'Argent\u012bna',
 u'as': u'Amerikas Samoa',
 u'at': u'Austrija',
 u'au': u'Austr\u0101lija',
 u'aw': u'Aruba',
 u'ax': u'\u0100landu salas',
 u'az': u'Azerbaid\u017e\u0101na',
 u'ba': u'Bosnija un Hercogovina',
 u'bb': u'Barbadosa',
 u'bd': u'Banglade\u0161a',
 u'be': u'Be\u013c\u0123ija',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulg\u0101rija',
 u'bh': u'Bahreina',
 u'bi': u'Burundija',
 u'bj': u'Benina',
 u'bl': u'Seint Bartelemeja',
 u'bm': u'Bermudas',
 u'bn': u'Bruneja Darusalama',
 u'bo': u'Bol\u012bvija',
 u'br': u'Braz\u012blija',
 u'bs': u'Bahamas',
 u'bt': u'But\u0101na',
 u'bv': u'Buvetu Sala',
 u'bw': u'Botsv\u0101na',
 u'by': u'Baltkrievija',
 u'bz': u'Beliza',
 u'ca': u'Kan\u0101da',
 u'cc': u'Kokosu salas',
 u'cd': u'Kongo-Kin\u0161asa',
 u'cf': u'Centr\u0101l\u0101frikas republika',
 u'cg': u'Kongo-Brazivilla',
 u'ch': u'\u0160veice',
 u'ci': u'Zilo\u0146kaula Krasts',
 u'ck': u'Kuka Salas',
 u'cl': u'\u010c\u012ble',
 u'cm': u'Kamer\u016bna',
 u'cn': u'\u0136\u012bna',
 u'co': u'Kolumbija',
 u'cr': u'Kosta Rika',
 u'cu': u'Kuba',
 u'cv': u'Kabaverde',
 u'cx': u'Ziemassv\u0113tku sala',
 u'cy': u'Kipra',
 u'cz': u'\u010cehijas republika',
 u'de': u'V\u0101cija',
 u'dj': u'D\u017eibutija',
 u'dk': u'D\u0101nija',
 u'dm': u'Dominika',
 u'do': u'Dominika\u0146u Republika',
 u'dz': u'Al\u017e\u012bra',
 u'ec': u'Ekvadora',
 u'ee': u'Igaunija',
 u'eg': u'\u0112\u0123ipte',
 u'eh': u'Rietumsah\u0101ra',
 u'er': u'Eritreja',
 u'es': u'Sp\u0101nija',
 u'et': u'Etiopija',
 u'fi': u'Somija',
 u'fj': u'Fid\u017ei',
 u'fk': u'Folklendu salas',
 u'fm': u'Mikron\u0113zija',
 u'fo': u'F\u0113ru salas',
 u'fr': u'Francija',
 u'ga': u'Gabona',
 u'gb': u'Apvienot\u0101 Karaliste',
 u'gd': u'Gren\u0101da',
 u'ge': u'Gruzija',
 u'gf': u'Fran\u010du Gvi\u0101na',
 u'gg': u'Guernsey',
 u'gh': u'Gana',
 u'gi': u'Gibralt\u0101rs',
 u'gl': u'Grenlande',
 u'gm': u'Gambija',
 u'gn': u'Gvineja',
 u'gp': u'Gvandelupa',
 u'gq': u'Ekvatori\u0101l\u0101 Gvineja',
 u'gr': u'Grie\u0137ija',
 u'gs': u'Dienvidgruzija un Dienvidu Sendvi\u010du salas',
 u'gt': u'Gvatemala',
 u'gu': u'Guama',
 u'gw': u'Gvineja-Bisava',
 u'gy': u'Gajana',
 u'hk': u'Honkonga',
 u'hm': u'Heada sala un McDonalda salas',
 u'hn': u'Hondurasa',
 u'hr': u'Horv\u0101tija',
 u'ht': u'Haiti',
 u'hu': u'Ung\u0101rija',
 u'id': u'Indon\u0113zija',
 u'ie': u'\u012arija',
 u'il': u'Izra\u0113la',
 u'im': u'Mana sala',
 u'in': u'Indija',
 u'io': u'Britu Indijas oke\u0101na teritorija',
 u'iq': u'Ir\u0101ka',
 u'ir': u'Ir\u0101na',
 u'is': u'Islande',
 u'it': u'It\u0101lija',
 u'je': u'D\u017eersija',
 u'jm': u'Jamaika',
 u'jo': u'Jord\u0101na',
 u'jp': u'Jap\u0101na',
 u'ke': u'Kenija',
 u'kg': u'Kirgizst\u0101na',
 u'kh': u'Kambod\u017ea',
 u'ki': u'Kiribati',
 u'km': u'Komori',
 u'kn': u'Sv. Kitts un Nevis',
 u'kp': u'Zieme\u013ckoreja',
 u'kr': u'Dienvidkoreja',
 u'kw': u'Kuveita',
 u'ky': u'Kaimanu salas',
 u'kz': u'Kazahst\u0101na',
 u'la': u'Laosa',
 u'lb': u'Lib\u0101na',
 u'lc': u'Sv. L\u016bcija',
 u'li': u'Lihten\u0161teina',
 u'lk': u'\u0160rilanka',
 u'lr': u'Lib\u0113rija',
 u'ls': u'Lesoto',
 u'lt': u'Lietuva',
 u'lu': u'Luksemburga',
 u'lv': u'Latvija',
 u'ly': u'L\u012bbija',
 u'ma': u'Maroka',
 u'mc': u'Monako',
 u'md': u'Mold\u0101vija',
 u'me': u'Montenegro',
 u'mf': u'Seint Martina',
 u'mg': u'Madagaskara',
 u'mh': u'M\u0101r\u0161alu salas',
 u'mk': u'Ma\u0137edonija',
 u'ml': u'Mali',
 u'mm': u'Mjanmara',
 u'mn': u'Mongolija',
 u'mo': u'Makao',
 u'mp': u'Zieme\u013cmari\u0101nas salas',
 u'mq': u'Martinika',
 u'mr': u'Maurit\u0101nija',
 u'ms': u'Monserata',
 u'mt': u'Malta',
 u'mu': u'Maur\u012bcija',
 u'mv': u'Maldv\u012bnes',
 u'mw': u'Malavi',
 u'mx': u'Meksika',
 u'my': u'Malaizija',
 u'mz': u'Mozambika',
 u'na': u'Nam\u012bbija',
 u'nc': u'Jaunkaledonija',
 u'ne': u'Nig\u0113ra',
 u'nf': u'Norfolkas sala',
 u'ng': u'Nig\u0113rija',
 u'ni': u'Nikaragva',
 u'nl': u'N\u012bderlande',
 u'no': u'Norv\u0113\u0123ija',
 u'np': u'Nep\u0101la',
 u'nr': u'Nauri',
 u'nu': u'Niue',
 u'nz': u'Jaunz\u0113lande',
 u'om': u'Om\u0101na',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Fran\u010du Polin\u0113zija',
 u'pg': u'Papua Jaungvineja',
 u'ph': u'Filip\u012bnas',
 u'pk': u'Pakist\u0101na',
 u'pl': u'Polija',
 u'pm': u'Senpj\u0113ra un Mikelona',
 u'pn': u'Pitk\u0113rna',
 u'pr': u'Puertoriko',
 u'ps': u'Okup\u0113t\u0101 Palest\u012bnas teritorija',
 u'pt': u'Portug\u0101le',
 u'pw': u'Palau',
 u'py': u'Paragvaja',
 u'qa': u'Katara',
 u're': u'Reunjona',
 u'ro': u'Rum\u0101nija',
 u'rs': u'Serbija',
 u'ru': u'Krievijas feder\u0101cija',
 u'rw': u'Ruanda',
 u'sa': u'Sa\u016bdu Ar\u0101bija',
 u'sb': u'Solomonu salas',
 u'sc': u'\u0160ei\u0161e\u013ci',
 u'sd': u'Sud\u0101na',
 u'se': u'Zviedrija',
 u'sg': u'Singap\u016bra',
 u'sh': u'Sv. Hel\u0113nas sala',
 u'si': u'Slov\u0113nija',
 u'sj': u'Svalb\u0101ra un Jan Maj\u0113na',
 u'sk': u'Slov\u0101kija',
 u'sl': u'Sjerra Leone',
 u'sm': u'Sanmar\u012bno',
 u'sn': u'Seneg\u0101la',
 u'so': u'Som\u0101lija',
 u'sr': u'Surinama',
 u'st': u'Santome un Prinsipi',
 u'sv': u'Salvadora',
 u'sy': u'S\u012brija',
 u'sz': u'Svazilenda',
 u'tc': u'T\u0113rksa un Kaikosa salas',
 u'td': u'\u010cada',
 u'tf': u'Fran\u010du dienvidu teritorijas',
 u'tg': u'Togo',
 u'th': u'Taizeme',
 u'tj': u'Tad\u017eikist\u0101na',
 u'tk': u'Tokelau',
 u'tl': u'Timor-Leste',
 u'tm': u'Turkmenist\u0101na',
 u'tn': u'Tunisija',
 u'to': u'Tonga',
 u'tr': u'Turcija',
 u'tt': u'Trinidada un Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiv\u0101na',
 u'tz': u'Tanz\u0101nija',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'Savienoto Valstu maz\u0101s \u0101r\u0113j\u0101s salas',
 u'us': u'Savienot\u0101s Valstis',
 u'uy': u'Urugvaja',
 u'uz': u'Uzbekist\u0101na',
 u'va': u'Vatik\u0101ns',
 u'vc': u'Sv. Vincenta un Grenad\u012bnes',
 u've': u'Venecu\u0113la',
 u'vg': u'Britu Vird\u017einu salas',
 u'vi': u'ASV Vird\u017einu salas',
 u'vn': u'Vjetnama',
 u'vu': u'Vanuatu',
 u'wf': u'Volisa salas un Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jemena',
 u'yt': u'Majota',
 u'za': u'Dienvid\u0101frikas Republika',
 u'zm': u'Zambija',
 u'zw': u'Zimbabve'}