REGIONS = {u'ad': u'Andorra',
 u'ae': u'Verenigde Arabische Emiraten',
 u'af': u'Afghanistan',
 u'ag': u'Antigua en Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albani\xeb',
 u'am': u'Armeni\xeb',
 u'an': u'Nederlandse Antillen',
 u'ao': u'Angola',
 u'aq': u'Antarctica',
 u'ar': u'Argentini\xeb',
 u'as': u'Amerikaans-Samoa',
 u'at': u'Oostenrijk',
 u'au': u'Australi\xeb',
 u'aw': u'Aruba',
 u'ax': u'\xc5landseilanden',
 u'az': u'Azerbeidzjan',
 u'ba': u'Bosni\xeb en Herzegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesh',
 u'be': u'Belgi\xeb',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgarije',
 u'bh': u'Bahrein',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Sint-Bartholomeus',
 u'bm': u'Bermuda',
 u'bn': u'Brunei',
 u'bo': u'Bolivia',
 u'br': u'Brazili\xeb',
 u'bs': u'Bahama\u2019s',
 u'bt': u'Bhutan',
 u'bv': u'Bouvet',
 u'bw': u'Botswana',
 u'by': u'Wit-Rusland',
 u'bz': u'Belize',
 u'ca': u'Canada',
 u'cc': u'Cocoseilanden',
 u'cd': u'Congo-Kinshasa',
 u'cf': u'Centraal-Afrikaanse Republiek',
 u'cg': u'Congo-Brazzaville',
 u'ch': u'Zwitserland',
 u'ci': u'Ivoorkust',
 u'ck': u'Cookeilanden',
 u'cl': u'Chili',
 u'cm': u'Kameroen',
 u'cn': u'China',
 u'co': u'Colombia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Kaapverdi\xeb',
 u'cx': u'Christmaseiland',
 u'cy': u'Cyprus',
 u'cz': u'Tsjechi\xeb',
 u'de': u'Duitsland',
 u'dj': u'Djibouti',
 u'dk': u'Denemarken',
 u'dm': u'Dominica',
 u'do': u'Dominicaanse Republiek',
 u'dz': u'Algerije',
 u'ec': u'Ecuador',
 u'ee': u'Estland',
 u'eg': u'Egypte',
 u'eh': u'Westelijke Sahara',
 u'er': u'Eritrea',
 u'es': u'Spanje',
 u'et': u'Ethiopi\xeb',
 u'fi': u'Finland',
 u'fj': u'Fiji',
 u'fk': u'Falklandeilanden',
 u'fm': u'Micronesia',
 u'fo': u'Faer\xf6er',
 u'fr': u'Frankrijk',
 u'ga': u'Gabon',
 u'gb': u'Verenigd Koninkrijk',
 u'gd': u'Grenada',
 u'ge': u'Georgi\xeb',
 u'gf': u'Frans-Guyana',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Groenland',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'Equatoriaal-Guinea',
 u'gr': u'Griekenland',
 u'gs': u'Zuid-Georgi\xeb en de Zuidelijke Sandwicheilanden',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinee-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hongkong',
 u'hm': u'Heard en McDonaldeilanden',
 u'hn': u'Honduras',
 u'hr': u'Kroati\xeb',
 u'ht': u'Haiti',
 u'hu': u'Hongarije',
 u'id': u'Indonesi\xeb',
 u'ie': u'Ierland',
 u'il': u'Isra\xebl',
 u'im': u'Man',
 u'in': u'India',
 u'io': u'Brits Territorium in de Indische Oceaan',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'IJsland',
 u'it': u'Itali\xeb',
 u'je': u'Jersey',
 u'jm': u'Jamaica',
 u'jo': u'Jordani\xeb',
 u'jp': u'Japan',
 u'ke': u'Kenia',
 u'kg': u'Kirgizi\xeb',
 u'kh': u'Cambodja',
 u'ki': u'Kiribati',
 u'km': u'Comoren',
 u'kn': u'Saint Kitts en Nevis',
 u'kp': u'Noord-Korea',
 u'kr': u'Zuid-Korea',
 u'kw': u'Koeweit',
 u'ky': u'Caymaneilanden',
 u'kz': u'Kazachstan',
 u'la': u'Laos',
 u'lb': u'Libanon',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Litouwen',
 u'lu': u'Luxemburg',
 u'lv': u'Letland',
 u'ly': u'Libi\xeb',
 u'ma': u'Marokko',
 u'mc': u'Monaco',
 u'md': u'Moldavi\xeb',
 u'me': u'Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagascar',
 u'mh': u'Marshalleilanden',
 u'mk': u'Macedoni\xeb',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mongoli\xeb',
 u'mo': u'Macau',
 u'mp': u'Noordelijke Marianen',
 u'mq': u'Martinique',
 u'mr': u'Mauritania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritani\xeb',
 u'mv': u'Maldiven',
 u'mw': u'Malawi',
 u'mx': u'Mexico',
 u'my': u'Maleisi\xeb',
 u'mz': u'Mozambique',
 u'na': u'Namibi\xeb',
 u'nc': u'Nieuw-Caledoni\xeb',
 u'ne': u'Niger',
 u'nf': u'Norfolk',
 u'ng': u'Nigeria',
 u'ni': u'Nicaragua',
 u'nl': u'Nederland',
 u'no': u'Noorwegen',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nieuw-Zeeland',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Frans Polynesi\xeb',
 u'pg': u'Papoea-Nieuw-Guinea',
 u'ph': u'Filippijnen',
 u'pk': u'Pakistan',
 u'pl': u'Polen',
 u'pm': u'Saint-Pierre en Miquelon',
 u'pn': u'Pitcairneilanden',
 u'pr': u'Puerto Rico',
 u'ps': u'Palestijnse Gebieden',
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Qatar',
 u're': u'R\xe9union',
 u'ro': u'Roemeni\xeb',
 u'rs': u'Servi\xeb',
 u'ru': u'Rusland',
 u'rw': u'Rwanda',
 u'sa': u'Saoedi-Arabi\xeb',
 u'sb': u'Salomonseilanden',
 u'sc': u'Seychellen',
 u'sd': u'Soedan',
 u'se': u'Zweden',
 u'sg': u'Singapore',
 u'sh': u'Sint-Helena',
 u'si': u'Sloveni\xeb',
 u'sj': u'Spitsbergen en Jan Mayen-eilanden',
 u'sk': u'Slovakije',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somali\xeb',
 u'sr': u'Suriname',
 u'st': u'Sao Tome en Principe',
 u'sv': u'El Salvador',
 u'sy': u'Syri\xeb',
 u'sz': u'Swaziland',
 u'tc': u'Turks- en Caicoseilanden',
 u'td': u'Tsjaad',
 u'tf': u'Franse Zuidelijke en Antarctische Gebieden',
 u'tg': u'Togo',
 u'th': u'Thailand',
 u'tj': u'Tadzjikistan',
 u'tk': u'Tokelau-eilanden',
 u'tl': u'Oost-Timor',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunesi\xeb',
 u'to': u'Tonga',
 u'tr': u'Turkije',
 u'tt': u'Trinidad en Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanzania',
 u'ua': u'Oekra\xefne',
 u'ug': u'Oeganda',
 u'um': u'Kleine afgelegen eilanden van de Verenigde Staten',
 u'us': u'Verenigde Staten',
 u'uy': u'Uruguay',
 u'uz': u'Oezbekistan',
 u'va': u'Vaticaanstad',
 u'vc': u'Saint Vincent en de Grenadines',
 u've': u'Venezuela',
 u'vg': u'Britse Maagdeneilanden',
 u'vi': u'Amerikaanse Maagdeneilanden',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis en Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jemen',
 u'yt': u'Mayotte',
 u'za': u'Zuid-Afrika',
 u'zm': u'Zambia',
 u'zw': u'Zimbabwe'}