REGIONS = {u'ad': u'Andora',
 u'ae': u'Zjednoczone Emiraty Arabskie',
 u'af': u'Afganistan',
 u'ag': u'Antigua i Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albania',
 u'am': u'Armenia',
 u'an': u'Antyle Holenderskie',
 u'ao': u'Angola',
 u'aq': u'Antarktyda',
 u'ar': u'Argentyna',
 u'as': u'Samoa Ameryka\u0144skie',
 u'at': u'Austria',
 u'au': u'Australia',
 u'aw': u'Aruba',
 u'ax': u'Wyspy Alandzkie',
 u'az': u'Azerbejd\u017can',
 u'ba': u'Bo\u015bnia i Hercegowina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesz',
 u'be': u'Belgia',
 u'bf': u'Burkina Faso',
 u'bg': u'Bu\u0142garia',
 u'bh': u'Bahrajn',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint-Barth\xe9lemy',
 u'bm': u'Bermudy',
 u'bn': u'Brunei',
 u'bo': u'Boliwia',
 u'br': u'Brazylia',
 u'bs': u'Bahamy',
 u'bt': u'Bhutan',
 u'bv': u'Wyspa Bouveta',
 u'bw': u'Botswana',
 u'by': u'Bia\u0142oru\u015b',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Wyspy Kokosowe',
 u'cd': u'Kongo-Kinszasa',
 u'cf': u'Republika \u015arodkowoafryka\u0144ska',
 u'cg': u'Kongo-Brazzaville',
 u'ch': u'Szwajcaria',
 u'ci': u'Wybrze\u017ce Ko\u015bci S\u0142oniowej',
 u'ck': u'Wyspy Cooka',
 u'cl': u'Chile',
 u'cm': u'Kamerun',
 u'cn': u'Chiny',
 u'co': u'Kolumbia',
 u'cr': u'Kostaryka',
 u'cu': u'Kuba',
 u'cv': u'Wyspy Zielonego Przyl\u0105dka',
 u'cx': u'Wyspa Bo\u017cego Narodzenia',
 u'cy': u'Cypr',
 u'cz': u'Czechy',
 u'de': u'Niemcy',
 u'dj': u'D\u017cibuti',
 u'dk': u'Dania',
 u'dm': u'Dominika',
 u'do': u'Dominikana',
 u'dz': u'Algieria',
 u'ec': u'Ekwador',
 u'ee': u'Estonia',
 u'eg': u'Egipt',
 u'eh': u'Sahara Zachodnia',
 u'er': u'Erytrea',
 u'es': u'Hiszpania',
 u'et': u'Etiopia',
 u'fi': u'Finlandia',
 u'fj': u'Fid\u017ci',
 u'fk': u'Falklandy (Malwiny)',
 u'fm': u'Mikronezja',
 u'fo': u'Wyspy Owcze',
 u'fr': u'Francja',
 u'ga': u'Gabon',
 u'gb': u'Wielka Brytania',
 u'gd': u'Grenada',
 u'ge': u'Gruzja',
 u'gf': u'Gujana Francuska',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Grenlandia',
 u'gm': u'Gambia',
 u'gn': u'Gwinea',
 u'gp': u'Gwadelupa',
 u'gq': u'Gwinea R\xf3wnikowa',
 u'gr': u'Grecja',
 u'gs': u'Georgia Po\u0142udniowa i Sandwich Po\u0142udniowy',
 u'gt': u'Gwatemala',
 u'gu': u'Guam',
 u'gw': u'Gwinea-Bissau',
 u'gy': u'Gujana',
 u'hk': u'Hongkong',
 u'hm': u'Wyspy Heard i McDonalda',
 u'hn': u'Honduras',
 u'hr': u'Chorwacja',
 u'ht': u'Haiti',
 u'hu': u'W\u0119gry',
 u'id': u'Indonezja',
 u'ie': u'Irlandia',
 u'il': u'Izrael',
 u'im': u'Wyspa Man',
 u'in': u'Indie',
 u'io': u'Brytyjskie Terytorium Oceanu Indyjskiego',
 u'iq': u'Irak',
 u'ir': u'Iran',
 u'is': u'Islandia',
 u'it': u'W\u0142ochy',
 u'je': u'Jersey',
 u'jm': u'Jamajka',
 u'jo': u'Jordania',
 u'jp': u'Japonia',
 u'ke': u'Kenia',
 u'kg': u'Kirgistan',
 u'kh': u'Kambod\u017ca',
 u'ki': u'Kiribati',
 u'km': u'Komory',
 u'kn': u'Saint Kitts i Nevis',
 u'kp': u'Korea P\xf3\u0142nocna',
 u'kr': u'Korea Po\u0142udniowa',
 u'kw': u'Kuwejt',
 u'ky': u'Kajmany',
 u'kz': u'Kazachstan',
 u'la': u'Laos',
 u'lb': u'Liban',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Litwa',
 u'lu': u'Luksemburg',
 u'lv': u'\u0141otwa',
 u'ly': u'Libia',
 u'ma': u'Maroko',
 u'mc': u'Monako',
 u'md': u'Mo\u0142dawia',
 u'me': u'Czarnog\xf3ra',
 u'mf': u'Saint-Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Wyspy Marshalla',
 u'mk': u'Macedonia',
 u'ml': u'Mali',
 u'mm': u'Birma',
 u'mn': u'Mongolia',
 u'mo': u'Makau',
 u'mp': u'Mariany P\xf3\u0142nocne',
 u'mq': u'Martynika',
 u'mr': u'Mauretania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Malediwy',
 u'mw': u'Malawi',
 u'mx': u'Meksyk',
 u'my': u'Malezja',
 u'mz': u'Mozambik',
 u'na': u'Namibia',
 u'nc': u'Nowa Kaledonia',
 u'ne': u'Niger',
 u'nf': u'Wyspa Norfolk',
 u'ng': u'Nigeria',
 u'ni': u'Nikaragua',
 u'nl': u'Holandia',
 u'no': u'Norwegia',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nowa Zelandia',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Polinezja Francuska',
 u'pg': u'Papua-Nowa Gwinea',
 u'ph': u'Filipiny',
 u'pk': u'Pakistan',
 u'pl': u'Polska',
 u'pm': u'Saint Pierre i Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Portoryko',
 u'ps': u'Okupowane Terytoria Palesty\u0144skie',
 u'pt': u'Portugalia',
 u'pw': u'Palau',
 u'py': u'Paragwaj',
 u'qa': u'Katar',
 u're': u'Reunion',
 u'ro': u'Rumunia',
 u'rs': u'Serbia',
 u'ru': u'Rosja',
 u'rw': u'Rwanda',
 u'sa': u'Arabia Saudyjska',
 u'sb': u'Wyspy Salomona',
 u'sc': u'Seszele',
 u'sd': u'Sudan',
 u'se': u'Szwecja',
 u'sg': u'Singapur',
 u'sh': u'\u015awi\u0119ta Helena',
 u'si': u'S\u0142owenia',
 u'sj': u'Svalbard i Jan Mayen',
 u'sk': u'S\u0142owacja',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somalia',
 u'sr': u'Surinam',
 u'st': u'Wyspy \u015awi\u0119tego Tomasza i Ksi\u0105\u017c\u0119ca',
 u'sv': u'Salwador',
 u'sy': u'Syria',
 u'sz': u'Suazi',
 u'tc': u'Turks i Caicos',
 u'td': u'Czad',
 u'tf': u'Francuskie Terytoria Po\u0142udniowe',
 u'tg': u'Togo',
 u'th': u'Tajlandia',
 u'tj': u'Tad\u017cykistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor Wschodni',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunezja',
 u'to': u'Tonga',
 u'tr': u'Turcja',
 u'tt': u'Trynidad i Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Tajwan',
 u'tz': u'Tanzania',
 u'ua': u'Ukraina',
 u'ug': u'Uganda',
 u'um': u'Dalekie Wyspy Mniejsze Stan\xf3w Zjednoczonych',
 u'us': u'Stany Zjednoczone',
 u'uy': u'Urugwaj',
 u'uz': u'Uzbekistan',
 u'va': u'Watykan',
 u'vc': u'Saint Vincent i Grenadyny',
 u've': u'Wenezuela',
 u'vg': u'Brytyjskie Wyspy Dziewicze',
 u'vi': u'Wyspy Dziewicze Stan\xf3w Zjednoczonych',
 u'vn': u'Wietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis i Futuna',
 u'ws': u'Samoa',
 u'ye': u'Jemen',
 u'yt': u'Majotta',
 u'za': u'Republika Po\u0142udniowej Afryki',
 u'zm': u'Zambia',
 u'zw': u'Zimbabwe'}