REGIONS = {u'ad': u'Andorra',
 u'ae': u'Emirados \xc1rabes Unidos',
 u'af': u'Afeganist\xe3o',
 u'ag': u'Ant\xedgua e Barbuda',
 u'ai': u'Anguila',
 u'al': u'Alb\xe2nia',
 u'am': u'Arm\xeania',
 u'an': u'Antilhas Holandesas',
 u'ao': u'Angola',
 u'aq': u'Ant\xe1rtida',
 u'ar': u'Argentina',
 u'as': u'Samoa Americana',
 u'at': u'\xc1ustria',
 u'au': u'Austr\xe1lia',
 u'aw': u'Aruba',
 u'ax': u'Ilhas \xc5land',
 u'az': u'Azerbaij\xe3o',
 u'ba': u'B\xf3snia-Herzegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesh',
 u'be': u'B\xe9lgica',
 u'bf': u'Burquina Faso',
 u'bg': u'Bulg\xe1ria',
 u'bh': u'Bahrein',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'S\xe3o Bartolomeu',
 u'bm': u'Bermudas',
 u'bn': u'Brunei',
 u'bo': u'Bol\xedvia',
 u'br': u'Brasil',
 u'bs': u'Bahamas',
 u'bt': u'But\xe3o',
 u'bv': u'Ilha Bouvet',
 u'bw': u'Botsuana',
 u'by': u'Belarus',
 u'bz': u'Belize',
 u'ca': u'Canad\xe1',
 u'cc': u'Ilhas Cocos (Keeling)',
 u'cd': u'Rep\xfablica Democr\xe1tica do Congo',
 u'cf': u'Rep\xfablica Centro-Africana',
 u'cg': u'Congo',
 u'ch': u'Su\xed\xe7a',
 u'ci': u'Costa do Marfim',
 u'ck': u'Ilhas Cook',
 u'cl': u'Chile',
 u'cm': u'Rep\xfablica dos Camar\xf5es',
 u'cn': u'China',
 u'co': u'Col\xf4mbia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Cabo Verde',
 u'cx': u'Ilha Natal',
 u'cy': u'Chipre',
 u'cz': u'Rep\xfablica Tcheca',
 u'de': u'Alemanha',
 u'dj': u'Djibuti',
 u'dk': u'Dinamarca',
 u'dm': u'Dominica',
 u'do': u'Rep\xfablica Dominicana',
 u'dz': u'Arg\xe9lia',
 u'ec': u'Equador',
 u'ee': u'Est\xf4nia',
 u'eg': u'Egito',
 u'eh': u'Saara Ocidental',
 u'er': u'Eritr\xe9ia',
 u'es': u'Espanha',
 u'et': u'Eti\xf3pia',
 u'fi': u'Finl\xe2ndia',
 u'fj': u'Fiji',
 u'fk': u'Ilhas Falkland (Malvinas)',
 u'fm': u'Micron\xe9sia',
 u'fo': u'Ilhas Faro\xe9',
 u'fr': u'Fran\xe7a',
 u'ga': u'Gab\xe3o',
 u'gb': u'Reino Unido',
 u'gd': u'Granada',
 u'ge': u'Ge\xf3rgia',
 u'gf': u'Guiana Francesa',
 u'gg': u'Guernsey',
 u'gh': u'Gana',
 u'gi': u'Gibraltar',
 u'gl': u'Groenl\xe2ndia',
 u'gm': u'G\xe2mbia',
 u'gn': u'Guin\xe9',
 u'gp': u'Guadalupe',
 u'gq': u'Guin\xe9 Equatorial',
 u'gr': u'Gr\xe9cia',
 u'gs': u'Ge\xf3rgia do Sul e Ilhas Sandwich do Sul',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guin\xe9-Bissau',
 u'gy': u'Guiana',
 u'hk': u'Hong Kong',
 u'hm': u'Ilha Heard e Ilhas McDonald',
 u'hn': u'Honduras',
 u'hr': u'Cro\xe1cia',
 u'ht': u'Haiti',
 u'hu': u'Hungria',
 u'id': u'Indon\xe9sia',
 u'ie': u'Irlanda',
 u'il': u'Israel',
 u'im': u'Ilha de Man',
 u'in': u'\xcdndia',
 u'io': u'Territ\xf3rio Brit\xe2nico do Oceano \xcdndico',
 u'iq': u'Iraque',
 u'ir': u'Ir\xe3',
 u'is': u'Isl\xe2ndia',
 u'it': u'It\xe1lia',
 u'je': u'Jersey',
 u'jm': u'Jamaica',
 u'jo': u'Jord\xe2nia',
 u'jp': u'Jap\xe3o',
 u'ke': u'Qu\xeania',
 u'kg': u'Quirguist\xe3o',
 u'kh': u'Camboja',
 u'ki': u'Quiribati',
 u'km': u'Comores',
 u'kn': u'S\xe3o Crist\xf3v\xe3o e N\xe9vis',
 u'kp': u'Cor\xe9ia do Norte',
 u'kr': u'Rep\xfablica da Cor\xe9ia (Cor\xe9ia do Sul)',
 u'kw': u'Kuwait',
 u'ky': u'Ilhas Cayman',
 u'kz': u'Cazaquist\xe3o',
 u'la': u'Laos',
 u'lb': u'L\xedbano',
 u'lc': u'Santa L\xfacia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Lib\xe9ria',
 u'ls': u'Lesoto',
 u'lt': u'Litu\xe2nia',
 u'lu': u'Luxemburgo',
 u'lv': u'Let\xf4nia',
 u'ly': u'L\xedbia',
 u'ma': u'Marrocos',
 u'mc': u'M\xf4naco',
 u'md': u'Mold\xe1via',
 u'me': u'Montenegro',
 u'mf': u'S\xe3o Martinho',
 u'mg': u'Madagascar',
 u'mh': u'Ilhas Marshall',
 u'mk': u'Maced\xf4nia, Antiga Rep\xfablica Iugoslava da',
 u'ml': u'Mali',
 u'mm': u'Mianmar',
 u'mn': u'Mong\xf3lia',
 u'mo': u'Macau',
 u'mp': u'Ilhas Marianas do Norte',
 u'mq': u'Martinica',
 u'mr': u'Maurit\xe2nia',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Maur\xedcio',
 u'mv': u'Maldivas',
 u'mw': u'Malawi',
 u'mx': u'M\xe9xico',
 u'my': u'Mal\xe1sia',
 u'mz': u'Mo\xe7ambique',
 u'na': u'Nam\xedbia',
 u'nc': u'Nova Caled\xf4nia',
 u'ne': u'N\xedger',
 u'nf': u'Ilha Norfolk',
 u'ng': u'Nig\xe9ria',
 u'ni': u'Nicar\xe1gua',
 u'nl': u'Pa\xedses Baixos',
 u'no': u'Noruega',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nova Zel\xe2ndia',
 u'om': u'Om\xe3',
 u'pa': u'Panam\xe1',
 u'pe': u'Peru',
 u'pf': u'Polin\xe9sia Francesa',
 u'pg': u'Papua Nova-Guin\xe9',
 u'ph': u'Filipinas',
 u'pk': u'Paquist\xe3o',
 u'pl': u'Pol\xf4nia',
 u'pm': u'S\xe3o Pedro e Miquel\xe3o',
 u'pn': u'Pitcairn',
 u'pr': u'Porto Rico',
 u'ps': u'Palestina, Territ\xf3rio Ocupado da',
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguai',
 u'qa': u'Catar',
 u're': u'Reuni\xe3o',
 u'ro': u'Rom\xeania',
 u'rs': u'S\xe9rvia',
 u'ru': u'R\xfassia',
 u'rw': u'Ruanda',
 u'sa': u'Ar\xe1bia Saudita',
 u'sb': u'Ilhas Salom\xe3o',
 u'sc': u'Seychelles',
 u'sd': u'Sud\xe3o',
 u'se': u'Su\xe9cia',
 u'sg': u'Cingapura',
 u'sh': u'Santa Helena',
 u'si': u'Eslov\xeania',
 u'sj': u'Svalbard e Jan Mayen',
 u'sk': u'Eslov\xe1quia',
 u'sl': u'Serra Leoa',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Som\xe1lia',
 u'sr': u'Suriname',
 u'st': u'S\xe3o Tom\xe9 e Pr\xedncipe',
 u'sv': u'El Salvador',
 u'sy': u'S\xedria',
 u'sz': u'Suazil\xe2ndia',
 u'tc': u'Ilhas Turks e Caicos',
 u'td': u'Chade',
 u'tf': u'Territ\xf3rios Franceses do Sul',
 u'tg': u'Togo',
 u'th': u'Tail\xe2ndia',
 u'tj': u'Tadjiquist\xe3o',
 u'tk': u'Toquelau',
 u'tl': u'Timor Leste',
 u'tm': u'Turcomenist\xe3o',
 u'tn': u'Tun\xedsia',
 u'to': u'Tonga',
 u'tr': u'Turquia',
 u'tt': u'Trinidad e Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanz\xe2nia',
 u'ua': u'Ucr\xe2nia',
 u'ug': u'Uganda',
 u'um': u'Ilhas Menores Distantes dos Estados Unidos',
 u'us': u'Estados Unidos',
 u'uy': u'Uruguai',
 u'uz': u'Uzbequist\xe3o',
 u'va': u'Cidade do Vaticano',
 u'vc': u'S\xe3o Vincente e Granadinas',
 u've': u'Venezuela',
 u'vg': u'Ilhas Virgens Brit\xe2nicas',
 u'vi': u'Ilhas Virgens',
 u'vn': u'Vietn\xe3',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis e Futuna',
 u'ws': u'Samoa',
 u'ye': u'I\xeamen',
 u'yt': u'Mayotte',
 u'za': u'\xc1frica do Sul',
 u'zm': u'Z\xe2mbia',
 u'zw': u'Zimb\xe1bue'}