REGIONS = {u'ad': u'Andorra',
 u'ae': u'E.A.U.',
 u'af': u'Afeganist\xe3o',
 u'ag': u'Ant\xedgua e Barbados',
 u'ai': u'Anguila',
 u'al': u'Alb\xe2nia',
 u'am': u'Arm\xe9nia',
 u'an': u'Antilhas Holandesas',
 u'ao': u'Angola',
 u'aq': u'Ant\xe1rctica',
 u'ar': u'Argentina',
 u'as': u'Samoa Americana',
 u'at': u'\xc1ustria',
 u'au': u'Austr\xe1lia',
 u'aw': u'Aruba',
 u'ax': u'Ilhas Alanda',
 u'az': u'Azerbeij\xe3o',
 u'ba': u'B\xf3snia-Herzegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesh',
 u'be': u'B\xe9lgica',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulg\xe1ria',
 u'bh': u'Bahrein',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei',
 u'bo': u'Bol\xedvia',
 u'br': u'Brasil',
 u'bs': u'Bahamas',
 u'bt': u'But\xe3o',
 u'bv': u'Ilha Bouvet',
 u'bw': u'Botswana',
 u'by': u'Bielor\xfassia',
 u'bz': u'Belize',
 u'ca': u'Canad\xe1',
 u'cc': u'Ilhas de Cocos',
 u'cd': u'Congo-Kinshasa',
 u'cf': u'Rep\xfabloca Centro-Africana',
 u'cg': u'Congo-Brazzaville',
 u'ch': u'Sui\xe7a',
 u'ci': u'Costa do Marfim',
 u'ck': u'Ilhas Cook',
 u'cl': u'Chile',
 u'cm': u'Camar\xf5es',
 u'cn': u'China',
 u'co': u'Col\xf4mbia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'Cabo Verde',
 u'cx': u'Ilha do Natal',
 u'cy': u'Chipre',
 u'cz': u'Rep\xfablica Checa',
 u'de': u'Alemanha',
 u'dj': u'Jibouti',
 u'dk': u'Dinamarca',
 u'dm': u'Dominica',
 u'do': u'Rep\xfablica Dominicana',
 u'dz': u'Arg\xe9lia',
 u'ec': u'Equador',
 u'ee': u'Est\xf3nia',
 u'eg': u'Egipto',
 u'eh': u'Saara Ocidental',
 u'er': u'Eritreia',
 u'es': u'Espanha',
 u'et': u'Eti\xf3pia',
 u'fi': u'Finl\xe2ndia',
 u'fj': u'Ilhas Fiji',
 u'fk': u'Malvinas',
 u'fm': u'Micron\xe9sia',
 u'fo': u'Ilhas Faro\xe9',
 u'fr': u'Fran\xe7a',
 u'ga': u'Gab\xe3o',
 u'gb': u'Reino Unido',
 u'gd': u'Granada',
 u'ge': u'Ge\xe9rgia',
 u'gf': u'Guiana Francesa',
 u'gg': u'Guernsey',
 u'gh': u'Gana',
 u'gi': u'Gibraltar',
 u'gl': u'Gronel\xe2ndia',
 u'gm': u'G\xe2mbia',
 u'gn': u'Guin\xe9',
 u'gp': u'Guadalupe',
 u'gq': u'Guin\xe9 Equatorial',
 u'gr': u'Gr\xe9cia',
 u'gs': u'Ilhas de South Georgia e South Sandwich',
 u'gt': u'Guatemala',
 u'gu': u'Gu\xe3o',
 u'gw': u'Guin\xe9-Bissau',
 u'gy': u'Guiana',
 u'hk': u'Hong Kong',
 u'hm': u'Ilhas Heard e McDonald',
 u'hn': u'Honduras',
 u'hr': u'Cro\xe1cia',
 u'ht': u'Haiti',
 u'hu': u'Hungria',
 u'id': u'Indon\xe9sia',
 u'ie': u'Irlanda',
 u'il': u'Israel',
 u'im': u'Ilha de Man',
 u'in': u'India',
 u'io': u'Territ\xf3rio Brit\xe2nico Oce\xe2nico da India',
 u'iq': u'Iraque',
 u'ir': u'Ir\xe3o',
 u'is': u'Isl\xe2ndia',
 u'it': u'It\xe1lia',
 u'je': u'J\xe9rsia',
 u'jm': u'Jamaica',
 u'jo': u'Jord\xe2nia',
 u'jp': u'Jap\xe3o',
 u'ke': u'Qu\xe9nia',
 u'kg': u'Kirziquist\xe3o',
 u'kh': u'Cambodja',
 u'ki': u'Kiribati',
 u'km': u'Comores',
 u'kn': u'Saint Kitts e Nevis',
 u'kp': u'Coreia do Norte',
 u'kr': u'Coreia do Sul',
 u'kw': u'Kuwait',
 u'ky': u'Ilhas Caim\xe3o',
 u'kz': u'Kazaquist\xe3o',
 u'la': u'Laos',
 u'lb': u'L\xedbano',
 u'lc': u'Santa Luzia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Lib\xe9ria',
 u'ls': u'Lesoto',
 u'lt': u'Litu\xe2nia',
 u'lu': u'Luxemburgo',
 u'lv': u'Let\xf3nia',
 u'ly': u'L\xedbia',
 u'ma': u'Marrocos',
 u'mc': u'M\xf3naco',
 u'md': u'Mold\xe1via',
 u'me': u'Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madag\xe1scar',
 u'mh': u'Ilhas Marshall',
 u'mk': u'Rep\xfablica da Maced\xf3nia',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mong\xf3lia',
 u'mo': u'Macau',
 u'mp': u'Ilhas Marianas do Norte',
 u'mq': u'Martinica',
 u'mr': u'Maurit\xe2nia',
 u'ms': u'Montserrate',
 u'mt': u'Malta',
 u'mu': u'Maur\xedcias',
 u'mv': u'Maldivas',
 u'mw': u'Malaui',
 u'mx': u'M\xe9xico',
 u'my': u'Mal\xe1sia',
 u'mz': u'Mo\xe7ambique',
 u'na': u'Nam\xedbia',
 u'nc': u'Nova Caled\xf3nia',
 u'ne': u'N\xedger',
 u'nf': u'Ilha de Norfolk',
 u'ng': u'Nig\xe9ria',
 u'ni': u'Nicar\xe1gua',
 u'nl': u'Holanda',
 u'no': u'Noruega',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nova Zel\xe2ndia',
 u'om': u'Om\xe3o',
 u'pa': u'Panam\xe1',
 u'pe': u'Peru',
 u'pf': u'Polin\xe9sia Francesa',
 u'pg': u'Papua Nova Guin\xe9',
 u'ph': u'Filipinas',
 u'pk': u'Paquist\xe3o',
 u'pl': u'Pol\xf3nia',
 u'pm': u'Saint Pierre e Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Porto Rico',
 u'ps': u'Territ\xf3rio Palestiniano Ocupado',
 u'pt': u'Portugal',
 u'pw': u'Palau',
 u'py': u'Paraguai',
 u'qa': u'Catar',
 u're': u'Reuni\xe3o',
 u'ro': u'Rom\xe9nia',
 u'rs': u'Serbia',
 u'ru': u'Federa\xe7\xe3o Russa',
 u'rw': u'Ruanda',
 u'sa': u'Ar\xe1bia Saudita',
 u'sb': u'Ilhas Salom\xe3o',
 u'sc': u'Seicheles',
 u'sd': u'Sud\xe3o',
 u'se': u'Su\xe9cia',
 u'sg': u'Singapora',
 u'sh': u'Santa Helena',
 u'si': u'Eslov\xe9nia',
 u'sj': u'Svalbard e Jan Mayen',
 u'sk': u'Eslov\xe1quia',
 u'sl': u'Serra Leoa',
 u'sm': u'S\xe3o Marino',
 u'sn': u'Senegal',
 u'so': u'Som\xe1lia',
 u'sr': u'Suriname',
 u'st': u'S\xe3o Tom\xe9 e Pr\xedncipe',
 u'sv': u'El Salvador',
 u'sy': u'S\xedria',
 u'sz': u'Swazil\xe2ndia',
 u'tc': u'Ilhas Turks e Caicos',
 u'td': u'Chad',
 u'tf': u'Territ\xf3rios Franceses do Sul',
 u'tg': u'Togo',
 u'th': u'Tail\xe2ndia',
 u'tj': u'Tadjiquist\xe3o',
 u'tk': u'Toquelau',
 u'tl': u'Timor-Leste',
 u'tm': u'Turqueminist\xe3o',
 u'tn': u'Tun\xedsia',
 u'to': u'Tonga',
 u'tr': u'Turquia',
 u'tt': u'Trinidade e Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Formosa',
 u'tz': u'Tanz\xe2nia',
 u'ua': u'Ucr\xe2nia',
 u'ug': u'Uganda',
 u'um': u'Ilhas Pequenas dos Estados Unidos da Am\xe9rica',
 u'us': u'Estados Unidos da Am\xe9rica',
 u'uy': u'Uruguai',
 u'uz': u'Usbequist\xe3o',
 u'va': u'Cidade do Vaticano',
 u'vc': u'Saint Vincent e as Grenadines',
 u've': u'Venezuela',
 u'vg': u'Ilhas Selvagens Brit\xe2nicas',
 u'vi': u'Ilhas Selvagens Norte Americanas',
 u'vn': u'Vietname',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis e Futuna',
 u'ws': u'Samoa',
 u'ye': u'I\xe9men',
 u'yt': u'Mayotte',
 u'za': u'\xc1frica do Sul',
 u'zm': u'Z\xe2mbia',
 u'zw': u'Zimbabwe'}