REGIONS = {u'ad': u'Andorra',
 u'ae': u'Spojen\xe9 Arabsk\xe9 Emir\xe1ty',
 u'af': u'Afganistan',
 u'ag': u'Antigua a Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Alb\xe1nsko',
 u'am': u'Arm\xe9nsko',
 u'an': u'Holandsk\xe9 Antily',
 u'ao': u'Angola',
 u'aq': u'Antarkt\xedda',
 u'ar': u'Argent\xedna',
 u'as': u'Americk\xe1 Samoa',
 u'at': u'Rak\xfasko',
 u'au': u'Austr\xe1lia',
 u'aw': u'Aruba',
 u'ax': u'Alandsk\xe9 ostrovy',
 u'az': u'Azerbajd\u017ean',
 u'ba': u'Bosna a Hercegovina',
 u'bb': u'Barbados',
 u'bd': u'Banglad\xe9\u0161',
 u'be': u'Belgicko',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulharsko',
 u'bh': u'Bahrajn',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Sv\xe4t\xfd Bartolomej',
 u'bm': u'Bermudy',
 u'bn': u'Brunej',
 u'bo': u'Bol\xedvia',
 u'br': u'Braz\xedlia',
 u'bs': u'Bahamy',
 u'bt': u'Bhut\xe1n',
 u'bv': u'Bouvetov ostrov',
 u'bw': u'Botswana',
 u'by': u'Bielorusko',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Kokosov\xe9 ostrovy',
 u'cd': u'Kon\u017esk\xe1 republika',
 u'cf': u'Stredoafrick\xe1 republika',
 u'cg': u'Kon\u017esk\xe1 demokratick\xe1 republika',
 u'ch': u'\u0160vaj\u010diarsko',
 u'ci': u'Pobre\u017eie Slonoviny',
 u'ck': u'Cookove ostrovy',
 u'cl': u'\u010cile',
 u'cm': u'Kamerun',
 u'cn': u'\u010c\xedna',
 u'co': u'Kolumbia',
 u'cr': u'Kostarika',
 u'cu': u'Kuba',
 u'cv': u'Kapverdsk\xe9 ostrovy',
 u'cx': u'Viano\u010dn\xfd ostrov',
 u'cy': u'Cyprus',
 u'cz': u'\u010cesk\xe1 republika',
 u'de': u'Nemecko',
 u'dj': u'D\u017eibuti',
 u'dk': u'D\xe1nsko',
 u'dm': u'Dominika',
 u'do': u'Dominik\xe1nska republika',
 u'dz': u'Al\u017e\xedrsko',
 u'ec': u'Ekv\xe1dor',
 u'ee': u'Est\xf3nsko',
 u'eg': u'Egypt',
 u'eh': u'Z\xe1padn\xe1 Sahara',
 u'er': u'Eritrea',
 u'es': u'\u0160panielsko',
 u'et': u'Eti\xf3pia',
 u'fi': u'F\xednsko',
 u'fj': u'Fid\u017ei',
 u'fk': u'Falklandy (Malv\xedny)',
 u'fm': u'Mikron\xe9zia',
 u'fo': u'Faersk\xe9 ostrovy',
 u'fr': u'Franc\xfazsko',
 u'ga': u'Gabon',
 u'gb': u'Spojen\xe9 kr\xe1\u013eovstvo',
 u'gd': u'Grenada',
 u'ge': u'Gruz\xednsko',
 u'gf': u'Franc\xfazska Guyana',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibralt\xe1r',
 u'gl': u'Gr\xf3nsko',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'Rovn\xedkov\xe1 Guinea',
 u'gr': u'Gr\xe9cko',
 u'gs': u'Ju\u017en\xe1 Georgia a Ju\u017en\xe9 Sandwich ostrovy',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hongkong',
 u'hm': u'Ostrovy Heard a McDonald',
 u'hn': u'Honduras',
 u'hr': u'Chorv\xe1tsko',
 u'ht': u'Haiti',
 u'hu': u'Ma\u010farsko',
 u'id': u'Indon\xe9zia',
 u'ie': u'\xcdrsko',
 u'il': u'Izrael',
 u'im': u'Ostrov Man',
 u'in': u'India',
 u'io': u'Britsk\xe9 Indicko-oce\xe1nske \xfazemie',
 u'iq': u'Irak',
 u'ir': u'Ir\xe1n',
 u'is': u'Island',
 u'it': u'Taliansko',
 u'je': u'Jersey',
 u'jm': u'Jamajka',
 u'jo': u'Jord\xe1nsko',
 u'jp': u'Japonsko',
 u'ke': u'Ke\u0148a',
 u'kg': u'Kirgizsko',
 u'kh': u'Kambod\u017ea',
 u'ki': u'Kiribati',
 u'km': u'Komory',
 u'kn': u'Sv\xe4t\xfd Kri\u0161tof a Nevis',
 u'kp': u'K\u013dDR',
 u'kr': u'Ju\u017en\xe1 K\xf3rea',
 u'kw': u'Kuvajt',
 u'ky': u'Kajmansk\xe9 ostrovy',
 u'kz': u'Kazachstan',
 u'la': u'Laos',
 u'lb': u'Libanon',
 u'lc': u'Sv\xe4t\xe1 Lucia',
 u'li': u'Lichten\u0161tajnsko',
 u'lk': u'Sr\xed Lanka',
 u'lr': u'Lib\xe9ria',
 u'ls': u'Lesotho',
 u'lt': u'Litva',
 u'lu': u'Luxembursko',
 u'lv': u'Loty\u0161sko',
 u'ly': u'L\xedbya',
 u'ma': u'Maroko',
 u'mc': u'Monako',
 u'md': u'Moldavsko',
 u'me': u'\u010cierna Hora',
 u'mf': u'Sv\xe4t\xfd Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Marshallove ostrovy',
 u'mk': u'Maced\xf3nsko',
 u'ml': u'Mali',
 u'mm': u'Mjanmarsko',
 u'mn': u'Mongolsko',
 u'mo': u'Macau',
 u'mp': u'Severn\xe9 Mari\xe1ny, ostrovy',
 u'mq': u'Martinik',
 u'mr': u'Mauret\xe1nia',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Maur\xedcius',
 u'mv': u'Maldivy',
 u'mw': u'Malawi',
 u'mx': u'Mexiko',
 u'my': u'Malajzia',
 u'mz': u'Mozambik',
 u'na': u'Nam\xedbia',
 u'nc': u'Nov\xe1 Kaled\xf3nia',
 u'ne': u'Niger',
 u'nf': u'Ostrov Norfolk',
 u'ng': u'Nig\xe9ria',
 u'ni': u'Nikaragua',
 u'nl': u'Holandsko',
 u'no': u'N\xf3rsko',
 u'np': u'Nep\xe1l',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Nov\xfd Z\xe9land',
 u'om': u'Om\xe1n',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Franc\xfazska Polyn\xe9zia',
 u'pg': u'Papua-Nov\xe1 Guinea',
 u'ph': u'Filip\xedny',
 u'pk': u'Pakistan',
 u'pl': u'Po\u013esko',
 u'pm': u'Sv\xe4t\xfd Pierre a Miquelon',
 u'pn': u'Pitcairnove ostrovy',
 u'pr': u'Portoriko',
 u'ps': u'Palest\xednske \xfazemia',
 u'pt': u'Portugalsko',
 u'pw': u'Palau',
 u'py': u'Paraguaj',
 u'qa': u'Katar',
 u're': u'Ostrov R\xe9union',
 u'ro': u'Rumunsko',
 u'rs': u'Srbsko',
 u'ru': u'Rusko',
 u'rw': u'Rwanda',
 u'sa': u'Saudsk\xe1 Ar\xe1bia',
 u'sb': u'\u0160alam\xfanove ostrovy',
 u'sc': u'Seychely',
 u'sd': u'Sud\xe1n',
 u'se': u'\u0160v\xe9dsko',
 u'sg': u'Singapur',
 u'sh': u'Sv\xe4t\xe1 Helena',
 u'si': u'Slovinsko',
 u'sj': u'Ostrovy Svalbard a Jan Mayen',
 u'sk': u'Slovensko',
 u'sl': u'Sierra Leone',
 u'sm': u'San Mar\xedno',
 u'sn': u'Senegal',
 u'so': u'Som\xe1lsko',
 u'sr': u'Surinam',
 u'st': u'Sv\xe4t\xfd Tom\xe1\u0161 a Princov ostrov',
 u'sv': u'Salvador',
 u'sy': u'S\xfdria',
 u'sz': u'Svazijsko',
 u'tc': u'Ostrovy Turks a Caicos',
 u'td': u'\u010cad',
 u'tf': u'Franc\xfazske ju\u017en\xe9 \xfazemia',
 u'tg': u'Togo',
 u'th': u'Thajsko',
 u'tj': u'Tad\u017eikistan',
 u'tk': u'Tokelau',
 u'tl': u'Timor-Leste',
 u'tm': u'Turkm\xe9nsko',
 u'tn': u'Tunisko',
 u'to': u'Tonga',
 u'tr': u'Turecko',
 u'tt': u'Trinidad a Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Taiwan',
 u'tz': u'Tanz\xe1nia',
 u'ua': u'Ukrajina',
 u'ug': u'Uganda',
 u'um': u'USA (mal\xe9 ostrovy)',
 u'us': u'USA',
 u'uy': u'Uruguaj',
 u'uz': u'Uzbekistan',
 u'va': u'Vatik\xe1n',
 u'vc': u'Sv\xe4t\xfd Vincent a Grenad\xedny',
 u've': u'Venezuela',
 u'vg': u'Britsk\xe9 Panensk\xe9 ostrovy',
 u'vi': u'Panensk\xe9 ostrovy Spojen\xfdch \u0161t\xe1tov',
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Z\xe1morsk\xe9 terit\xf3rium Wallisu a Futuny',
 u'ws': u'Z\xe1padn\xe1 Samoa',
 u'ye': u'Jemen',
 u'yt': u'Mayotte',
 u'za': u'JAR',
 u'zm': u'Zambia',
 u'zw': u'Zimbabwe'}