REGIONS = {u'ad': u'Andorra',
 u'ae': u'BAE',
 u'af': u'Afganistan',
 u'ag': u'Antigua ve Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Arnavutluk',
 u'am': u'Ermenistan',
 u'an': u'Hollanda Antilleri',
 u'ao': u'Angola',
 u'aq': u'Antarktika',
 u'ar': u'Arjantin',
 u'as': u'Amerika Samoas\u0131',
 u'at': u'Avusturya',
 u'au': u'Avustralya',
 u'aw': u'Aruba',
 u'ax': u'Aland Adalar\u0131',
 u'az': u'Azerbaycan',
 u'ba': u'Bosna Hersek',
 u'bb': u'Barbados',
 u'bd': u'Banglade\u015f',
 u'be': u'Bel\xe7ika',
 u'bf': u'Burkina Faso',
 u'bg': u'Bulgaristan',
 u'bh': u'Bahreyn',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Aziz Barthelemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei Sultanl\u0131\u011f\u0131',
 u'bo': u'Bolivya',
 u'br': u'Brezilya',
 u'bs': u'Bahamalar',
 u'bt': u'Butan',
 u'bv': u'Bouvet Adas\u0131',
 u'bw': u'Botsvana',
 u'by': u'Beyaz Rusya',
 u'bz': u'Belize',
 u'ca': u'Kanada',
 u'cc': u'Cocos (Keeling) Adalar\u0131',
 u'cd': u'Kongo Kin\u015fasa',
 u'cf': u'Orta Afrika Cumhuriyeti',
 u'cg': u'Kongo - Brazzaville',
 u'ch': u'\u0130svi\xe7re',
 u'ci': u'Fildi\u015fi Sahili',
 u'ck': u'Cook Adalar\u0131',
 u'cl': u'\u015eili',
 u'cm': u'Kamerun',
 u'cn': u'\xc7in',
 u'co': u'Kolombiya',
 u'cr': u'Kosta Rica',
 u'cu': u'K\xfcba',
 u'cv': u'Cape Verde',
 u'cx': u'Christmas Adas\u0131',
 u'cy': u'G\xfcney K\u0131br\u0131s Rum Kesimi',
 u'cz': u'\xc7ek Cumhuriyeti',
 u'de': u'Almanya',
 u'dj': u'Cibuti',
 u'dk': u'Danimarka',
 u'dm': u'Dominik',
 u'do': u'Dominik Cumhuriyeti',
 u'dz': u'Cezayir',
 u'ec': u'Ekvador',
 u'ee': u'Estonya',
 u'eg': u'M\u0131s\u0131r',
 u'eh': u'Bat\u0131 Sahara',
 u'er': u'Eritre',
 u'es': u'\u0130spanya',
 u'et': u'Etiyopya',
 u'fi': u'Finlandiya',
 u'fj': u'Fiji',
 u'fk': u'Falkland Adalar\u0131 (Malvinalar)',
 u'fm': u'Mikronezya',
 u'fo': u'Faroe Adalar\u0131',
 u'fr': u'Fransa',
 u'ga': u'Gabon',
 u'gb': u'Birle\u015fik Krall\u0131k',
 u'gd': u'Grenada',
 u'ge': u'G\xfcrcistan',
 u'gf': u'Frans\u0131z Guyanas\u0131',
 u'gg': u'Guernsey',
 u'gh': u'Gana',
 u'gi': u'Cebelitar\u0131k',
 u'gl': u'Gr\xf6nland',
 u'gm': u'Gambiya',
 u'gn': u'Gine',
 u'gp': u'Guadeloupe',
 u'gq': u'Ekvatoral Gine',
 u'gr': u'Yunanistan',
 u'gs': u'G\xfcney Georgia ve G\xfcney Sandvi\xe7 Adalar\u0131',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Gine Bissau',
 u'gy': u'Guyana',
 u'hk': u'Hong Kong',
 u'hm': u'Heard Adas\u0131 ve McDonald Adalar\u0131',
 u'hn': u'Honduras',
 u'hr': u'H\u0131rvatistan',
 u'ht': u'Haiti',
 u'hu': u'Macaristan',
 u'id': u'Endonezya',
 u'ie': u'\u0130rlanda',
 u'il': u'\u0130srail',
 u'im': u'Man Adas\u0131',
 u'in': u'Hindistan',
 u'io': u"Britanya'n\u0131n Hint Okyanusu Topraklar\u0131",
 u'iq': u'Irak',
 u'ir': u'\u0130ran',
 u'is': u'\u0130zlanda',
 u'it': u'\u0130talya',
 u'je': u'Jersey',
 u'jm': u'Jamaika',
 u'jo': u'\xdcrd\xfcn',
 u'jp': u'Japonya',
 u'ke': u'Kenya',
 u'kg': u'K\u0131rg\u0131zistan',
 u'kh': u'Kambo\xe7ya',
 u'ki': u'Kiribati',
 u'km': u'Komolar',
 u'kn': u'Saint Kitts ve Nevis',
 u'kp': u'Kuzey Kore',
 u'kr': u'G\xfcney Kore',
 u'kw': u'Kuveyt',
 u'ky': u'Cayman Adalar\u0131',
 u'kz': u'Kazakistan',
 u'la': u'Laos',
 u'lb': u'L\xfcbnan',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberya',
 u'ls': u'Lesotho',
 u'lt': u'Litvanya',
 u'lu': u'L\xfcksemburg',
 u'lv': u'Letonya',
 u'ly': u'Libya',
 u'ma': u'Fas',
 u'mc': u'Monako',
 u'md': u'Moldova',
 u'me': u'Karada\u011f',
 u'mf': u'Saint Martin',
 u'mg': u'Madagaskar',
 u'mh': u'Marshall Adalar\u0131',
 u'mk': u'Makedonya Cumhuriyeti',
 u'ml': u'Mali',
 u'mm': u'Myanmar',
 u'mn': u'Mo\u011folistan',
 u'mo': u'Macau',
 u'mp': u'Kuzey Mariana Adalar\u0131',
 u'mq': u'Martinik',
 u'mr': u'Moritanya',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Maldivler',
 u'mw': u'Malavi',
 u'mx': u'Meksika',
 u'my': u'Malezya',
 u'mz': u'Mozambik',
 u'na': u'Namibya',
 u'nc': u'Yeni Kaledonya',
 u'ne': u'Nijer',
 u'nf': u'Norfolk Adas\u0131',
 u'ng': u'Nijerya',
 u'ni': u'Nikaragua',
 u'nl': u'Hollanda',
 u'no': u'Norve\xe7',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'Yeni Zelanda',
 u'om': u'Umman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Frans\u0131z Polinezyas\u0131',
 u'pg': u'Papua Yeni Gine',
 u'ph': u'Filipinler',
 u'pk': u'Pakistan',
 u'pl': u'Polanya',
 u'pm': u'Saint Pierre ve Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Porto Riko',
 u'ps': u'Filistin',
 u'pt': u'Portekiz',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Katar',
 u're': u'Reunion',
 u'ro': u'Romanya',
 u'rs': u'S\u0131rbistan',
 u'ru': u'Rusya Federasyonu',
 u'rw': u'Ruanda',
 u'sa': u'Suudi Arabistan',
 u'sb': u'Solomon Adalar\u0131',
 u'sc': u'Sey\u015feller',
 u'sd': u'Sudan',
 u'se': u'\u0130sve\xe7',
 u'sg': u'Singapur',
 u'sh': u'Saint Helena',
 u'si': u'Slovenya',
 u'sj': u'Svalbard ve Jan Mayen',
 u'sk': u'Slovakya',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somali',
 u'sr': u'Surinam',
 u'st': u'Sao Tome ve Principe',
 u'sv': u'El Salvador',
 u'sy': u'Suriye',
 u'sz': u'Svaziland',
 u'tc': u'Turks ve Caicos Adalar\u0131',
 u'td': u'\xc7ad',
 u'tf': u"Fransa'n\u0131n G\xfcney Topraklar\u0131",
 u'tg': u'Togo',
 u'th': u'Tayland',
 u'tj': u'Tacikistan',
 u'tk': u'Tokelau',
 u'tl': u'Do\u011fu Timor',
 u'tm': u'T\xfcrkmenistan',
 u'tn': u'Tunus',
 u'to': u'Tonga',
 u'tr': u'T\xfcrkiye',
 u'tt': u'Trinidad Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'Tayvan',
 u'tz': u'Tanzanya',
 u'ua': u'Ukrayna',
 u'ug': u'Uganda',
 u'um': u'ABD Minor Outlying Adalar\u0131',
 u'us': u'ABD',
 u'uy': u'Uruguay',
 u'uz': u'\xd6zbekistan',
 u'va': u'Vatikan',
 u'vc': u'Saint Vincent ve Grenadineler',
 u've': u'Venezuela',
 u'vg': u"Britanya'n\u0131n Virjin Adalar\u0131",
 u'vi': u"ABD'nin Virjin Adalar\u0131",
 u'vn': u'Vietnam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis ve Futuna',
 u'ws': u'Samoa',
 u'ye': u'Yemen',
 u'yt': u'Mayotte',
 u'za': u'G\xfcney Africa',
 u'zm': u'Zambia',
 u'zw': u'Zimbabve'}