REGIONS = {u'ad': u'Andorra',
 u'ae': u'C\xe1c Ti\u1ec3u v\u01b0\u01a1ng qu\u1ed1c \u1ea2 R\u1eadp th\u1ed1ng nh\u1ea5t',
 u'af': u'Afghanistan',
 u'ag': u'Antigua v\xe0 Barbuda',
 u'ai': u'Anguilla',
 u'al': u'Albania',
 u'am': u'Armenia',
 u'an': u'Antilles H\xe0 Lan',
 u'ao': u'Angola',
 u'aq': u'Ch\xe2u Nam C\u1ef1c',
 u'ar': u'Argentina',
 u'as': u'Samoa Ch\xe2u M\u1ef9',
 u'at': u'\xc1o',
 u'au': u'\xdac',
 u'aw': u'Aruba',
 u'ax': u'Qu\u1ea7n \u0111\u1ea3o \xc5land',
 u'az': u'Azerbaijan',
 u'ba': u'Bosnia v\xe0 Herzegovina',
 u'bb': u'Barbados',
 u'bd': u'Bangladesh',
 u'be': u'B\u1ec9',
 u'bf': u'Burkina Faso',
 u'bg': u'Bungari',
 u'bh': u'Bahrain',
 u'bi': u'Burundi',
 u'bj': u'Benin',
 u'bl': u'Saint Barth\xe9lemy',
 u'bm': u'Bermuda',
 u'bn': u'Brunei Darussalam',
 u'bo': u'Bolivia',
 u'br': u'Brazil',
 u'bs': u'Bahamas',
 u'bt': u'Bhutan',
 u'bv': u'\u0110\u1ea3o Bouvet',
 u'bw': u'Botswana',
 u'by': u'Belarus',
 u'bz': u'Belize',
 u'ca': u'Canada',
 u'cc': u'Qu\u1ea7n \u0111\u1ea3o Cocos (Keeling)',
 u'cd': u'Congo-Kinshasa',
 u'cf': u'C\u1ed9ng h\xf2a Trung Phi',
 u'cg': u'Congo-Brazzaville',
 u'ch': u'Th\u1ee5y S\u0129',
 u'ci': u'B\u1edd Bi\u1ec3n Ng\xe0',
 u'ck': u'Qu\u1ea7n \u0111\u1ea3o Cook',
 u'cl': u'Chile',
 u'cm': u'Cameroon',
 u'cn': u'Trung Qu\u1ed1c',
 u'co': u'Colombia',
 u'cr': u'Costa Rica',
 u'cu': u'Cuba',
 u'cv': u'C\xe1p Ve',
 u'cx': u'\u0110\u1ea3o Gi\xe1ng Sinh',
 u'cy': u'S\xedp',
 u'cz': u'C\u1ed9ng h\xf2a S\xe9c',
 u'de': u'\u0110\u1ee9c',
 u'dj': u'Djibouti',
 u'dk': u'\u0110an M\u1ea1ch',
 u'dm': u'Dominica',
 u'do': u'C\u1ed9ng h\xf2a Dominica',
 u'dz': u'Angi\xeari',
 u'ec': u'Ecuador',
 u'ee': u'Estonia',
 u'eg': u'Ai C\u1eadp',
 u'eh': u'T\xe2y Sahara',
 u'er': u'Eritrea',
 u'es': u'T\xe2y Ban Nha',
 u'et': u'Ethiopia',
 u'fi': u'Ph\u1ea7n Lan',
 u'fj': u'Fiji',
 u'fk': u'Qu\u1ea7n \u0111\u1ea3o Falkland (Malvina)',
 u'fm': u'Micronesia',
 u'fo': u'Qu\u1ea7n \u0111\u1ea3o Faroe',
 u'fr': u'Ph\xe1p',
 u'ga': u'Gabon',
 u'gb': u'V\u01b0\u01a1ng qu\u1ed1c Anh',
 u'gd': u'Grenada',
 u'ge': u'Gruzia',
 u'gf': u'Guiana thu\u1ed9c Ph\xe1p',
 u'gg': u'Guernsey',
 u'gh': u'Ghana',
 u'gi': u'Gibraltar',
 u'gl': u'Greenland',
 u'gm': u'Gambia',
 u'gn': u'Guinea',
 u'gp': u'Guadeloupe',
 u'gq': u'Guinea X\xedch \u0110\u1ea1o',
 u'gr': u'Hi L\u1ea1p',
 u'gs': u'South Georgia v\xe0 South Sandwich Islands',
 u'gt': u'Guatemala',
 u'gu': u'Guam',
 u'gw': u'Guinea-Bissau',
 u'gy': u'Guyana',
 u'hk': u'H\u1ed3ng K\xf4ng',
 u'hm': u'Heard Island v\xe0 McDonald Islands',
 u'hn': u'Honduras',
 u'hr': u'Croatia',
 u'ht': u'Haiti',
 u'hu': u'Hungary',
 u'id': u'Indonesia',
 u'ie': u'Ai Len',
 u'il': u'Israel',
 u'im': u'\u0110\u1ea3o Man',
 u'in': u'\u1ea4n \u0110\u1ed9',
 u'io': u'L\xe3nh th\u1ed5 \u1ea4n \u0110\u1ed9 D\u01b0\u01a1ng thu\u1ed9c Anh',
 u'iq': u'Iraq',
 u'ir': u'Iran',
 u'is': u'Iceland',
 u'it': u'\xdd',
 u'je': u'Jersey',
 u'jm': u'Jamaica',
 u'jo': u'Jordan',
 u'jp': u'Nh\u1eadt B\u1ea3n',
 u'ke': u'Kenya',
 u'kg': u'Kyrgyzstan',
 u'kh': u'Campuchia',
 u'ki': u'Kiribati',
 u'km': u'Comoros',
 u'kn': u'Saint Kitts v\xe0 Nevis',
 u'kp': u'Tri\u1ec1u Ti\xean',
 u'kr': u'H\xe0n Qu\u1ed1c',
 u'kw': u'Kuwait',
 u'ky': u'Qu\u1ea7n \u0111\u1ea3o Cayman',
 u'kz': u'Kazakhstan',
 u'la': u'L\xe0o',
 u'lb': u'Lib\u0103ng',
 u'lc': u'Saint Lucia',
 u'li': u'Liechtenstein',
 u'lk': u'Sri Lanka',
 u'lr': u'Liberia',
 u'ls': u'Lesotho',
 u'lt': u'Litva',
 u'lu': u'Luxembourg',
 u'lv': u'Latvia',
 u'ly': u'Libya',
 u'ma': u'Mar\u1ed1c',
 u'mc': u'Monaco',
 u'md': u'Moldova',
 u'me': u'Montenegro',
 u'mf': u'Saint Martin',
 u'mg': u'Madagascar',
 u'mh': u'Qu\u1ea7n \u0111\u1ea3o Marshall',
 u'mk': u'Macedonia (C\u1ed9ng h\xf2a thu\u1ed9c Nam T\u01b0 C\u0169)',
 u'ml': u'Mali',
 u'mm': u'Myanma',
 u'mn': u'M\xf4ng C\u1ed5',
 u'mo': u'Macao',
 u'mp': u'Qu\u1ea7n \u0111\u1ea3o B\u1eafc Mariana',
 u'mq': u'Martinique',
 u'mr': u'Mauritania',
 u'ms': u'Montserrat',
 u'mt': u'Malta',
 u'mu': u'Mauritius',
 u'mv': u'Maldives',
 u'mw': u'Malawi',
 u'mx': u'Mexico',
 u'my': u'Malaysia',
 u'mz': u'Mozambique',
 u'na': u'Namibia',
 u'nc': u'T\xe2n Caledonia',
 u'ne': u'Niger',
 u'nf': u'\u0110\u1ea3o Norfolk',
 u'ng': u'Nigeria',
 u'ni': u'Nicaragua',
 u'nl': u'H\xe0 Lan',
 u'no': u'Na Uy',
 u'np': u'Nepal',
 u'nr': u'Nauru',
 u'nu': u'Niue',
 u'nz': u'New Zealand',
 u'om': u'Oman',
 u'pa': u'Panama',
 u'pe': u'Peru',
 u'pf': u'Polynesia thu\u1ed9c Ph\xe1p',
 u'pg': u'Papua New Guinea',
 u'ph': u'Philippines',
 u'pk': u'Pakistan',
 u'pl': u'Ba Lan',
 u'pm': u'Saint Pierre v\xe0 Miquelon',
 u'pn': u'Pitcairn',
 u'pr': u'Puerto Rico',
 u'ps': u'L\xe3nh th\u1ed5 Palestin',
 u'pt': u'B\u1ed3 \u0110\xe0o Nha',
 u'pw': u'Palau',
 u'py': u'Paraguay',
 u'qa': u'Qatar',
 u're': u'Reunion',
 u'ro': u'Rumani',
 u'rs': u'Serbia',
 u'ru': u'Li\xean bang Nga',
 u'rw': u'Rwanda',
 u'sa': u'\u1ea2 R\u1eadp Saudi',
 u'sb': u'Qu\u1ea7n \u0111\u1ea3o Solomon',
 u'sc': u'Seychelles',
 u'sd': u'Sudan',
 u'se': u'Th\u1ee5y \u0110i\u1ec3n',
 u'sg': u'Singapore',
 u'sh': u'Saint Helena',
 u'si': u'Slovenia',
 u'sj': u'Svalbard v\xe0 Jan Mayen',
 u'sk': u'Slovakia',
 u'sl': u'Sierra Leone',
 u'sm': u'San Marino',
 u'sn': u'Senegal',
 u'so': u'Somali',
 u'sr': u'Suriname',
 u'st': u'Sao Tome v\xe0 Principe',
 u'sv': u'El Salvador',
 u'sy': u'Syria',
 u'sz': u'Swaziland',
 u'tc': u'Turks v\xe0 Caicos Islands',
 u'td': u'Chad',
 u'tf': u'C\xe1c L\xe3nh th\u1ed5 Ph\xeda Nam thu\u1ed9c Ph\xe1p',
 u'tg': u'Togo',
 u'th': u'Th\xe1i Lan',
 u'tj': u'Tajikistan',
 u'tk': u'Tokelau',
 u'tl': u'\u0110\xf4ng Timor',
 u'tm': u'Turkmenistan',
 u'tn': u'Tunisia',
 u'to': u'Tonga',
 u'tr': u'Th\u1ed5 Nh\u0129 K\xec',
 u'tt': u'Trinidad v\xe0 Tobago',
 u'tv': u'Tuvalu',
 u'tw': u'\u0110\xe0i Loan',
 u'tz': u'Tanzania',
 u'ua': u'Ucraina',
 u'ug': u'Uganda',
 u'um': u'C\xe1c Ti\u1ec3u \u0111\u1ea3o Xa c\u1ee7a Hoa K\xec',
 u'us': u'Hoa K\xec',
 u'uy': u'Uruguay',
 u'uz': u'Uzbekistan',
 u'va': u'Vatican',
 u'vc': u'Saint Vincent v\xe0 Grenadines',
 u've': u'Venezuela',
 u'vg': u'Qu\u1ea7n \u0111\u1ea3o Virgin thu\u1ed9c Anh',
 u'vi': u'Qu\u1ea7n \u0111\u1ea3o Virgin thu\u1ed9c M\u1ef9',
 u'vn': u'Vi\u1ec7t Nam',
 u'vu': u'Vanuatu',
 u'wf': u'Wallis v\xe0 Futuna',
 u'ws': u'Samoa',
 u'ye': u'Yemen',
 u'yt': u'Mayotte',
 u'za': u'Nam Phi',
 u'zm': u'Zambia',
 u'zw': u'Zimbabwe'}