REGIONS = {u'ad': u'i-Andorra',
 u'ae': u'i-U.A.E.',
 u'af': u'i-Afghanistan',
 u'ag': u'i-Antigua ne-Barbuda',
 u'ai': u'i-Anguilla',
 u'al': u'i-Albania',
 u'am': u'i-Armenia',
 u'an': u'Ama-Antilles we-Netherlands',
 u'ao': u'i-Angola',
 u'aq': u'i-Antarctica',
 u'ar': u'i-Argentina',
 u'as': u'i-American Samoa',
 u'at': u'i-Austria',
 u'au': u'i-Australia',
 u'aw': u'i-Aruba',
 u'ax': u'i-\xc5land Islands',
 u'az': u'i-Azerbaijan',
 u'ba': u'i-Bosnia ne-Herzegovina',
 u'bb': u'i-Barbados',
 u'bd': u'i-Bangladesh',
 u'be': u'i-Belgium',
 u'bf': u'i-Burkina Faso',
 u'bg': u'i-Bulgaria',
 u'bh': u'i-Bahrain',
 u'bi': u'i-Burundi',
 u'bj': u'i-Benin',
 u'bl': u'i-Saint Barth\xe9lemy',
 u'bm': u'i-Bermuda',
 u'bn': u'i-Brunei Darussalam',
 u'bo': u'i-Bolivia',
 u'br': u'i-Brazil',
 u'bs': u'i-Bahamas',
 u'bt': u'i-Bhutan',
 u'bv': u'i-Bouvet Island',
 u'bw': u'i-Botswana',
 u'by': u'i-Belarus',
 u'bz': u'i-Belize',
 u'ca': u'i-Canada',
 u'cc': u'i-Cocos (Keeling) Islands',
 u'cd': u'i-Congo-Kinshasa',
 u'cf': u'i-Central African Republic',
 u'cg': u'i-Congo-Brazzaville',
 u'ch': u'i-Switzerland',
 u'ci': u'i-Ivory Coast',
 u'ck': u'i-Cook Islands',
 u'cl': u'i-Chile',
 u'cm': u'i-Cameroon',
 u'cn': u'i-China',
 u'co': u'i-Colombia',
 u'cr': u'i-Costa Rica',
 u'cu': u'i-Cuba',
 u'cv': u'i-Cape Verde',
 u'cx': u'i-Christmas Island',
 u'cy': u'i-Cyprus',
 u'cz': u'i-Czech Republic',
 u'de': u'i-Germany',
 u'dj': u'i-Djibouti',
 u'dk': u'i-Denmark',
 u'dm': u'i-Dominica',
 u'do': u'i-Dominican Republic',
 u'dz': u'i-Algeria',
 u'ec': u'i-Ecuador',
 u'ee': u'i-Estonia',
 u'eg': u'iGibhithe',
 u'eh': u'i-Western Sahara',
 u'er': u'i-Eritrea',
 u'es': u'i-Spain',
 u'et': u'i-Ethiopia',
 u'fi': u'i-Finland',
 u'fj': u'i-Fiji',
 u'fk': u'i-Falkland Islands (Malvinas)',
 u'fm': u'i-Micronesia',
 u'fo': u'i-Faroe Islands',
 u'fr': u'i-France',
 u'ga': u'i-Gabon',
 u'gb': u'i-United Kingdom',
 u'gd': u'i-Grenada',
 u'ge': u'i-Georgia',
 u'gf': u'i-French Guiana',
 u'gg': u'i-Guensey',
 u'gh': u'i-Ghana',
 u'gi': u'i-Gibraltar',
 u'gl': u'i-Greenland',
 u'gm': u'i-Gambia',
 u'gn': u'i-Guinea',
 u'gp': u'i-Guadeloupe',
 u'gq': u'i-Equatorial Guinea',
 u'gr': u'i-Greece',
 u'gs': u'i-South Georgia ne-South Sandwich Islands',
 u'gt': u'i-Guatemala',
 u'gu': u'i-Guam',
 u'gw': u'i-Guinea-Bissau',
 u'gy': u'i-Guyana',
 u'hk': u'i-Hong Kong',
 u'hm': u'i-Heard Island ne-McDonald Islands',
 u'hn': u'i-Honduras',
 u'hr': u'i-Croatia',
 u'ht': u'i-Haiti',
 u'hu': u'i-Hungary',
 u'id': u'i-Indonesia',
 u'ie': u'i-Ireland',
 u'il': u'i-Israel',
 u'im': u'i-Isle of Man',
 u'in': u'i-India',
 u'io': u'Endaweni yase-Britain Indian Ocean',
 u'iq': u'i-Iraq',
 u'ir': u'i-Iran',
 u'is': u'i-Iceland',
 u'it': u'i-Italy',
 u'je': u'i-Jersey',
 u'jm': u'i-Jamaica',
 u'jo': u'i-Jordan',
 u'jp': u'i-Japan',
 u'ke': u'i-Kenya',
 u'kg': u'i-Kyrgyzstan',
 u'kh': u'i-Cambodia',
 u'ki': u'i-Kiribati',
 u'km': u'i-Comoros',
 u'kn': u'i-Saint Kitts ne-Nevis',
 u'kp': u'i-North Korea',
 u'kr': u'i-South Korea',
 u'kw': u'i-Kuwait',
 u'ky': u'i-Cayman Islands',
 u'kz': u'i-Kazakhstan',
 u'la': u'i-Laos',
 u'lb': u'i-Lebanon',
 u'lc': u'i-Saint Lucia',
 u'li': u'i-Liechtenstein',
 u'lk': u'i-Sri Lanka',
 u'lr': u'i-Liberia',
 u'ls': u'i-Lesotho',
 u'lt': u'i-Lithuania',
 u'lu': u'i-Luxembourg',
 u'lv': u'i-Latvia',
 u'ly': u'i-Libya',
 u'ma': u'i-Morocco',
 u'mc': u'i-Monaco',
 u'md': u'i-Moldova',
 u'me': u'i-Montenegro',
 u'mf': u'i-Saint Martin',
 u'mg': u'i-Madagascar',
 u'mh': u'i-Marshall Island',
 u'mk': u'i-Macedonia, F.Y.R ye',
 u'ml': u'i-Mali',
 u'mm': u'i-Myanmar',
 u'mn': u'i-Mongolia',
 u'mo': u'i-Macao',
 u'mp': u'i-Northern Mariana Islands',
 u'mq': u'i-Martinique',
 u'mr': u'i-Mauritania',
 u'ms': u'i-Montserrat',
 u'mt': u'i-Malta',
 u'mu': u'i-Mauritius',
 u'mv': u'i-Maldives',
 u'mw': u'i-Malawi',
 u'mx': u'i-Mexico',
 u'my': u'i-Malaysia',
 u'mz': u'i-Mozambique',
 u'na': u'i-Namibia',
 u'nc': u'i-New Caledonia',
 u'ne': u'i-Niger',
 u'nf': u'i-Norfolk Island',
 u'ng': u'i-Nigeria',
 u'ni': u'i-Nicaragua',
 u'nl': u'i-Netherlands',
 u'no': u'i-Norway',
 u'np': u'i-Nepal',
 u'nr': u'i-Nauru',
 u'nu': u'i-Niue',
 u'nz': u'i-New Zealand',
 u'om': u'i-Oman',
 u'pa': u'i-Panama',
 u'pe': u'i-Peru',
 u'pf': u'i-French Polynesia',
 u'pg': u'i-Papua New Guinea',
 u'ph': u'i-Philippines',
 u'pk': u'i-Pakistan',
 u'pl': u'i-Poland',
 u'pm': u'i-Saint Pierre nase Miquelon',
 u'pn': u'i-Pitcairn',
 u'pr': u'i-Puerto Rico',
 u'ps': u'Indawo okuhlezwi kuyo yase-Phalestina',
 u'pt': u'i-Portugal',
 u'pw': u'i-Palau',
 u'py': u'i-Paraguay',
 u'qa': u'i-Qatar',
 u're': u'i-Reunion',
 u'ro': u'i-Romania',
 u'rs': u'i-Serbia',
 u'ru': u'i-Russian Federation',
 u'rw': u'i-Rwanda',
 u'sa': u'i-Saudi Arabia',
 u'sb': u'i-Solomon Islands',
 u'sc': u'i-Sychelles',
 u'sd': u'i-Sudan',
 u'se': u'i-Sweden',
 u'sg': u'i-Singapore',
 u'sh': u'i-Saint Helena',
 u'si': u'i-Slovenia',
 u'sj': u'i-Svalbard ne-Jan Mayen',
 u'sk': u'i-Slovaki',
 u'sl': u'i-Sierra Leone',
 u'sm': u'i-San Marino',
 u'sn': u'i-Senegal',
 u'so': u'i-Somalia',
 u'sr': u'i-Suriname',
 u'st': u'i-Sao Tome ne-Principe',
 u'sv': u'i-El Salvador',
 u'sy': u'i-Syria',
 u'sz': u'i-Swaziland',
 u'tc': u'i-Turks ne-Caicos Islands',
 u'td': u'i-Chad',
 u'tf': u'Ezindaweni ze-Fulansi eseningizimu',
 u'tg': u'i-Togo',
 u'th': u'i-Thailand',
 u'tj': u'i-Tajikistan',
 u'tk': u'i-Tokelau',
 u'tl': u'i-Timor-Leste',
 u'tm': u'i-Turkmenistan',
 u'tn': u'i-Tunisia',
 u'to': u'i-Tonga',
 u'tr': u'i-Turkey',
 u'tt': u'i-Trinidad ne-Tobago',
 u'tv': u'i-Tuvalu',
 u'tw': u'i-Taiwan',
 u'tz': u'i-Tanzania',
 u'ua': u'i-Ukraine',
 u'ug': u'i-Uganda',
 u'um': u'i-United States Minor Outlying Islands',
 u'us': u'i-United States',
 u'uy': u'i-Uruguay',
 u'uz': u'i-Uzbekistan',
 u'va': u'i-Vatican City',
 u'vc': u'i-Saint Vincent ne-Grenadines',
 u've': u'i-Venezuela',
 u'vg': u'i-British Virgin Islands',
 u'vi': u'i-U.S. Virgin Islands',
 u'vn': u'i-Vietnam',
 u'vu': u'i-Vanuatu',
 u'wf': u'i-Wallis ne-Futuna',
 u'ws': u'i-Samoa',
 u'ye': u'i-Yemen',
 u'yt': u'i-Mayotte',
 u'za': u'i-Ningizimu Afrika',
 u'zm': u'i-Zambia',
 u'zw': u'i-Zimbabwe'}