# -*- coding: utf8 -*-
# List of valid country codes: http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
COUNTRIES = [
    'AFG', 'ALA', 'ALB', 'DZA', 'ASM', 'AND', 'AGO', 'AIA', 'ATA', 'ATG',
    'ARG', 'ARM', 'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB',
    'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES', 'BIH', 'BWA',
    'BVT', 'BRA', 'IOT', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM', 'CMR', 'CAN',
    'CPV', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'CXR', 'CCK', 'COL', 'COM',
    'COG', 'COD', 'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE',
    'DNK', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI', 'EST',
    'ETH', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA', 'GUF', 'PYF', 'ATF', 'GAB',
    'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC', 'GRL', 'GRD', 'GLP', 'GUM',
    'GTM', 'GGY', 'GIN', 'GNB', 'GUY', 'HTI', 'HMD', 'VAT', 'HND', 'HKG',
    'HUN', 'ISL', 'IND', 'IDN', 'IRQ', 'IRL', 'IMN', 'ISR', 'ITA',  # IRN
    'JAM', 'JPN', 'JEY', 'JOR', 'KAZ', 'KEN', 'KIR', 'KOR', 'KOS',  # PRK
    'KWT', 'KGZ', 'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU',
    'LUX', 'MAC', 'MKD', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MHL',
    'MTQ', 'MRT', 'MUS', 'MYT', 'MEX', 'FSM', 'MDA', 'MCO', 'MNG', 'MNE',
    'MSR', 'MAR', 'MOZ', 'MMR', 'NAM', 'NRU', 'NPL', 'NLD', 'NCL', 'NZL',
    'NIC', 'NER', 'NGA', 'NIU', 'NFK', 'MNP', 'NOR', 'OMN', 'PAK', 'PLW',
    'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'PCN', 'POL', 'PRT', 'PRI',
    'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'BLM', 'SHN', 'KNA', 'LCA', 'MAF',
    'SPM', 'VCT', 'WSM', 'SMR', 'STP', 'SAU', 'SEN', 'SRB', 'SCG', 'SYC',
    'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB', 'SOM', 'ZAF', 'SGS', 'SSD',
    'ESP', 'LKA', 'SDN', 'SUR', 'SJM', 'SWZ', 'SWE', 'CHE', 'SYR', 'TWN',
    'TJK', 'TZA', 'THA', 'TLS', 'TGO', 'TKL', 'TON', 'TTO', 'TUN', 'TUR',
    'TKM', 'TCA', 'TUV', 'UGA', 'UKR', 'ARE', 'GBR', 'USA', 'UMI', 'URY',
    'UZB', 'VUT', 'VEN', 'VNM', 'VGB', 'VIR', 'WLF', 'ESH', 'YEM', 'ZMB',
    'ZWE',
]

COUNTRY_DETAILS = {
    'ARG': {
        'adolescent': True,
        'default_currency': 'ARS',
        'id': 20,
        'mcc': 722,
        'name': 'Argentina',
        'ratingsbody': 'ESRB',
        'slug': 'ar',
        'special': False,
        'weight': 0
    },
    'BGD': {
        'adolescent': True,
        'default_currency': 'BDT',
        'id': 31,
        'mcc': 470,
        'name': 'Bangladesh',
        'ratingsbody': None,
        'slug': 'bd',
        'special': False,
        'weight': 0
    },
    'BRA': {
        'adolescent': False,
        'default_currency': 'BRL',
        'id': 7,
        'mcc': 724,
        'name': 'Brazil',
        'ratingsbody': 'CLASSIND',
        'slug': 'br',
        'special': False,
        'weight': 0
    },
    'BWA': {
        'adolescent': True,
        'default_currency': 'BWP',
        'id': 45,
        'mcc': 652,
        'name': 'Botswana',
        'slug': 'bw',
        'special': False,
        'weight': 0
    },
    'CHL': {
        'adolescent': True,
        'default_currency': 'CLP',
        'id': 23,
        'mcc': 730,
        'name': 'Chile',
        'ratingsbody': 'ESRB',
        'slug': 'cl',
        'special': False,
        'weight': 0
    },
    'CHN': {
        'adolescent': True,
        'default_currency': 'CNY',
        'id': 21,
        'mcc': 460,
        'name': 'China',
        'ratingsbody': None,
        'slug': 'cn',
        'special': True,
        'weight': 0
    },
    'CIV': {
        'adolescent': True,
        'default_currency': 'XOF',
        'id': 40,
        'mcc': 612,
        'name': u"Côte d'Ivoire",
        'slug': 'ci',
        'special': False,
        'weight': 0
    },
    'CMR': {
        'adolescent': True,
        'default_currency': 'COP',
        'id': 42,
        'mcc': 624,
        'name': 'Cameroon',
        'slug': 'cm',
        'special': False,
        'weight': 0
    },
    'COL': {
        'adolescent': False,
        'default_currency': 'COP',
        'id': 9,
        'mcc': 732,
        'name': 'Colombia',
        'ratingsbody': 'ESRB',
        'slug': 'co',
        'special': False,
        'weight': 0
    },
    'CRI': {
        'adolescent': True,
        'default_currency': 'CRC',
        'id': 27,
        'mcc': 712,
        'name': 'Costa Rica',
        'ratingsbody': 'ESRB',
        'slug': 'cr',
        'special': False,
        'weight': 0
    },
    'CZE': {
        'adolescent': True,
        'default_currency': 'CZK',
        'id': 34,
        'name': 'Czech Republic',
        'mcc': 230,
        'slug': 'cz',
        'special': False,
        'weight': 0
    },
    'DEU': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 14,
        'mcc': 262,
        'name': 'Germany',
        'ratingsbody': 'USK',
        'slug': 'de',
        'special': False,
        'weight': 0
    },
    'ECU': {
        'adolescent': True,
        'default_currency': 'USD',
        'id': 26,
        'mcc': 740,
        'name': 'Ecuador',
        'ratingsbody': 'ESRB',
        'slug': 'ec',
        'special': False,
        'weight': 0
    },
    'EGY': {
        'adolescent': True,
        'default_currency': 'EGP',
        'id': 43,
        'mcc': 602,
        'name': 'Egypt',
        'slug': 'eg',
        'special': False,
        'weight': 0
    },
    'ESP': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 8,
        'mcc': 214,
        'name': 'Spain',
        'ratingsbody': 'PEGI',
        'slug': 'es',
        'special': False,
        'weight': 0
    },
    'FRA': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 30,
        'mcc': 208,
        'name': 'France',
        'ratingsbody': 'PEGI',
        'slug': 'fr',
        'special': False,
        'weight': 0
    },
    'GBR': {
        'adolescent': True,
        'default_currency': 'GBP',
        'id': 4,
        'mcc': 235,
        'name': 'United Kingdom',
        'ratingsbody': 'PEGI',
        'slug': 'uk',
        'special': False,
        'weight': 0
    },
    'GNB': {
        'adolescent': True,
        'default_currency': 'XOF',
        'id': 46,
        'mcc': 632,
        'name': 'Guinea-Bissau',
        'slug': 'gw',
        'special': False,
        'weight': 0
    },
    'GRC': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 17,
        'mcc': 202,
        'name': 'Greece',
        'ratingsbody': 'PEGI',
        'slug': 'gr',
        'special': False,
        'weight': 0
    },
    'GTM': {
        'adolescent': True,
        'default_currency': 'GTQ',
        'id': 25,
        'mcc': 704,
        'name': 'Guatemala',
        'ratingsbody': 'ESRB',
        'slug': 'gt',
        'special': False,
        'weight': 0
    },
    'HUN': {
        'adolescent': True,
        'default_currency': 'HUF',
        'id': 13,
        'mcc': 216,
        'name': 'Hungary',
        'ratingsbody': 'PEGI',
        'slug': 'hu',
        'special': False,
        'weight': 0
    },
    'IND': {
        'adolescent': True,
        'default_currency': 'INR',
        'id': 32,
        'low_memory': True,
        'mcc': 405,
        'name': 'India',
        'ratingsbody': None,
        'slug': 'in',
        'weight': 0
    },
    'ITA': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 22,
        'mcc': 222,
        'name': 'Italy',
        'ratingsbody': 'PEGI',
        'slug': 'it',
        'special': False,
        'weight': 0
    },
    'JOR': {
        'adolescent': True,
        'default_currency': 'JOD',
        'id': 51,
        'mcc': 416,
        'name': 'Jordan',
        'slug': 'jo',
        'special': False,
        'weight': 0
    },
    'JPN': {
        'adolescent': True,
        'default_currency': 'JPY',
        'id': 33,
        'mcc': 440,
        'name': 'Japan',
        'slug': 'jp',
        'special': False,
        'weight': 0
    },
    'LTU': {
        'adolescent': True,
        'default_currency': 'LTL',
        'id': 38,
        'mcc': 370,
        'name': 'Lithuania',
        'slug': 'lt',
        'special': False,
        'weight': 0
    },
    'MDG': {
        'adolescent': True,
        'default_currency': 'MGA',
        'id': 49,
        'mcc': 646,
        'name': 'Madagascar',
        'slug': 'mg',
        'special': False,
        'weight': 0
    },
    'MEX': {
        'adolescent': False,
        'default_currency': 'MXN',
        'id': 12,
        'mcc': 334,
        'name': 'Mexico',
        'ratingsbody': 'ESRB',
        'slug': 'mx',
        'special': False,
        'weight': 0
    },
    'MLI': {
        'adolescent': True,
        'default_currency': 'XOF',
        'id': 48,
        'mcc': 610,
        'name': 'Mali',
        'slug': 'ml',
        'special': False,
        'weight': 0
    },
    'MMR': {
        'adolescent': True,
        'default_currency': 'MMK',
        'id': 53,
        'mcc': 414,
        'name': 'Myanmar',
        'slug': 'mm',
        'special': False,
        'weight': 0
    },
    'MNE': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 15,
        'mcc': 297,
        'name': 'Montenegro',
        'ratingsbody': 'PEGI',
        'slug': 'me',
        'special': False,
        'weight': 0
    },
    'MUS': {
        'adolescent': True,
        'default_currency': 'MUR',
        'id': 50,
        'mcc': 617,
        'name': 'Mauritius',
        'slug': 'mu',
        'special': False,
        'weight': 0
    },
    'NER': {
        'adolescent': True,
        'default_currency': 'XOF',
        'id': 52,
        'mcc': 614,
        'name': 'Niger',
        'slug': 'ne',
        'special': False,
        'weight': 0
    },
    'NIC': {
        'adolescent': True,
        'default_currency': 'NIO',
        'id': 29,
        'mcc': 710,
        'name': 'Nicaragua',
        'ratingsbody': 'ESRB',
        'slug': 'ni',
        'special': False,
        'weight': 0
    },
    'PAN': {
        'adolescent': True,
        'default_currency': 'USD',
        'id': 28,
        'mcc': 714,
        'name': 'Panama',
        'ratingsbody': 'ESRB',
        'slug': 'pa',
        'special': False,
        'weight': 0
    },
    'PER': {
        'adolescent': False,
        'default_currency': 'PEN',
        'id': 18,
        'mcc': 716,
        'name': 'Peru',
        'ratingsbody': 'ESRB',
        'slug': 'pe',
        'special': False,
        'weight': 0
    },
    'PHL': {
        'adolescent': True,
        'default_currency': 'PHP',
        'id': 35,
        'low_memory': True,
        'mcc': 515,
        'name': 'Philippines',
        'ratingsbody': None,
        'slug': 'ph',
        'weight': 0
    },
    'POL': {
        'adolescent': True,
        'default_currency': 'PLN',
        'id': 11,
        'mcc': 260,
        'name': 'Poland',
        'ratingsbody': 'PEGI',
        'slug': 'pl',
        'special': False,
        'weight': 0
    },
    'RUS': {
        'adolescent': True,
        'default_currency': 'EUR',
        'id': 36,
        'mcc': 250,
        'name': 'Russia',
        'slug': 'ru',
        'special': False,
        'weight': 0
    },
    'SLV': {
        'adolescent': True,
        'default_currency': 'USD',
        'id': 24,
        'mcc': 706,
        'name': 'El Salvador',
        'ratingsbody': 'ESRB',
        'slug': 'sv',
        'special': False,
        'weight': 0
    },
    'SEN': {
        'adolescent': True,
        'default_currency': 'XOF',
        'id': 41,
        'mcc': 608,
        'name': 'Senegal',
        'slug': 'sn',
        'special': False,
        'weight': 0
    },
    'SRB': {
        'adolescent': True,
        'default_currency': 'RSD',
        'id': 16,
        'mcc': 220,
        'name': 'Serbia',
        'ratingsbody': 'PEGI',
        'slug': 'rs',
        'special': False,
        'weight': 0
    },
    'TUN': {
        'adolescent': True,
        'default_currency': 'TND',
        'id': 39,
        'mcc': 605,
        'name': 'Tunisia',
        'slug': 'tn',
        'special': False,
        'weight': 0
    },
    'TZA': {
        'adolescent': True,
        'default_currency': 'TZS',
        'id': 44,
        'mcc': 640,
        'name': 'Tanzania',
        'slug': 'tz',
        'special': False,
        'weight': 0
    },
    'URY': {
        'adolescent': False,
        'default_currency': 'UYU',
        'id': 19,
        'mcc': 748,
        'name': 'Uruguay',
        'ratingsbody': 'ESRB',
        'slug': 'uy',
        'special': False,
        'weight': 0
    },
    'USA': {
        'adolescent': True,
        'default_currency': 'USD',
        'id': 2,
        'mcc': 310,
        'name': 'United States',
        'ratingsbody': 'ESRB',
        'slug': 'us',
        'special': False,
        'weight': 1
    },
    'VEN': {
        'adolescent': False,
        'default_currency': 'USD',
        'id': 10,
        'mcc': 734,
        'name': 'Venezuela',
        'ratingsbody': 'ESRB',
        'slug': 've',
        'special': False,
        'weight': 0
    },
    'VUT': {
        'adolescent': True,
        'default_currency': 'USD',
        'id': 47,
        'mcc': 541,
        'name': 'Vanuatu',
        'slug': 'vu',
        'special': False,
        'weight': 0
    },
    'ZAF': {
        'adolescent': False,
        'default_currency': 'ZAR',
        'id': 37,
        'mcc': 655,
        'name': 'South Africa',
        'ratingsbody': None,
        'slug': 'za',
        'special': False,
        'weight': 0
    },
}
