# List of valid country codes: http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
COUNTRIES = [
    'AFG', 'ALA', 'ALB', 'DZA', 'ASM', 'AND', 'AGO', 'AIA', 'ATA', 'ATG',
    'ARG', 'ARM', 'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB',
    'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES', 'BIH', 'BWA',
    'BVT', 'BRA', 'IOT', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM', 'CMR', 'CAN',
    'CPV', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'CXR', 'CCK', 'COL', 'COM',
    'COG', 'COD', 'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE',
    'DNK', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI', 'EST',
    'ETH', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA', 'GUF', 'PYF', 'ATF', 'GAB',
    'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC', 'GRL', 'GRD', 'GLP', 'GUM',
    'GTM', 'GGY', 'GIN', 'GNB', 'GUY', 'HTI', 'HMD', 'VAT', 'HND', 'HKG',
    'HUN', 'ISL', 'IND', 'IDN', 'IRQ', 'IRL', 'IMN', 'ISR', 'ITA', 'IRN',
    'JAM', 'JPN', 'JEY', 'JOR', 'KAZ', 'KEN', 'KIR', 'KOR', 'PRK',
    'KWT', 'KGZ', 'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU',
    'LUX', 'MAC', 'MKD', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MHL',
    'MTQ', 'MRT', 'MUS', 'MYT', 'MEX', 'FSM', 'MDA', 'MCO', 'MNG', 'MNE',
    'MSR', 'MAR', 'MOZ', 'MMR', 'NAM', 'NRU', 'NPL', 'NLD', 'NCL', 'NZL',
    'NIC', 'NER', 'NGA', 'NIU', 'NFK', 'MNP', 'NOR', 'OMN', 'PAK', 'PLW',
    'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'PCN', 'POL', 'PRT', 'PRI',
    'QAT', 'REU', 'ROU', 'RUS', 'RWA', 'BLM', 'SHN', 'KNA', 'LCA', 'MAF',
    'SPM', 'VCT', 'WSM', 'SMR', 'STP', 'SAU', 'SEN', 'SRB', 'SYC',
    'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB', 'SOM', 'ZAF', 'SGS', 'SSD',
    'ESP', 'LKA', 'SDN', 'SUR', 'SJM', 'SWZ', 'SWE', 'CHE', 'SYR', 'TWN',
    'TJK', 'TZA', 'THA', 'TLS', 'TGO', 'TKL', 'TON', 'TTO', 'TUN', 'TUR',
    'TKM', 'TCA', 'TUV', 'UGA', 'UKR', 'ARE', 'GBR', 'USA', 'UMI', 'URY',
    'UZB', 'VUT', 'VEN', 'VNM', 'VGB', 'VIR', 'WLF', 'ESH', 'YEM', 'ZMB',
    'ZWE',
]

COUNTRY_DETAILS = {
    'ABW': {
       'adolescent': False,
        'default_currency': u'AWG',
        'default_language': 'en',
        'id': 37,
        'mcc': [363],
        'name': u'Aruba',
        'ratingsbody': None,
        'slug': 'aw',
        'special': False,
        'weight': 0
    },
    'AFG': {
       'adolescent': False,
        'default_currency': u'AFN',
        'default_language': 'en',
        'id': 37,
        'mcc': [412],
        'name': u'Afghanistan',
        'ratingsbody': None,
        'slug': 'af',
        'special': False,
        'weight': 0
    },
    'AGO': {
       'adolescent': False,
        'default_currency': u'AOA',
        'default_language': 'en',
        'id': 37,
        'mcc': [631],
        'name': u'Angola',
        'ratingsbody': None,
        'slug': 'ao',
        'special': False,
        'weight': 0
    },
    'AIA': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [365],
        'name': u'Anguilla',
        'ratingsbody': None,
        'slug': 'ai',
        'special': False,
        'weight': 0
    },
    'ALA': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [244],
        'name': u'\xc5land Islands',
        'ratingsbody': None,
        'slug': 'ax',
        'special': False,
        'weight': 0
    },
    'ALB': {
       'adolescent': False,
        'default_currency': u'ALL',
        'default_language': 'en',
        'id': 37,
        'mcc': [276],
        'name': u'Albania',
        'ratingsbody': None,
        'slug': 'al',
        'special': False,
        'weight': 0
    },
    'AND': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [213],
        'name': u'Andorra',
        'ratingsbody': None,
        'slug': 'ad',
        'special': False,
        'weight': 0
    },
    'ARE': {
       'adolescent': False,
        'default_currency': u'AED',
        'default_language': 'en',
        'id': 37,
        'mcc': [424],
        'name': u'United Arab Emirates',
        'ratingsbody': None,
        'slug': 'ae',
        'special': False,
        'weight': 0
    },
    'ARG': {
       'adolescent': True,
        'default_currency': 'ARS',
        'default_language': 'es',
        'id': 20,
        'mcc': [722],
        'name': 'Argentina',
        'ratingsbody': 'ESRB',
        'slug': 'ar',
        'special': False,
        'weight': 0
    },
    'ARM': {
       'adolescent': False,
        'default_currency': u'AMD',
        'default_language': 'en',
        'id': 37,
        'mcc': [283],
        'name': u'Armenia',
        'ratingsbody': None,
        'slug': 'am',
        'special': False,
        'weight': 0
    },
    'ASM': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [544],
        'name': u'American Samoa',
        'ratingsbody': None,
        'slug': 'as',
        'special': False,
        'weight': 0
    },
    'ATA': {
       'adolescent': False,
        'default_currency': u'',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Antarctica',
        'ratingsbody': None,
        'slug': 'aq',
        'special': False,
        'weight': 0
    },
    'ATF': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'French Southern Territories',
        'ratingsbody': None,
        'slug': 'tf',
        'special': False,
        'weight': 0
    },
    'ATG': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [344],
        'name': u'Antigua and Barbuda',
        'ratingsbody': None,
        'slug': 'ag',
        'special': False,
        'weight': 0
    },
    'AUS': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [505],
        'name': u'Australia',
        'ratingsbody': None,
        'slug': 'au',
        'special': False,
        'weight': 0
    },
    'AUT': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [232],
        'name': u'Austria',
        'ratingsbody': None,
        'slug': 'at',
        'special': False,
        'weight': 0
    },
    'AZE': {
       'adolescent': False,
        'default_currency': u'AZN',
        'default_language': 'en',
        'id': 37,
        'mcc': [400],
        'name': u'Azerbaijan',
        'ratingsbody': None,
        'slug': 'az',
        'special': False,
        'weight': 0
    },
    'BDI': {
       'adolescent': False,
        'default_currency': u'BIF',
        'default_language': 'en',
        'id': 37,
        'mcc': [642],
        'name': u'Burundi',
        'ratingsbody': None,
        'slug': 'bi',
        'special': False,
        'weight': 0
    },
    'BEL': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [206],
        'name': u'Belgium',
        'ratingsbody': None,
        'slug': 'be',
        'special': False,
        'weight': 0
    },
    'BEN': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [616],
        'name': u'Benin',
        'ratingsbody': None,
        'slug': 'bj',
        'special': False,
        'weight': 0
    },
    'BES': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [362],
        'name': u'Bonaire, Sint Eustatius and Saba',
        'ratingsbody': None,
        'slug': 'bq',
        'special': False,
        'weight': 0
    },
    'BFA': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [613],
        'name': u'Burkina Faso',
        'ratingsbody': None,
        'slug': 'bf',
        'special': False,
        'weight': 0
    },
    'BGD': {
       'adolescent': True,
        'default_currency': 'BDT',
        'default_language': 'en',
        'id': 31,
        'mcc': [470],
        'name': 'Bangladesh',
        'ratingsbody': None,
        'slug': 'bd',
        'special': False,
        'weight': 0
    },
    'BGR': {
       'adolescent': False,
        'default_currency': u'BGN',
        'default_language': 'en',
        'id': 37,
        'mcc': [284],
        'name': u'Bulgaria',
        'ratingsbody': None,
        'slug': 'bg',
        'special': False,
        'weight': 0
    },
    'BHR': {
       'adolescent': False,
        'default_currency': u'BHD',
        'default_language': 'en',
        'id': 37,
        'mcc': [426],
        'name': u'Bahrain',
        'ratingsbody': None,
        'slug': 'bh',
        'special': False,
        'weight': 0
    },
    'BHS': {
       'adolescent': False,
        'default_currency': u'BSD',
        'default_language': 'en',
        'id': 37,
        'mcc': [364],
        'name': u'Bahamas',
        'ratingsbody': None,
        'slug': 'bs',
        'special': False,
        'weight': 0
    },
    'BIH': {
       'adolescent': False,
        'default_currency': u'BAM',
        'default_language': 'en',
        'id': 37,
        'mcc': [218],
        'name': u'Bosnia and Herzegovina',
        'ratingsbody': None,
        'slug': 'ba',
        'special': False,
        'weight': 0
    },
    'BLM': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Saint Barth\xe9lemy',
        'ratingsbody': None,
        'slug': 'bl',
        'special': False,
        'weight': 0
    },
    'BLR': {
       'adolescent': False,
        'default_currency': u'BYR',
        'default_language': 'en',
        'id': 37,
        'mcc': [257],
        'name': u'Belarus',
        'ratingsbody': None,
        'slug': 'by',
        'special': False,
        'weight': 0
    },
    'BLZ': {
       'adolescent': False,
        'default_currency': u'BZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [702],
        'name': u'Belize',
        'ratingsbody': None,
        'slug': 'bz',
        'special': False,
        'weight': 0
    },
    'BMU': {
       'adolescent': False,
        'default_currency': u'BMD',
        'default_language': 'en',
        'id': 37,
        'mcc': [350, 338, 310],
        'name': u'Bermuda',
        'ratingsbody': None,
        'slug': 'bm',
        'special': False,
        'weight': 0
    },
    'BOL': {
       'adolescent': False,
        'default_currency': u'BOB',
        'default_language': 'en',
        'id': 37,
        'mcc': [736],
        'name': u'Bolivia, Plurinational State of',
        'ratingsbody': None,
        'slug': 'bo',
        'special': False,
        'weight': 0
    },
    'BRA': {
       'adolescent': False,
        'default_currency': 'BRL',
        'default_language': 'pt-BR',
        'id': 7,
        'mcc': [724],
        'name': 'Brazil',
        'ratingsbody': 'CLASSIND',
        'slug': 'br',
        'special': False,
        'weight': 0
    },
    'BRB': {
       'adolescent': False,
        'default_currency': u'BBD',
        'default_language': 'en',
        'id': 37,
        'mcc': [342],
        'name': u'Barbados',
        'ratingsbody': None,
        'slug': 'bb',
        'special': False,
        'weight': 0
    },
    'BRN': {
       'adolescent': False,
        'default_currency': u'BND',
        'default_language': 'en',
        'id': 37,
        'mcc': [528],
        'name': u'Brunei Darussalam',
        'ratingsbody': None,
        'slug': 'bn',
        'special': False,
        'weight': 0
    },
    'BTN': {
       'adolescent': False,
        'default_currency': u'INR',
        'default_language': 'en',
        'id': 37,
        'mcc': [402],
        'name': u'Bhutan',
        'ratingsbody': None,
        'slug': 'bt',
        'special': False,
        'weight': 0
    },
    'BVT': {
       'adolescent': False,
        'default_currency': u'NOK',
        'default_language': 'en',
        'id': 37,
        'mcc': [242],
        'name': u'Bouvet Island',
        'ratingsbody': None,
        'slug': 'bv',
        'special': False,
        'weight': 0
    },
    'BWA': {
       'adolescent': False,
        'default_currency': u'BWP',
        'default_language': 'en',
        'id': 37,
        'mcc': [652],
        'name': u'Botswana',
        'ratingsbody': None,
        'slug': 'bw',
        'special': False,
        'weight': 0
    },
    'CAF': {
       'adolescent': False,
        'default_currency': u'XAF',
        'default_language': 'en',
        'id': 37,
        'mcc': [623],
        'name': u'Central African Republic',
        'ratingsbody': None,
        'slug': 'cf',
        'special': False,
        'weight': 0
    },
    'CAN': {
       'adolescent': False,
        'default_currency': u'CAD',
        'default_language': 'en',
        'id': 37,
        'mcc': [302],
        'name': u'Canada',
        'ratingsbody': None,
        'slug': 'ca',
        'special': False,
        'weight': 0
    },
    'CCK': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Cocos (Keeling) Islands',
        'ratingsbody': None,
        'slug': 'cc',
        'special': False,
        'weight': 0
    },
    'CHE': {
       'adolescent': False,
        'default_currency': u'CHF',
        'default_language': 'en',
        'id': 37,
        'mcc': [228],
        'name': u'Switzerland',
        'ratingsbody': None,
        'slug': 'ch',
        'special': False,
        'weight': 0
    },
    'CHL': {
       'adolescent': True,
        'default_currency': 'CLP',
        'default_language': 'es',
        'id': 23,
        'mcc': [730],
        'name': 'Chile',
        'ratingsbody': 'ESRB',
        'slug': 'cl',
        'special': False,
        'weight': 0
    },
    'CHN': {
       'adolescent': True,
        'default_currency': 'RMB',
        'default_language': 'zh-CN',
        'id': 21,
        'mcc': [460],
        'name': 'China',
        'ratingsbody': None,
        'slug': 'cn',
        'special': True,
        'weight': 0
    },
    'CIV': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [612],
        'name': u"C\xf4te d'Ivoire",
        'ratingsbody': None,
        'slug': 'ci',
        'special': False,
        'weight': 0
    },
    'CMR': {
       'adolescent': False,
        'default_currency': u'XAF',
        'default_language': 'en',
        'id': 37,
        'mcc': [624],
        'name': u'Cameroon',
        'ratingsbody': None,
        'slug': 'cm',
        'special': False,
        'weight': 0
    },
    'COD': {
       'adolescent': False,
        'default_currency': u'',
        'default_language': 'en',
        'id': 37,
        'mcc': [630],
        'name': u'Congo, Democratic Republic of the',
        'ratingsbody': None,
        'slug': 'cd',
        'special': False,
        'weight': 0
    },
    'COG': {
       'adolescent': False,
        'default_currency': u'XAF',
        'default_language': 'en',
        'id': 37,
        'mcc': [629],
        'name': u'Congo',
        'ratingsbody': None,
        'slug': 'cg',
        'special': False,
        'weight': 0
    },
    'COK': {
       'adolescent': False,
        'default_currency': u'NZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [548],
        'name': u'Cook Islands',
        'ratingsbody': None,
        'slug': 'ck',
        'special': False,
        'weight': 0
    },
    'COL': {
       'adolescent': False,
        'default_currency': 'COP',
        'default_language': 'es',
        'id': 9,
        'mcc': [732],
        'name': 'Colombia',
        'ratingsbody': 'ESRB',
        'slug': 'co',
        'special': False,
        'weight': 0
    },
    'COM': {
       'adolescent': False,
        'default_currency': u'KMF',
        'default_language': 'en',
        'id': 37,
        'mcc': [654],
        'name': u'Comoros',
        'ratingsbody': None,
        'slug': 'km',
        'special': False,
        'weight': 0
    },
    'CPV': {
       'adolescent': False,
        'default_currency': u'CVE',
        'default_language': 'en',
        'id': 37,
        'mcc': [625],
        'name': u'Cabo Verde',
        'ratingsbody': None,
        'slug': 'cv',
        'special': False,
        'weight': 0
    },
    'CRI': {
       'adolescent': True,
        'default_currency': 'CRC',
        'default_language': 'es',
        'id': 27,
        'mcc': [712],
        'name': 'Costa Rica',
        'ratingsbody': 'ESRB',
        'slug': 'cr',
        'special': False,
        'weight': 0
    },
    'CUB': {
       'adolescent': False,
        'default_currency': u'CUP',
        'default_language': 'en',
        'id': 37,
        'mcc': [368],
        'name': u'Cuba',
        'ratingsbody': None,
        'slug': 'cu',
        'special': False,
        'weight': 0
    },
    'CUW': {
       'adolescent': False,
        'default_currency': u'ANG',
        'default_language': 'en',
        'id': 37,
        'mcc': [362],
        'name': u'Cura\xe7ao',
        'ratingsbody': None,
        'slug': 'cw',
        'special': False,
        'weight': 0
    },
    'CXR': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Christmas Island',
        'ratingsbody': None,
        'slug': 'cx',
        'special': False,
        'weight': 0
    },
    'CYM': {
       'adolescent': False,
        'default_currency': u'KYD',
        'default_language': 'en',
        'id': 37,
        'mcc': [346],
        'name': u'Cayman Islands',
        'ratingsbody': None,
        'slug': 'ky',
        'special': False,
        'weight': 0
    },
    'CYP': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [280],
        'name': u'Cyprus',
        'ratingsbody': None,
        'slug': 'cy',
        'special': False,
        'weight': 0
    },
    'CZE': {
       'adolescent': True,
        'default_currency': 'CZK',
        'default_language': 'cs',
        'id': 34,
        'mcc': [230],
        'name': 'Czech Republic',
        'slug': 'cz',
        'special': False,
        'weight': 0
    },
    'DEU': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'de',
        'id': 14,
        'mcc': [262],
        'name': 'Germany',
        'ratingsbody': 'USK',
        'slug': 'de',
        'special': False,
        'weight': 0
    },
    'DJI': {
       'adolescent': False,
        'default_currency': u'DJF',
        'default_language': 'en',
        'id': 37,
        'mcc': [638],
        'name': u'Djibouti',
        'ratingsbody': None,
        'slug': 'dj',
        'special': False,
        'weight': 0
    },
    'DMA': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [366],
        'name': u'Dominica',
        'ratingsbody': None,
        'slug': 'dm',
        'special': False,
        'weight': 0
    },
    'DNK': {
       'adolescent': False,
        'default_currency': u'DKK',
        'default_language': 'en',
        'id': 37,
        'mcc': [238],
        'name': u'Denmark',
        'ratingsbody': None,
        'slug': 'dk',
        'special': False,
        'weight': 0
    },
    'DOM': {
       'adolescent': False,
        'default_currency': u'DOP',
        'default_language': 'en',
        'id': 37,
        'mcc': [370],
        'name': u'Dominican Republic',
        'ratingsbody': None,
        'slug': 'do',
        'special': False,
        'weight': 0
    },
    'DZA': {
       'adolescent': False,
        'default_currency': u'DZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [603],
        'name': u'Algeria',
        'ratingsbody': None,
        'slug': 'dz',
        'special': False,
        'weight': 0
    },
    'ECU': {
       'adolescent': True,
        'default_currency': 'USD',
        'default_language': 'es',
        'id': 26,
        'mcc': [740],
        'name': 'Ecuador',
        'ratingsbody': 'ESRB',
        'slug': 'ec',
        'special': False,
        'weight': 0
    },
    'EGY': {
       'adolescent': False,
        'default_currency': u'EGP',
        'default_language': 'en',
        'id': 37,
        'mcc': [602],
        'name': u'Egypt',
        'ratingsbody': None,
        'slug': 'eg',
        'special': False,
        'weight': 0
    },
    'ERI': {
       'adolescent': False,
        'default_currency': u'ERN',
        'default_language': 'en',
        'id': 37,
        'mcc': [657],
        'name': u'Eritrea',
        'ratingsbody': None,
        'slug': 'er',
        'special': False,
        'weight': 0
    },
    'ESH': {
       'adolescent': False,
        'default_currency': u'MAD',
        'default_language': 'en',
        'id': 37,
        'mcc': [604],
        'name': u'Western Sahara',
        'ratingsbody': None,
        'slug': 'eh',
        'special': False,
        'weight': 0
    },
    'ESP': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'es',
        'id': 8,
        'mcc': [214],
        'name': 'Spain',
        'ratingsbody': 'PEGI',
        'slug': 'es',
        'special': False,
        'weight': 0
    },
    'EST': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [248],
        'name': u'Estonia',
        'ratingsbody': None,
        'slug': 'ee',
        'special': False,
        'weight': 0
    },
    'ETH': {
       'adolescent': False,
        'default_currency': u'ETB',
        'default_language': 'en',
        'id': 37,
        'mcc': [636],
        'name': u'Ethiopia',
        'ratingsbody': None,
        'slug': 'et',
        'special': False,
        'weight': 0
    },
    'FIN': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [244],
        'name': u'Finland',
        'ratingsbody': None,
        'slug': 'fi',
        'special': False,
        'weight': 0
    },
    'FJI': {
       'adolescent': False,
        'default_currency': u'FJD',
        'default_language': 'en',
        'id': 37,
        'mcc': [542],
        'name': u'Fiji',
        'ratingsbody': None,
        'slug': 'fj',
        'special': False,
        'weight': 0
    },
    'FLK': {
       'adolescent': False,
        'default_currency': u'FKP',
        'default_language': 'en',
        'id': 37,
        'mcc': [750],
        'name': u'Falkland Islands (Malvinas)',
        'ratingsbody': None,
        'slug': 'fk',
        'special': False,
        'weight': 0
    },
    'FRA': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'fr',
        'id': 30,
        'mcc': [208],
        'name': 'France',
        'ratingsbody': 'PEGI',
        'slug': 'fr',
        'special': False,
        'weight': 0
    },
    'FRO': {
       'adolescent': False,
        'default_currency': u'DKK',
        'default_language': 'en',
        'id': 37,
        'mcc': [288],
        'name': u'Faroe Islands',
        'ratingsbody': None,
        'slug': 'fo',
        'special': False,
        'weight': 0
    },
    'FSM': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [550],
        'name': u'Micronesia, Federated States of',
        'ratingsbody': None,
        'slug': 'fm',
        'special': False,
        'weight': 0
    },
    'GAB': {
       'adolescent': False,
        'default_currency': u'XAF',
        'default_language': 'en',
        'id': 37,
        'mcc': [628],
        'name': u'Gabon',
        'ratingsbody': None,
        'slug': 'ga',
        'special': False,
        'weight': 0
    },
    'GBR': {
       'adolescent': True,
        'default_currency': 'GBP',
        'default_language': 'en-US',
        'id': 4,
        'mcc': [235],
        'name': 'United Kingdom',
        'ratingsbody': 'PEGI',
        'slug': 'uk',
        'special': False,
        'weight': 0
    },
    'GEO': {
       'adolescent': False,
        'default_currency': u'GEL',
        'default_language': 'en',
        'id': 37,
        'mcc': [282, 289],
        'name': u'Georgia',
        'ratingsbody': None,
        'slug': 'ge',
        'special': False,
        'weight': 0
    },
    'GGY': {
       'adolescent': False,
        'default_currency': u'GBP',
        'default_language': 'en',
        'id': 37,
        'mcc': [234],
        'name': u'Guernsey',
        'ratingsbody': None,
        'slug': 'gg',
        'special': False,
        'weight': 0
    },
    'GHA': {
       'adolescent': False,
        'default_currency': u'GHS',
        'default_language': 'en',
        'id': 37,
        'mcc': [620],
        'name': u'Ghana',
        'ratingsbody': None,
        'slug': 'gh',
        'special': False,
        'weight': 0
    },
    'GIB': {
       'adolescent': False,
        'default_currency': u'GIP',
        'default_language': 'en',
        'id': 37,
        'mcc': [266],
        'name': u'Gibraltar',
        'ratingsbody': None,
        'slug': 'gi',
        'special': False,
        'weight': 0
    },
    'GIN': {
       'adolescent': False,
        'default_currency': u'GNF',
        'default_language': 'en',
        'id': 37,
        'mcc': [611],
        'name': u'Guinea',
        'ratingsbody': None,
        'slug': 'gn',
        'special': False,
        'weight': 0
    },
    'GLP': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [340],
        'name': u'Guadeloupe',
        'ratingsbody': None,
        'slug': 'gp',
        'special': False,
        'weight': 0
    },
    'GMB': {
       'adolescent': False,
        'default_currency': u'GMD',
        'default_language': 'en',
        'id': 37,
        'mcc': [607],
        'name': u'Gambia',
        'ratingsbody': None,
        'slug': 'gm',
        'special': False,
        'weight': 0
    },
    'GNB': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [632],
        'name': u'Guinea-Bissau',
        'ratingsbody': None,
        'slug': 'gw',
        'special': False,
        'weight': 0
    },
    'GNQ': {
       'adolescent': False,
        'default_currency': u'XAF',
        'default_language': 'en',
        'id': 37,
        'mcc': [627],
        'name': u'Equatorial Guinea',
        'ratingsbody': None,
        'slug': 'gq',
        'special': False,
        'weight': 0
    },
    'GRC': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'el',
        'id': 17,
        'mcc': [202],
        'name': 'Greece',
        'ratingsbody': 'PEGI',
        'slug': 'gr',
        'special': False,
        'weight': 0
    },
    'GRD': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [352],
        'name': u'Grenada',
        'ratingsbody': None,
        'slug': 'gd',
        'special': False,
        'weight': 0
    },
    'GRL': {
       'adolescent': False,
        'default_currency': u'DKK',
        'default_language': 'en',
        'id': 37,
        'mcc': [290],
        'name': u'Greenland',
        'ratingsbody': None,
        'slug': 'gl',
        'special': False,
        'weight': 0
    },
    'GTM': {
       'adolescent': True,
        'default_currency': 'GTQ',
        'default_language': 'es',
        'id': 25,
        'mcc': [704],
        'name': 'Guatemala',
        'ratingsbody': 'ESRB',
        'slug': 'gt',
        'special': False,
        'weight': 0
    },
    'GUF': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [340],
        'name': u'French Guiana',
        'ratingsbody': None,
        'slug': 'gf',
        'special': False,
        'weight': 0
    },
    'GUM': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [310, 311],
        'name': u'Guam',
        'ratingsbody': None,
        'slug': 'gu',
        'special': False,
        'weight': 0
    },
    'GUY': {
       'adolescent': False,
        'default_currency': u'GYD',
        'default_language': 'en',
        'id': 37,
        'mcc': [738],
        'name': u'Guyana',
        'ratingsbody': None,
        'slug': 'gy',
        'special': False,
        'weight': 0
    },
    'HKG': {
       'adolescent': False,
        'default_currency': u'HKD',
        'default_language': 'en',
        'id': 37,
        'mcc': [454],
        'name': u'Hong Kong',
        'ratingsbody': None,
        'slug': 'hk',
        'special': False,
        'weight': 0
    },
    'HMD': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Heard Island and McDonald Islands',
        'ratingsbody': None,
        'slug': 'hm',
        'special': False,
        'weight': 0
    },
    'HND': {
       'adolescent': False,
        'default_currency': u'HNL',
        'default_language': 'en',
        'id': 37,
        'mcc': [708],
        'name': u'Honduras',
        'ratingsbody': None,
        'slug': 'hn',
        'special': False,
        'weight': 0
    },
    'HRV': {
       'adolescent': False,
        'default_currency': u'HRK',
        'default_language': 'en',
        'id': 37,
        'mcc': [219],
        'name': u'Croatia',
        'ratingsbody': None,
        'slug': 'hr',
        'special': False,
        'weight': 0
    },
    'HTI': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [372],
        'name': u'Haiti',
        'ratingsbody': None,
        'slug': 'ht',
        'special': False,
        'weight': 0
    },
    'HUN': {
       'adolescent': True,
        'default_currency': 'HUF',
        'default_language': 'hu',
        'id': 13,
        'mcc': [216],
        'name': 'Hungary',
        'ratingsbody': 'PEGI',
        'slug': 'hu',
        'special': False,
        'weight': 0
    },
    'IDN': {
       'adolescent': False,
        'default_currency': u'IDR',
        'default_language': 'en',
        'id': 37,
        'mcc': [510],
        'name': u'Indonesia',
        'ratingsbody': None,
        'slug': 'id',
        'special': False,
        'weight': 0
    },
    'IMN': {
       'adolescent': False,
        'default_currency': u'GBP',
        'default_language': 'en',
        'id': 37,
        'mcc': [234],
        'name': u'Isle of Man',
        'ratingsbody': None,
        'slug': 'im',
        'special': False,
        'weight': 0
    },
    'IND': {
       'adolescent': True,
        'default_currency': 'INR',
        'default_language': 'en',
        'id': 32,
        'low_memory': True,
        'mcc': [405],
        'name': 'India',
        'ratingsbody': None,
        'slug': 'in',
        'weight': 0
    },
    'IOT': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'British Indian Ocean Territory',
        'ratingsbody': None,
        'slug': 'io',
        'special': False,
        'weight': 0
    },
    'IRL': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [272],
        'name': u'Ireland',
        'ratingsbody': None,
        'slug': 'ie',
        'special': False,
        'weight': 0
    },
    'IRN': {
       'adolescent': False,
        'default_currency': u'IRR',
        'default_language': 'en',
        'id': 37,
        'mcc': [432],
        'name': u'Iran, Islamic Republic of',
        'ratingsbody': None,
        'slug': 'ir',
        'special': False,
        'weight': 0
    },
    'IRQ': {
       'adolescent': False,
        'default_currency': u'IQD',
        'default_language': 'en',
        'id': 37,
        'mcc': [418],
        'name': u'Iraq',
        'ratingsbody': None,
        'slug': 'iq',
        'special': False,
        'weight': 0
    },
    'ISL': {
       'adolescent': False,
        'default_currency': u'ISK',
        'default_language': 'en',
        'id': 37,
        'mcc': [274],
        'name': u'Iceland',
        'ratingsbody': None,
        'slug': 'is',
        'special': False,
        'weight': 0
    },
    'ISR': {
       'adolescent': False,
        'default_currency': u'ILS',
        'default_language': 'en',
        'id': 37,
        'mcc': [425],
        'name': u'Israel',
        'ratingsbody': None,
        'slug': 'il',
        'special': False,
        'weight': 0
    },
    'ITA': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'it',
        'id': 22,
        'mcc': [222],
        'name': 'Italy',
        'ratingsbody': 'PEGI',
        'slug': 'it',
        'special': False,
        'weight': 0
    },
    'JAM': {
       'adolescent': False,
        'default_currency': u'JMD',
        'default_language': 'en',
        'id': 37,
        'mcc': [338],
        'name': u'Jamaica',
        'ratingsbody': None,
        'slug': 'jm',
        'special': False,
        'weight': 0
    },
    'JEY': {
       'adolescent': False,
        'default_currency': u'GBP',
        'default_language': 'en',
        'id': 37,
        'mcc': [234],
        'name': u'Jersey',
        'ratingsbody': None,
        'slug': 'je',
        'special': False,
        'weight': 0
    },
    'JOR': {
       'adolescent': False,
        'default_currency': u'JOD',
        'default_language': 'en',
        'id': 37,
        'mcc': [416],
        'name': u'Jordan',
        'ratingsbody': None,
        'slug': 'jo',
        'special': False,
        'weight': 0
    },
    'JPN': {
       'adolescent': True,
        'default_currency': 'JPY',
        'default_language': 'ja',
        'id': 33,
        'mcc': [440],
        'name': 'Japan',
        'slug': 'jp',
        'special': False,
        'weight': 0
    },
    'KAZ': {
       'adolescent': False,
        'default_currency': u'KZT',
        'default_language': 'en',
        'id': 37,
        'mcc': [401],
        'name': u'Kazakhstan',
        'ratingsbody': None,
        'slug': 'kz',
        'special': False,
        'weight': 0
    },
    'KEN': {
       'adolescent': False,
        'default_currency': u'KES',
        'default_language': 'en',
        'id': 37,
        'mcc': [639],
        'name': u'Kenya',
        'ratingsbody': None,
        'slug': 'ke',
        'special': False,
        'weight': 0
    },
    'KGZ': {
       'adolescent': False,
        'default_currency': u'KGS',
        'default_language': 'en',
        'id': 37,
        'mcc': [437],
        'name': u'Kyrgyzstan',
        'ratingsbody': None,
        'slug': 'kg',
        'special': False,
        'weight': 0
    },
    'KHM': {
       'adolescent': False,
        'default_currency': u'KHR',
        'default_language': 'en',
        'id': 37,
        'mcc': [456],
        'name': u'Cambodia',
        'ratingsbody': None,
        'slug': 'kh',
        'special': False,
        'weight': 0
    },
    'KIR': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [545],
        'name': u'Kiribati',
        'ratingsbody': None,
        'slug': 'ki',
        'special': False,
        'weight': 0
    },
    'KNA': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [356],
        'name': u'Saint Kitts and Nevis',
        'ratingsbody': None,
        'slug': 'kn',
        'special': False,
        'weight': 0
    },
    'KOR': {
       'adolescent': False,
        'default_currency': u'KRW',
        'default_language': 'en',
        'id': 37,
        'mcc': [450],
        'name': u'Korea, Republic of',
        'ratingsbody': None,
        'slug': 'kr',
        'special': False,
        'weight': 0
    },
    'KWT': {
       'adolescent': False,
        'default_currency': u'KWD',
        'default_language': 'en',
        'id': 37,
        'mcc': [419],
        'name': u'Kuwait',
        'ratingsbody': None,
        'slug': 'kw',
        'special': False,
        'weight': 0
    },
    'LAO': {
       'adolescent': False,
        'default_currency': u'LAK',
        'default_language': 'en',
        'id': 37,
        'mcc': [457],
        'name': u"Lao People's Democratic Republic",
        'ratingsbody': None,
        'slug': 'la',
        'special': False,
        'weight': 0
    },
    'LBN': {
       'adolescent': False,
        'default_currency': u'LBP',
        'default_language': 'en',
        'id': 37,
        'mcc': [415],
        'name': u'Lebanon',
        'ratingsbody': None,
        'slug': 'lb',
        'special': False,
        'weight': 0
    },
    'LBR': {
       'adolescent': False,
        'default_currency': u'LRD',
        'default_language': 'en',
        'id': 37,
        'mcc': [618],
        'name': u'Liberia',
        'ratingsbody': None,
        'slug': 'lr',
        'special': False,
        'weight': 0
    },
    'LBY': {
       'adolescent': False,
        'default_currency': u'LYD',
        'default_language': 'en',
        'id': 37,
        'mcc': [606],
        'name': u'Libya',
        'ratingsbody': None,
        'slug': 'ly',
        'special': False,
        'weight': 0
    },
    'LCA': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [358],
        'name': u'Saint Lucia',
        'ratingsbody': None,
        'slug': 'lc',
        'special': False,
        'weight': 0
    },
    'LIE': {
       'adolescent': False,
        'default_currency': u'CHF',
        'default_language': 'en',
        'id': 37,
        'mcc': [295],
        'name': u'Liechtenstein',
        'ratingsbody': None,
        'slug': 'li',
        'special': False,
        'weight': 0
    },
    'LKA': {
       'adolescent': False,
        'default_currency': u'LKR',
        'default_language': 'en',
        'id': 37,
        'mcc': [413],
        'name': u'Sri Lanka',
        'ratingsbody': None,
        'slug': 'lk',
        'special': False,
        'weight': 0
    },
    'LSO': {
       'adolescent': False,
        'default_currency': u'ZAR',
        'default_language': 'en',
        'id': 37,
        'mcc': [651],
        'name': u'Lesotho',
        'ratingsbody': None,
        'slug': 'ls',
        'special': False,
        'weight': 0
    },
    'LTU': {
       'adolescent': True,
        'default_currency': 'LTL',
        'default_language': 'lt',
        'id': 36,
        'mcc': [370],
        'name': 'Lithuania',
        'slug': 'lt',
        'special': False,
        'weight': 0
    },
    'LUX': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [270],
        'name': u'Luxembourg',
        'ratingsbody': None,
        'slug': 'lu',
        'special': False,
        'weight': 0
    },
    'LVA': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [247],
        'name': u'Latvia',
        'ratingsbody': None,
        'slug': 'lv',
        'special': False,
        'weight': 0
    },
    'MAC': {
       'adolescent': False,
        'default_currency': u'MOP',
        'default_language': 'en',
        'id': 37,
        'mcc': [455],
        'name': u'Macao',
        'ratingsbody': None,
        'slug': 'mo',
        'special': False,
        'weight': 0
    },
    'MAF': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [340],
        'name': u'Saint Martin (French part)',
        'ratingsbody': None,
        'slug': 'mf',
        'special': False,
        'weight': 0
    },
    'MAR': {
       'adolescent': False,
        'default_currency': u'MAD',
        'default_language': 'en',
        'id': 37,
        'mcc': [604],
        'name': u'Morocco',
        'ratingsbody': None,
        'slug': 'ma',
        'special': False,
        'weight': 0
    },
    'MCO': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [212],
        'name': u'Monaco',
        'ratingsbody': None,
        'slug': 'mc',
        'special': False,
        'weight': 0
    },
    'MDA': {
       'adolescent': False,
        'default_currency': u'MDL',
        'default_language': 'en',
        'id': 37,
        'mcc': [259],
        'name': u'Moldova, Republic of',
        'ratingsbody': None,
        'slug': 'md',
        'special': False,
        'weight': 0
    },
    'MDG': {
       'adolescent': False,
        'default_currency': u'MGA',
        'default_language': 'en',
        'id': 37,
        'mcc': [646],
        'name': u'Madagascar',
        'ratingsbody': None,
        'slug': 'mg',
        'special': False,
        'weight': 0
    },
    'MDV': {
       'adolescent': False,
        'default_currency': u'MVR',
        'default_language': 'en',
        'id': 37,
        'mcc': [472],
        'name': u'Maldives',
        'ratingsbody': None,
        'slug': 'mv',
        'special': False,
        'weight': 0
    },
    'MEX': {
       'adolescent': False,
        'default_currency': 'MXN',
        'default_language': 'es',
        'id': 12,
        'mcc': [334],
        'name': 'Mexico',
        'ratingsbody': 'ESRB',
        'slug': 'mx',
        'special': False,
        'weight': 0
    },
    'MHL': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [551],
        'name': u'Marshall Islands',
        'ratingsbody': None,
        'slug': 'mh',
        'special': False,
        'weight': 0
    },
    'MKD': {
       'adolescent': False,
        'default_currency': u'MKD',
        'default_language': 'en',
        'id': 37,
        'mcc': [294],
        'name': u'Macedonia, the former Yugoslav Republic of',
        'ratingsbody': None,
        'slug': 'mk',
        'special': False,
        'weight': 0
    },
    'MLI': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [610],
        'name': u'Mali',
        'ratingsbody': None,
        'slug': 'ml',
        'special': False,
        'weight': 0
    },
    'MLT': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [278],
        'name': u'Malta',
        'ratingsbody': None,
        'slug': 'mt',
        'special': False,
        'weight': 0
    },
    'MMR': {
       'adolescent': False,
        'default_currency': u'MMK',
        'default_language': 'en',
        'id': 37,
        'mcc': [414],
        'name': u'Myanmar',
        'ratingsbody': None,
        'slug': 'mm',
        'special': False,
        'weight': 0
    },
    'MNE': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'srp',
        'id': 15,
        'mcc': [297],
        'name': 'Montenegro',
        'slug': 'me',
        'special': False,
        'weight': 0
    },
    'MNG': {
       'adolescent': False,
        'default_currency': u'MNT',
        'default_language': 'en',
        'id': 37,
        'mcc': [428],
        'name': u'Mongolia',
        'ratingsbody': None,
        'slug': 'mn',
        'special': False,
        'weight': 0
    },
    'MNP': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Northern Mariana Islands',
        'ratingsbody': None,
        'slug': 'mp',
        'special': False,
        'weight': 0
    },
    'MOZ': {
       'adolescent': False,
        'default_currency': u'MZN',
        'default_language': 'en',
        'id': 37,
        'mcc': [643],
        'name': u'Mozambique',
        'ratingsbody': None,
        'slug': 'mz',
        'special': False,
        'weight': 0
    },
    'MRT': {
       'adolescent': False,
        'default_currency': u'MRO',
        'default_language': 'en',
        'id': 37,
        'mcc': [609],
        'name': u'Mauritania',
        'ratingsbody': None,
        'slug': 'mr',
        'special': False,
        'weight': 0
    },
    'MSR': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [354],
        'name': u'Montserrat',
        'ratingsbody': None,
        'slug': 'ms',
        'special': False,
        'weight': 0
    },
    'MTQ': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [340],
        'name': u'Martinique',
        'ratingsbody': None,
        'slug': 'mq',
        'special': False,
        'weight': 0
    },
    'MUS': {
       'adolescent': False,
        'default_currency': u'MUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [617],
        'name': u'Mauritius',
        'ratingsbody': None,
        'slug': 'mu',
        'special': False,
        'weight': 0
    },
    'MWI': {
       'adolescent': False,
        'default_currency': u'MWK',
        'default_language': 'en',
        'id': 37,
        'mcc': [650],
        'name': u'Malawi',
        'ratingsbody': None,
        'slug': 'mw',
        'special': False,
        'weight': 0
    },
    'MYS': {
       'adolescent': False,
        'default_currency': u'MYR',
        'default_language': 'en',
        'id': 37,
        'mcc': [502],
        'name': u'Malaysia',
        'ratingsbody': None,
        'slug': 'my',
        'special': False,
        'weight': 0
    },
    'MYT': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [208],
        'name': u'Mayotte',
        'ratingsbody': None,
        'slug': 'yt',
        'special': False,
        'weight': 0
    },
    'NAM': {
       'adolescent': False,
        'default_currency': u'ZAR',
        'default_language': 'en',
        'id': 37,
        'mcc': [649],
        'name': u'Namibia',
        'ratingsbody': None,
        'slug': 'na',
        'special': False,
        'weight': 0
    },
    'NCL': {
       'adolescent': False,
        'default_currency': u'XPF',
        'default_language': 'en',
        'id': 37,
        'mcc': [546],
        'name': u'New Caledonia',
        'ratingsbody': None,
        'slug': 'nc',
        'special': False,
        'weight': 0
    },
    'NER': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [614],
        'name': u'Niger',
        'ratingsbody': None,
        'slug': 'ne',
        'special': False,
        'weight': 0
    },
    'NFK': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [505],
        'name': u'Norfolk Island',
        'ratingsbody': None,
        'slug': 'nf',
        'special': False,
        'weight': 0
    },
    'NGA': {
       'adolescent': False,
        'default_currency': u'NGN',
        'default_language': 'en',
        'id': 37,
        'mcc': [621],
        'name': u'Nigeria',
        'ratingsbody': None,
        'slug': 'ng',
        'special': False,
        'weight': 0
    },
    'NIC': {
       'adolescent': True,
        'default_currency': 'NIO',
        'default_language': 'es',
        'id': 29,
        'mcc': [710],
        'name': 'Nicaragua',
        'ratingsbody': 'ESRB',
        'slug': 'ni',
        'special': False,
        'weight': 0
    },
    'NIU': {
       'adolescent': False,
        'default_currency': u'NZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [555],
        'name': u'Niue',
        'ratingsbody': None,
        'slug': 'nu',
        'special': False,
        'weight': 0
    },
    'NLD': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [204],
        'name': u'Netherlands',
        'ratingsbody': None,
        'slug': 'nl',
        'special': False,
        'weight': 0
    },
    'NOR': {
       'adolescent': False,
        'default_currency': u'NOK',
        'default_language': 'en',
        'id': 37,
        'mcc': [242],
        'name': u'Norway',
        'ratingsbody': None,
        'slug': 'no',
        'special': False,
        'weight': 0
    },
    'NPL': {
       'adolescent': False,
        'default_currency': u'NPR',
        'default_language': 'en',
        'id': 37,
        'mcc': [429],
        'name': u'Nepal',
        'ratingsbody': None,
        'slug': 'np',
        'special': False,
        'weight': 0
    },
    'NRU': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [536],
        'name': u'Nauru',
        'ratingsbody': None,
        'slug': 'nr',
        'special': False,
        'weight': 0
    },
    'NZL': {
       'adolescent': False,
        'default_currency': u'NZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [530],
        'name': u'New Zealand',
        'ratingsbody': None,
        'slug': 'nz',
        'special': False,
        'weight': 0
    },
    'OMN': {
       'adolescent': False,
        'default_currency': u'OMR',
        'default_language': 'en',
        'id': 37,
        'mcc': [422],
        'name': u'Oman',
        'ratingsbody': None,
        'slug': 'om',
        'special': False,
        'weight': 0
    },
    'PAK': {
       'adolescent': False,
        'default_currency': u'PKR',
        'default_language': 'en',
        'id': 37,
        'mcc': [410],
        'name': u'Pakistan',
        'ratingsbody': None,
        'slug': 'pk',
        'special': False,
        'weight': 0
    },
    'PAN': {
       'adolescent': True,
        'default_currency': 'USD',
        'default_language': 'es',
        'id': 28,
        'mcc': [714],
        'name': 'Panama',
        'ratingsbody': 'ESRB',
        'slug': 'pa',
        'special': False,
        'weight': 0
    },
    'PCN': {
       'adolescent': False,
        'default_currency': u'NZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Pitcairn',
        'ratingsbody': None,
        'slug': 'pn',
        'special': False,
        'weight': 0
    },
    'PER': {
       'adolescent': False,
        'default_currency': 'PEN',
        'default_language': 'es',
        'id': 18,
        'mcc': [716],
        'name': 'Peru',
        'ratingsbody': 'ESRB',
        'slug': 'pe',
        'special': False,
        'weight': 0
    },
    'PHL': {
       'adolescent': True,
        'default_currency': 'PHP',
        'default_language': 'en',
        'id': 35,
        'low_memory': True,
        'mcc': [515],
        'name': 'Philippines',
        'ratingsbody': None,
        'slug': 'ph',
        'weight': 0
    },
    'PLW': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [552],
        'name': u'Palau',
        'ratingsbody': None,
        'slug': 'pw',
        'special': False,
        'weight': 0
    },
    'PNG': {
       'adolescent': False,
        'default_currency': u'PGK',
        'default_language': 'en',
        'id': 37,
        'mcc': [537],
        'name': u'Papua New Guinea',
        'ratingsbody': None,
        'slug': 'pg',
        'special': False,
        'weight': 0
    },
    'POL': {
       'adolescent': True,
        'default_currency': 'PLN',
        'default_language': 'pl',
        'id': 11,
        'mcc': [260],
        'name': 'Poland',
        'ratingsbody': 'PEGI',
        'slug': 'pl',
        'special': False,
        'weight': 0
    },
    'PRI': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [310, 330],
        'name': u'Puerto Rico',
        'ratingsbody': None,
        'slug': 'pr',
        'special': False,
        'weight': 0
    },
    'PRK': {
       'adolescent': False,
        'default_currency': u'KPW',
        'default_language': 'en',
        'id': 37,
        'mcc': [467],
        'name': u"Korea, Democratic People's Republic of",
        'ratingsbody': None,
        'slug': 'kp',
        'special': False,
        'weight': 0
    },
    'PRT': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [268],
        'name': u'Portugal',
        'ratingsbody': None,
        'slug': 'pt',
        'special': False,
        'weight': 0
    },
    'PRY': {
       'adolescent': False,
        'default_currency': u'PYG',
        'default_language': 'en',
        'id': 37,
        'mcc': [744],
        'name': u'Paraguay',
        'ratingsbody': None,
        'slug': 'py',
        'special': False,
        'weight': 0
    },
    'PSE': {
       'adolescent': False,
        'default_currency': u'',
        'default_language': 'en',
        'id': 37,
        'mcc': [425],
        'name': u'Palestine, State of',
        'ratingsbody': None,
        'slug': 'ps',
        'special': False,
        'weight': 0
    },
    'PYF': {
       'adolescent': False,
        'default_currency': u'XPF',
        'default_language': 'en',
        'id': 37,
        'mcc': [547],
        'name': u'French Polynesia',
        'ratingsbody': None,
        'slug': 'pf',
        'special': False,
        'weight': 0
    },
    'QAT': {
       'adolescent': False,
        'default_currency': u'QAR',
        'default_language': 'en',
        'id': 37,
        'mcc': [427],
        'name': u'Qatar',
        'ratingsbody': None,
        'slug': 'qa',
        'special': False,
        'weight': 0
    },
    'REU': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [647],
        'name': u'R\xe9union',
        'ratingsbody': None,
        'slug': 're',
        'special': False,
        'weight': 0
    },
    'ROU': {
       'adolescent': False,
        'default_currency': u'RON',
        'default_language': 'en',
        'id': 37,
        'mcc': [226],
        'name': u'Romania',
        'ratingsbody': None,
        'slug': 'ro',
        'special': False,
        'weight': 0
    },
    'RUS': {
       'adolescent': True,
        'default_currency': 'EUR',
        'default_language': 'ru',
        'id': 36,
        'mcc': [250],
        'name': 'Russia',
        'slug': 'ru',
        'special': False,
        'weight': 0
    },
    'RWA': {
       'adolescent': False,
        'default_currency': u'RWF',
        'default_language': 'en',
        'id': 37,
        'mcc': [635],
        'name': u'Rwanda',
        'ratingsbody': None,
        'slug': 'rw',
        'special': False,
        'weight': 0
    },
    'SAU': {
       'adolescent': False,
        'default_currency': u'SAR',
        'default_language': 'en',
        'id': 37,
        'mcc': [420],
        'name': u'Saudi Arabia',
        'ratingsbody': None,
        'slug': 'sa',
        'special': False,
        'weight': 0
    },
    'SDN': {
       'adolescent': False,
        'default_currency': u'SDG',
        'default_language': 'en',
        'id': 37,
        'mcc': [634],
        'name': u'Sudan',
        'ratingsbody': None,
        'slug': 'sd',
        'special': False,
        'weight': 0
    },
    'SEN': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [608],
        'name': u'Senegal',
        'ratingsbody': None,
        'slug': 'sn',
        'special': False,
        'weight': 0
    },
    'SGP': {
       'adolescent': False,
        'default_currency': u'SGD',
        'default_language': 'en',
        'id': 37,
        'mcc': [525],
        'name': u'Singapore',
        'ratingsbody': None,
        'slug': 'sg',
        'special': False,
        'weight': 0
    },
    'SGS': {
       'adolescent': False,
        'default_currency': u'',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'South Georgia and the South Sandwich Islands',
        'ratingsbody': None,
        'slug': 'gs',
        'special': False,
        'weight': 0
    },
    'SHN': {
       'adolescent': False,
        'default_currency': u'SHP',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Saint Helena, Ascension and Tristan da Cunha',
        'ratingsbody': None,
        'slug': 'sh',
        'special': False,
        'weight': 0
    },
    'SJM': {
       'adolescent': False,
        'default_currency': u'NOK',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Svalbard and Jan Mayen',
        'ratingsbody': None,
        'slug': 'sj',
        'special': False,
        'weight': 0
    },
    'SLB': {
       'adolescent': False,
        'default_currency': u'SBD',
        'default_language': 'en',
        'id': 37,
        'mcc': [540],
        'name': u'Solomon Islands',
        'ratingsbody': None,
        'slug': 'sb',
        'special': False,
        'weight': 0
    },
    'SLE': {
       'adolescent': False,
        'default_currency': u'SLL',
        'default_language': 'en',
        'id': 37,
        'mcc': [619],
        'name': u'Sierra Leone',
        'ratingsbody': None,
        'slug': 'sl',
        'special': False,
        'weight': 0
    },
    'SLV': {
       'adolescent': True,
        'default_currency': 'USD',
        'default_language': 'es',
        'id': 24,
        'mcc': [706],
        'name': 'El Salvador',
        'ratingsbody': 'ESRB',
        'slug': 'sv',
        'special': False,
        'weight': 0
    },
    'SMR': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [292],
        'name': u'San Marino',
        'ratingsbody': None,
        'slug': 'sm',
        'special': False,
        'weight': 0
    },
    'SOM': {
       'adolescent': False,
        'default_currency': u'SOS',
        'default_language': 'en',
        'id': 37,
        'mcc': [637],
        'name': u'Somalia',
        'ratingsbody': None,
        'slug': 'so',
        'special': False,
        'weight': 0
    },
    'SPM': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [308],
        'name': u'Saint Pierre and Miquelon',
        'ratingsbody': None,
        'slug': 'pm',
        'special': False,
        'weight': 0
    },
    'SRB': {
       'adolescent': True,
        'default_currency': 'RSD',
        'default_language': 'sr',
        'id': 16,
        'mcc': [220],
        'name': 'Serbia',
        'ratingsbody': None,
        'slug': 'rs',
        'special': False,
        'weight': 0
    },
    'SSD': {
       'adolescent': False,
        'default_currency': u'SSP',
        'default_language': 'en',
        'id': 37,
        'mcc': [659],
        'name': u'South Sudan',
        'ratingsbody': None,
        'slug': 'ss',
        'special': False,
        'weight': 0
    },
    'STP': {
       'adolescent': False,
        'default_currency': u'STD',
        'default_language': 'en',
        'id': 37,
        'mcc': [626],
        'name': u'Sao Tome and Principe',
        'ratingsbody': None,
        'slug': 'st',
        'special': False,
        'weight': 0
    },
    'SUR': {
       'adolescent': False,
        'default_currency': u'SRD',
        'default_language': 'en',
        'id': 37,
        'mcc': [746],
        'name': u'Suriname',
        'ratingsbody': None,
        'slug': 'sr',
        'special': False,
        'weight': 0
    },
    'SVK': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [231],
        'name': u'Slovakia',
        'ratingsbody': None,
        'slug': 'sk',
        'special': False,
        'weight': 0
    },
    'SVN': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [293],
        'name': u'Slovenia',
        'ratingsbody': None,
        'slug': 'si',
        'special': False,
        'weight': 0
    },
    'SWE': {
       'adolescent': False,
        'default_currency': u'SEK',
        'default_language': 'en',
        'id': 37,
        'mcc': [240],
        'name': u'Sweden',
        'ratingsbody': None,
        'slug': 'se',
        'special': False,
        'weight': 0
    },
    'SWZ': {
       'adolescent': False,
        'default_currency': u'SZL',
        'default_language': 'en',
        'id': 37,
        'mcc': [653],
        'name': u'Swaziland',
        'ratingsbody': None,
        'slug': 'sz',
        'special': False,
        'weight': 0
    },
    'SXM': {
       'adolescent': False,
        'default_currency': u'ANG',
        'default_language': 'en',
        'id': 37,
        'mcc': [362],
        'name': u'Sint Maarten (Dutch part)',
        'ratingsbody': None,
        'slug': 'sx',
        'special': False,
        'weight': 0
    },
    'SYC': {
       'adolescent': False,
        'default_currency': u'SCR',
        'default_language': 'en',
        'id': 37,
        'mcc': [633],
        'name': u'Seychelles',
        'ratingsbody': None,
        'slug': 'sc',
        'special': False,
        'weight': 0
    },
    'SYR': {
       'adolescent': False,
        'default_currency': u'SYP',
        'default_language': 'en',
        'id': 37,
        'mcc': [417],
        'name': u'Syrian Arab Republic',
        'ratingsbody': None,
        'slug': 'sy',
        'special': False,
        'weight': 0
    },
    'TCA': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [338, 376],
        'name': u'Turks and Caicos Islands',
        'ratingsbody': None,
        'slug': 'tc',
        'special': False,
        'weight': 0
    },
    'TCD': {
       'adolescent': False,
        'default_currency': u'XAF',
        'default_language': 'en',
        'id': 37,
        'mcc': [622],
        'name': u'Chad',
        'ratingsbody': None,
        'slug': 'td',
        'special': False,
        'weight': 0
    },
    'TGO': {
       'adolescent': False,
        'default_currency': u'XOF',
        'default_language': 'en',
        'id': 37,
        'mcc': [615],
        'name': u'Togo',
        'ratingsbody': None,
        'slug': 'tg',
        'special': False,
        'weight': 0
    },
    'THA': {
       'adolescent': False,
        'default_currency': u'THB',
        'default_language': 'en',
        'id': 37,
        'mcc': [520],
        'name': u'Thailand',
        'ratingsbody': None,
        'slug': 'th',
        'special': False,
        'weight': 0
    },
    'TJK': {
       'adolescent': False,
        'default_currency': u'TJS',
        'default_language': 'en',
        'id': 37,
        'mcc': [436],
        'name': u'Tajikistan',
        'ratingsbody': None,
        'slug': 'tj',
        'special': False,
        'weight': 0
    },
    'TKL': {
       'adolescent': False,
        'default_currency': u'NZD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Tokelau',
        'ratingsbody': None,
        'slug': 'tk',
        'special': False,
        'weight': 0
    },
    'TKM': {
       'adolescent': False,
        'default_currency': u'TMT',
        'default_language': 'en',
        'id': 37,
        'mcc': [438],
        'name': u'Turkmenistan',
        'ratingsbody': None,
        'slug': 'tm',
        'special': False,
        'weight': 0
    },
    'TLS': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [514],
        'name': u'Timor-Leste',
        'ratingsbody': None,
        'slug': 'tl',
        'special': False,
        'weight': 0
    },
    'TON': {
       'adolescent': False,
        'default_currency': u'TOP',
        'default_language': 'en',
        'id': 37,
        'mcc': [539],
        'name': u'Tonga',
        'ratingsbody': None,
        'slug': 'to',
        'special': False,
        'weight': 0
    },
    'TTO': {
       'adolescent': False,
        'default_currency': u'TTD',
        'default_language': 'en',
        'id': 37,
        'mcc': [374],
        'name': u'Trinidad and Tobago',
        'ratingsbody': None,
        'slug': 'tt',
        'special': False,
        'weight': 0
    },
    'TUN': {
       'adolescent': False,
        'default_currency': u'TND',
        'default_language': 'en',
        'id': 37,
        'mcc': [605],
        'name': u'Tunisia',
        'ratingsbody': None,
        'slug': 'tn',
        'special': False,
        'weight': 0
    },
    'TUR': {
       'adolescent': False,
        'default_currency': u'TRY',
        'default_language': 'en',
        'id': 37,
        'mcc': [286],
        'name': u'Turkey',
        'ratingsbody': None,
        'slug': 'tr',
        'special': False,
        'weight': 0
    },
    'TUV': {
       'adolescent': False,
        'default_currency': u'AUD',
        'default_language': 'en',
        'id': 37,
        'mcc': [553],
        'name': u'Tuvalu',
        'ratingsbody': None,
        'slug': 'tv',
        'special': False,
        'weight': 0
    },
    'TWN': {
       'adolescent': False,
        'default_currency': u'TWD',
        'default_language': 'en',
        'id': 37,
        'mcc': [466],
        'name': u'Taiwan, Province of China',
        'ratingsbody': None,
        'slug': 'tw',
        'special': False,
        'weight': 0
    },
    'TZA': {
       'adolescent': False,
        'default_currency': u'TZS',
        'default_language': 'en',
        'id': 37,
        'mcc': [640],
        'name': u'Tanzania, United Republic of',
        'ratingsbody': None,
        'slug': 'tz',
        'special': False,
        'weight': 0
    },
    'UGA': {
       'adolescent': False,
        'default_currency': u'UGX',
        'default_language': 'en',
        'id': 37,
        'mcc': [641],
        'name': u'Uganda',
        'ratingsbody': None,
        'slug': 'ug',
        'special': False,
        'weight': 0
    },
    'UKR': {
       'adolescent': False,
        'default_currency': u'UAH',
        'default_language': 'en',
        'id': 37,
        'mcc': [255],
        'name': u'Ukraine',
        'ratingsbody': None,
        'slug': 'ua',
        'special': False,
        'weight': 0
    },
    'UMI': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'United States Minor Outlying Islands',
        'ratingsbody': None,
        'slug': 'um',
        'special': False,
        'weight': 0
    },
    'URY': {
       'adolescent': False,
        'default_currency': 'UYU',
        'default_language': 'es',
        'id': 19,
        'mcc': [748],
        'name': 'Uruguay',
        'ratingsbody': 'ESRB',
        'slug': 'uy',
        'special': False,
        'weight': 0
    },
    'USA': {
       'adolescent': True,
        'default_currency': 'USD',
        'default_language': 'en-US',
        'id': 2,
        'mcc': [310],
        'name': 'United States',
        'ratingsbody': 'ESRB',
        'slug': 'us',
        'special': False,
        'weight': 1
    },
    'UZB': {
       'adolescent': False,
        'default_currency': u'UZS',
        'default_language': 'en',
        'id': 37,
        'mcc': [434],
        'name': u'Uzbekistan',
        'ratingsbody': None,
        'slug': 'uz',
        'special': False,
        'weight': 0
    },
    'VAT': {
       'adolescent': False,
        'default_currency': u'EUR',
        'default_language': 'en',
        'id': 37,
        'mcc': [225],
        'name': u'Holy See (Vatican City State)',
        'ratingsbody': None,
        'slug': 'va',
        'special': False,
        'weight': 0
    },
    'VCT': {
       'adolescent': False,
        'default_currency': u'XCD',
        'default_language': 'en',
        'id': 37,
        'mcc': [360],
        'name': u'Saint Vincent and the Grenadines',
        'ratingsbody': None,
        'slug': 'vc',
        'special': False,
        'weight': 0
    },
    'VEN': {
       'adolescent': False,
        'default_currency': 'USD',
        'default_language': 'es',
        'id': 10,
        'mcc': [734],
        'name': 'Venezuela',
        'ratingsbody': 'ESRB',
        'slug': 've',
        'special': False,
        'weight': 0
    },
    'VGB': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [348],
        'name': u'Virgin Islands, British',
        'ratingsbody': None,
        'slug': 'vg',
        'special': False,
        'weight': 0
    },
    'VIR': {
       'adolescent': False,
        'default_currency': u'USD',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Virgin Islands, U.S.',
        'ratingsbody': None,
        'slug': 'vi',
        'special': False,
        'weight': 0
    },
    'VNM': {
       'adolescent': False,
        'default_currency': u'VND',
        'default_language': 'en',
        'id': 37,
        'mcc': [452],
        'name': u'Viet Nam',
        'ratingsbody': None,
        'slug': 'vn',
        'special': False,
        'weight': 0
    },
    'VUT': {
       'adolescent': False,
        'default_currency': u'VUV',
        'default_language': 'en',
        'id': 37,
        'mcc': [541],
        'name': u'Vanuatu',
        'ratingsbody': None,
        'slug': 'vu',
        'special': False,
        'weight': 0
    },
    'WLF': {
       'adolescent': False,
        'default_currency': u'XPF',
        'default_language': 'en',
        'id': 37,
        'mcc': [],
        'name': u'Wallis and Futuna',
        'ratingsbody': None,
        'slug': 'wf',
        'special': False,
        'weight': 0
    },
    'WSM': {
       'adolescent': False,
        'default_currency': u'WST',
        'default_language': 'en',
        'id': 37,
        'mcc': [549],
        'name': u'Samoa',
        'ratingsbody': None,
        'slug': 'ws',
        'special': False,
        'weight': 0
    },
    'YEM': {
       'adolescent': False,
        'default_currency': u'YER',
        'default_language': 'en',
        'id': 37,
        'mcc': [421],
        'name': u'Yemen',
        'ratingsbody': None,
        'slug': 'ye',
        'special': False,
        'weight': 0
    },
    'ZAF': {
       'adolescent': False,
        'default_currency': 'ZAR',
        'default_language': 'en-US',
        'id': 37,
        'mcc': [655],
        'name': 'South Africa',
        'ratingsbody': None,
        'slug': 'za',
        'special': False,
        'weight': 0
    },
    'ZMB': {
       'adolescent': False,
        'default_currency': u'ZMW',
        'default_language': 'en',
        'id': 37,
        'mcc': [645],
        'name': u'Zambia',
        'ratingsbody': None,
        'slug': 'zm',
        'special': False,
        'weight': 0
    },
    'ZWE': {
       'adolescent': False,
        'default_currency': u'ZWL',
        'default_language': 'en',
        'id': 37,
        'mcc': [648],
        'name': u'Zimbabwe',
        'ratingsbody': None,
        'slug': 'zw',
        'special': False,
        'weight': 0
    },
}
